// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/paymentorder"
	"github.com/Wei-Shaw/sub2api/ent/rechargebonusrule"
)

// RechargeBonusRuleCreate is the builder for creating a RechargeBonusRule entity.
type RechargeBonusRuleCreate struct {
	config
	mutation *RechargeBonusRuleMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (_c *RechargeBonusRuleCreate) SetName(v string) *RechargeBonusRuleCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *RechargeBonusRuleCreate) SetEnabled(v bool) *RechargeBonusRuleCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *RechargeBonusRuleCreate) SetNillableEnabled(v *bool) *RechargeBonusRuleCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetPriority sets the "priority" field.
func (_c *RechargeBonusRuleCreate) SetPriority(v int) *RechargeBonusRuleCreate {
	_c.mutation.SetPriority(v)
	return _c
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_c *RechargeBonusRuleCreate) SetNillablePriority(v *int) *RechargeBonusRuleCreate {
	if v != nil {
		_c.SetPriority(*v)
	}
	return _c
}

// SetMinAmount sets the "min_amount" field.
func (_c *RechargeBonusRuleCreate) SetMinAmount(v float64) *RechargeBonusRuleCreate {
	_c.mutation.SetMinAmount(v)
	return _c
}

// SetMaxAmount sets the "max_amount" field.
func (_c *RechargeBonusRuleCreate) SetMaxAmount(v float64) *RechargeBonusRuleCreate {
	_c.mutation.SetMaxAmount(v)
	return _c
}

// SetNillableMaxAmount sets the "max_amount" field if the given value is not nil.
func (_c *RechargeBonusRuleCreate) SetNillableMaxAmount(v *float64) *RechargeBonusRuleCreate {
	if v != nil {
		_c.SetMaxAmount(*v)
	}
	return _c
}

// SetBonusType sets the "bonus_type" field.
func (_c *RechargeBonusRuleCreate) SetBonusType(v string) *RechargeBonusRuleCreate {
	_c.mutation.SetBonusType(v)
	return _c
}

// SetBonusValue sets the "bonus_value" field.
func (_c *RechargeBonusRuleCreate) SetBonusValue(v float64) *RechargeBonusRuleCreate {
	_c.mutation.SetBonusValue(v)
	return _c
}

// SetStartsAt sets the "starts_at" field.
func (_c *RechargeBonusRuleCreate) SetStartsAt(v time.Time) *RechargeBonusRuleCreate {
	_c.mutation.SetStartsAt(v)
	return _c
}

// SetNillableStartsAt sets the "starts_at" field if the given value is not nil.
func (_c *RechargeBonusRuleCreate) SetNillableStartsAt(v *time.Time) *RechargeBonusRuleCreate {
	if v != nil {
		_c.SetStartsAt(*v)
	}
	return _c
}

// SetEndsAt sets the "ends_at" field.
func (_c *RechargeBonusRuleCreate) SetEndsAt(v time.Time) *RechargeBonusRuleCreate {
	_c.mutation.SetEndsAt(v)
	return _c
}

// SetNillableEndsAt sets the "ends_at" field if the given value is not nil.
func (_c *RechargeBonusRuleCreate) SetNillableEndsAt(v *time.Time) *RechargeBonusRuleCreate {
	if v != nil {
		_c.SetEndsAt(*v)
	}
	return _c
}

// SetNotes sets the "notes" field.
func (_c *RechargeBonusRuleCreate) SetNotes(v string) *RechargeBonusRuleCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *RechargeBonusRuleCreate) SetNillableNotes(v *string) *RechargeBonusRuleCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *RechargeBonusRuleCreate) SetCreatedAt(v time.Time) *RechargeBonusRuleCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RechargeBonusRuleCreate) SetNillableCreatedAt(v *time.Time) *RechargeBonusRuleCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *RechargeBonusRuleCreate) SetUpdatedAt(v time.Time) *RechargeBonusRuleCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *RechargeBonusRuleCreate) SetNillableUpdatedAt(v *time.Time) *RechargeBonusRuleCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// AddPaymentOrderIDs adds the "payment_orders" edge to the PaymentOrder entity by IDs.
func (_c *RechargeBonusRuleCreate) AddPaymentOrderIDs(ids ...int64) *RechargeBonusRuleCreate {
	_c.mutation.AddPaymentOrderIDs(ids...)
	return _c
}

// AddPaymentOrders adds the "payment_orders" edges to the PaymentOrder entity.
func (_c *RechargeBonusRuleCreate) AddPaymentOrders(v ...*PaymentOrder) *RechargeBonusRuleCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPaymentOrderIDs(ids...)
}

// Mutation returns the RechargeBonusRuleMutation object of the builder.
func (_c *RechargeBonusRuleCreate) Mutation() *RechargeBonusRuleMutation {
	return _c.mutation
}

// Save creates the RechargeBonusRule in the database.
func (_c *RechargeBonusRuleCreate) Save(ctx context.Context) (*RechargeBonusRule, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RechargeBonusRuleCreate) SaveX(ctx context.Context) *RechargeBonusRule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RechargeBonusRuleCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RechargeBonusRuleCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RechargeBonusRuleCreate) defaults() {
	if _, ok := _c.mutation.Enabled(); !ok {
		v := rechargebonusrule.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.Priority(); !ok {
		v := rechargebonusrule.DefaultPriority
		_c.mutation.SetPriority(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := rechargebonusrule.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := rechargebonusrule.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RechargeBonusRuleCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "RechargeBonusRule.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := rechargebonusrule.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "RechargeBonusRule.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "RechargeBonusRule.enabled"`)}
	}
	if _, ok := _c.mutation.Priority(); !ok {
		return &ValidationError{Name: "priority", err: errors.New(`ent: missing required field "RechargeBonusRule.priority"`)}
	}
	if _, ok := _c.mutation.MinAmount(); !ok {
		return &ValidationError{Name: "min_amount", err: errors.New(`ent: missing required field "RechargeBonusRule.min_amount"`)}
	}
	if _, ok := _c.mutation.BonusType(); !ok {
		return &ValidationError{Name: "bonus_type", err: errors.New(`ent: missing required field "RechargeBonusRule.bonus_type"`)}
	}
	if v, ok := _c.mutation.BonusType(); ok {
		if err := rechargebonusrule.BonusTypeValidator(v); err != nil {
			return &ValidationError{Name: "bonus_type", err: fmt.Errorf(`ent: validator failed for field "RechargeBonusRule.bonus_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BonusValue(); !ok {
		return &ValidationError{Name: "bonus_value", err: errors.New(`ent: missing required field "RechargeBonusRule.bonus_value"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RechargeBonusRule.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "RechargeBonusRule.updated_at"`)}
	}
	return nil
}

func (_c *RechargeBonusRuleCreate) sqlSave(ctx context.Context) (*RechargeBonusRule, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RechargeBonusRuleCreate) createSpec() (*RechargeBonusRule, *sqlgraph.CreateSpec) {
	var (
		_node = &RechargeBonusRule{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(rechargebonusrule.Table, sqlgraph.NewFieldSpec(rechargebonusrule.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(rechargebonusrule.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(rechargebonusrule.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.Priority(); ok {
		_spec.SetField(rechargebonusrule.FieldPriority, field.TypeInt, value)
		_node.Priority = value
	}
	if value, ok := _c.mutation.MinAmount(); ok {
		_spec.SetField(rechargebonusrule.FieldMinAmount, field.TypeFloat64, value)
		_node.MinAmount = value
	}
	if value, ok := _c.mutation.MaxAmount(); ok {
		_spec.SetField(rechargebonusrule.FieldMaxAmount, field.TypeFloat64, value)
		_node.MaxAmount = &value
	}
	if value, ok := _c.mutation.BonusType(); ok {
		_spec.SetField(rechargebonusrule.FieldBonusType, field.TypeString, value)
		_node.BonusType = value
	}
	if value, ok := _c.mutation.BonusValue(); ok {
		_spec.SetField(rechargebonusrule.FieldBonusValue, field.TypeFloat64, value)
		_node.BonusValue = value
	}
	if value, ok := _c.mutation.StartsAt(); ok {
		_spec.SetField(rechargebonusrule.FieldStartsAt, field.TypeTime, value)
		_node.StartsAt = &value
	}
	if value, ok := _c.mutation.EndsAt(); ok {
		_spec.SetField(rechargebonusrule.FieldEndsAt, field.TypeTime, value)
		_node.EndsAt = &value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(rechargebonusrule.FieldNotes, field.TypeString, value)
		_node.Notes = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(rechargebonusrule.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(rechargebonusrule.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.PaymentOrdersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rechargebonusrule.PaymentOrdersTable,
			Columns: []string{rechargebonusrule.PaymentOrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RechargeBonusRule.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RechargeBonusRuleUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *RechargeBonusRuleCreate) OnConflict(opts ...sql.ConflictOption) *RechargeBonusRuleUpsertOne {
	_c.conflict = opts
	return &RechargeBonusRuleUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RechargeBonusRule.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RechargeBonusRuleCreate) OnConflictColumns(columns ...string) *RechargeBonusRuleUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RechargeBonusRuleUpsertOne{
		create: _c,
	}
}

type (
	// RechargeBonusRuleUpsertOne is the builder for "upsert"-ing
	//  one RechargeBonusRule node.
	RechargeBonusRuleUpsertOne struct {
		create *RechargeBonusRuleCreate
	}

	// RechargeBonusRuleUpsert is the "OnConflict" setter.
	RechargeBonusRuleUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *RechargeBonusRuleUpsert) SetName(v string) *RechargeBonusRuleUpsert {
	u.Set(rechargebonusrule.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *RechargeBonusRuleUpsert) UpdateName() *RechargeBonusRuleUpsert {
	u.SetExcluded(rechargebonusrule.FieldName)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *RechargeBonusRuleUpsert) SetEnabled(v bool) *RechargeBonusRuleUpsert {
	u.Set(rechargebonusrule.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *RechargeBonusRuleUpsert) UpdateEnabled() *RechargeBonusRuleUpsert {
	u.SetExcluded(rechargebonusrule.FieldEnabled)
	return u
}

// SetPriority sets the "priority" field.
func (u *RechargeBonusRuleUpsert) SetPriority(v int) *RechargeBonusRuleUpsert {
	u.Set(rechargebonusrule.FieldPriority, v)
	return u
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *RechargeBonusRuleUpsert) UpdatePriority() *RechargeBonusRuleUpsert {
	u.SetExcluded(rechargebonusrule.FieldPriority)
	return u
}

// AddPriority adds v to the "priority" field.
func (u *RechargeBonusRuleUpsert) AddPriority(v int) *RechargeBonusRuleUpsert {
	u.Add(rechargebonusrule.FieldPriority, v)
	return u
}

// SetMinAmount sets the "min_amount" field.
func (u *RechargeBonusRuleUpsert) SetMinAmount(v float64) *RechargeBonusRuleUpsert {
	u.Set(rechargebonusrule.FieldMinAmount, v)
	return u
}

// UpdateMinAmount sets the "min_amount" field to the value that was provided on create.
func (u *RechargeBonusRuleUpsert) UpdateMinAmount() *RechargeBonusRuleUpsert {
	u.SetExcluded(rechargebonusrule.FieldMinAmount)
	return u
}

// AddMinAmount adds v to the "min_amount" field.
func (u *RechargeBonusRuleUpsert) AddMinAmount(v float64) *RechargeBonusRuleUpsert {
	u.Add(rechargebonusrule.FieldMinAmount, v)
	return u
}

// SetMaxAmount sets the "max_amount" field.
func (u *RechargeBonusRuleUpsert) SetMaxAmount(v float64) *RechargeBonusRuleUpsert {
	u.Set(rechargebonusrule.FieldMaxAmount, v)
	return u
}

// UpdateMaxAmount sets the "max_amount" field to the value that was provided on create.
func (u *RechargeBonusRuleUpsert) UpdateMaxAmount() *RechargeBonusRuleUpsert {
	u.SetExcluded(rechargebonusrule.FieldMaxAmount)
	return u
}

// AddMaxAmount adds v to the "max_amount" field.
func (u *RechargeBonusRuleUpsert) AddMaxAmount(v float64) *RechargeBonusRuleUpsert {
	u.Add(rechargebonusrule.FieldMaxAmount, v)
	return u
}

// ClearMaxAmount clears the value of the "max_amount" field.
func (u *RechargeBonusRuleUpsert) ClearMaxAmount() *RechargeBonusRuleUpsert {
	u.SetNull(rechargebonusrule.FieldMaxAmount)
	return u
}

// SetBonusType sets the "bonus_type" field.
func (u *RechargeBonusRuleUpsert) SetBonusType(v string) *RechargeBonusRuleUpsert {
	u.Set(rechargebonusrule.FieldBonusType, v)
	return u
}

// UpdateBonusType sets the "bonus_type" field to the value that was provided on create.
func (u *RechargeBonusRuleUpsert) UpdateBonusType() *RechargeBonusRuleUpsert {
	u.SetExcluded(rechargebonusrule.FieldBonusType)
	return u
}

// SetBonusValue sets the "bonus_value" field.
func (u *RechargeBonusRuleUpsert) SetBonusValue(v float64) *RechargeBonusRuleUpsert {
	u.Set(rechargebonusrule.FieldBonusValue, v)
	return u
}

// UpdateBonusValue sets the "bonus_value" field to the value that was provided on create.
func (u *RechargeBonusRuleUpsert) UpdateBonusValue() *RechargeBonusRuleUpsert {
	u.SetExcluded(rechargebonusrule.FieldBonusValue)
	return u
}

// AddBonusValue adds v to the "bonus_value" field.
func (u *RechargeBonusRuleUpsert) AddBonusValue(v float64) *RechargeBonusRuleUpsert {
	u.Add(rechargebonusrule.FieldBonusValue, v)
	return u
}

// SetStartsAt sets the "starts_at" field.
func (u *RechargeBonusRuleUpsert) SetStartsAt(v time.Time) *RechargeBonusRuleUpsert {
	u.Set(rechargebonusrule.FieldStartsAt, v)
	return u
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *RechargeBonusRuleUpsert) UpdateStartsAt() *RechargeBonusRuleUpsert {
	u.SetExcluded(rechargebonusrule.FieldStartsAt)
	return u
}

// ClearStartsAt clears the value of the "starts_at" field.
func (u *RechargeBonusRuleUpsert) ClearStartsAt() *RechargeBonusRuleUpsert {
	u.SetNull(rechargebonusrule.FieldStartsAt)
	return u
}

// SetEndsAt sets the "ends_at" field.
func (u *RechargeBonusRuleUpsert) SetEndsAt(v time.Time) *RechargeBonusRuleUpsert {
	u.Set(rechargebonusrule.FieldEndsAt, v)
	return u
}

// UpdateEndsAt sets the "ends_at" field to the value that was provided on create.
func (u *RechargeBonusRuleUpsert) UpdateEndsAt() *RechargeBonusRuleUpsert {
	u.SetExcluded(rechargebonusrule.FieldEndsAt)
	return u
}

// ClearEndsAt clears the value of the "ends_at" field.
func (u *RechargeBonusRuleUpsert) ClearEndsAt() *RechargeBonusRuleUpsert {
	u.SetNull(rechargebonusrule.FieldEndsAt)
	return u
}

// SetNotes sets the "notes" field.
func (u *RechargeBonusRuleUpsert) SetNotes(v string) *RechargeBonusRuleUpsert {
	u.Set(rechargebonusrule.FieldNotes, v)
	return u
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *RechargeBonusRuleUpsert) UpdateNotes() *RechargeBonusRuleUpsert {
	u.SetExcluded(rechargebonusrule.FieldNotes)
	return u
}

// ClearNotes clears the value of the "notes" field.
func (u *RechargeBonusRuleUpsert) ClearNotes() *RechargeBonusRuleUpsert {
	u.SetNull(rechargebonusrule.FieldNotes)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RechargeBonusRuleUpsert) SetUpdatedAt(v time.Time) *RechargeBonusRuleUpsert {
	u.Set(rechargebonusrule.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RechargeBonusRuleUpsert) UpdateUpdatedAt() *RechargeBonusRuleUpsert {
	u.SetExcluded(rechargebonusrule.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.RechargeBonusRule.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RechargeBonusRuleUpsertOne) UpdateNewValues() *RechargeBonusRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(rechargebonusrule.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RechargeBonusRule.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RechargeBonusRuleUpsertOne) Ignore() *RechargeBonusRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RechargeBonusRuleUpsertOne) DoNothing() *RechargeBonusRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RechargeBonusRuleCreate.OnConflict
// documentation for more info.
func (u *RechargeBonusRuleUpsertOne) Update(set func(*RechargeBonusRuleUpsert)) *RechargeBonusRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RechargeBonusRuleUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *RechargeBonusRuleUpsertOne) SetName(v string) *RechargeBonusRuleUpsertOne {
	return u.Update(func(s *RechargeBonusRuleUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *RechargeBonusRuleUpsertOne) UpdateName() *RechargeBonusRuleUpsertOne {
	return u.Update(func(s *RechargeBonusRuleUpsert) {
		s.UpdateName()
	})
}

// SetEnabled sets the "enabled" field.
func (u *RechargeBonusRuleUpsertOne) SetEnabled(v bool) *RechargeBonusRuleUpsertOne {
	return u.Update(func(s *RechargeBonusRuleUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *RechargeBonusRuleUpsertOne) UpdateEnabled() *RechargeBonusRuleUpsertOne {
	return u.Update(func(s *RechargeBonusRuleUpsert) {
		s.UpdateEnabled()
	})
}

// SetPriority sets the "priority" field.
func (u *RechargeBonusRuleUpsertOne) SetPriority(v int) *RechargeBonusRuleUpsertOne {
	return u.Update(func(s *RechargeBonusRuleUpsert) {
		s.SetPriority(v)
	})
}

// AddPriority adds v to the "priority" field.
func (u *RechargeBonusRuleUpsertOne) AddPriority(v int) *RechargeBonusRuleUpsertOne {
	return u.Update(func(s *RechargeBonusRuleUpsert) {
		s.AddPriority(v)
	})
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *RechargeBonusRuleUpsertOne) UpdatePriority() *RechargeBonusRuleUpsertOne {
	return u.Update(func(s *RechargeBonusRuleUpsert) {
		s.UpdatePriority()
	})
}

// SetMinAmount sets the "min_amount" field.
func (u *RechargeBonusRuleUpsertOne) SetMinAmount(v float64) *RechargeBonusRuleUpsertOne {
	return u.Update(func(s *RechargeBonusRuleUpsert) {
		s.SetMinAmount(v)
	})
}

// AddMinAmount adds v to the "min_amount" field.
func (u *RechargeBonusRuleUpsertOne) AddMinAmount(v float64) *RechargeBonusRuleUpsertOne {
	return u.Update(func(s *RechargeBonusRuleUpsert) {
		s.AddMinAmount(v)
	})
}

// UpdateMinAmount sets the "min_amount" field to the value that was provided on create.
func (u *RechargeBonusRuleUpsertOne) UpdateMinAmount() *RechargeBonusRuleUpsertOne {
	return u.Update(func(s *RechargeBonusRuleUpsert) {
		s.UpdateMinAmount()
	})
}

// SetMaxAmount sets the "max_amount" field.
func (u *RechargeBonusRuleUpsertOne) SetMaxAmount(v float64) *RechargeBonusRuleUpsertOne {
	return u.Update(func(s *RechargeBonusRuleUpsert) {
		s.SetMaxAmount(v)
	})
}

// AddMaxAmount adds v to the "max_amount" field.
func (u *RechargeBonusRuleUpsertOne) AddMaxAmount(v float64) *RechargeBonusRuleUpsertOne {
	return u.Update(func(s *RechargeBonusRuleUpsert) {
		s.AddMaxAmount(v)
	})
}

// UpdateMaxAmount sets the "max_amount" field to the value that was provided on create.
func (u *RechargeBonusRuleUpsertOne) UpdateMaxAmount() *RechargeBonusRuleUpsertOne {
	return u.Update(func(s *RechargeBonusRuleUpsert) {
		s.UpdateMaxAmount()
	})
}

// ClearMaxAmount clears the value of the "max_amount" field.
func (u *RechargeBonusRuleUpsertOne) ClearMaxAmount() *RechargeBonusRuleUpsertOne {
	return u.Update(func(s *RechargeBonusRuleUpsert) {
		s.ClearMaxAmount()
	})
}

// SetBonusType sets the "bonus_type" field.
func (u *RechargeBonusRuleUpsertOne) SetBonusType(v string) *RechargeBonusRuleUpsertOne {
	return u.Update(func(s *RechargeBonusRuleUpsert) {
		s.SetBonusType(v)
	})
}

// UpdateBonusType sets the "bonus_type" field to the value that was provided on create.
func (u *RechargeBonusRuleUpsertOne) UpdateBonusType() *RechargeBonusRuleUpsertOne {
	return u.Update(func(s *RechargeBonusRuleUpsert) {
		s.UpdateBonusType()
	})
}

// SetBonusValue sets the "bonus_value" field.
func (u *RechargeBonusRuleUpsertOne) SetBonusValue(v float64) *RechargeBonusRuleUpsertOne {
	return u.Update(func(s *RechargeBonusRuleUpsert) {
		s.SetBonusValue(v)
	})
}

// AddBonusValue adds v to the "bonus_value" field.
func (u *RechargeBonusRuleUpsertOne) AddBonusValue(v float64) *RechargeBonusRuleUpsertOne {
	return u.Update(func(s *RechargeBonusRuleUpsert) {
		s.AddBonusValue(v)
	})
}

// UpdateBonusValue sets the "bonus_value" field to the value that was provided on create.
func (u *RechargeBonusRuleUpsertOne) UpdateBonusValue() *RechargeBonusRuleUpsertOne {
	return u.Update(func(s *RechargeBonusRuleUpsert) {
		s.UpdateBonusValue()
	})
}

// SetStartsAt sets the "starts_at" field.
func (u *RechargeBonusRuleUpsertOne) SetStartsAt(v time.Time) *RechargeBonusRuleUpsertOne {
	return u.Update(func(s *RechargeBonusRuleUpsert) {
		s.SetStartsAt(v)
	})
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *RechargeBonusRuleUpsertOne) UpdateStartsAt() *RechargeBonusRuleUpsertOne {
	return u.Update(func(s *RechargeBonusRuleUpsert) {
		s.UpdateStartsAt()
	})
}

// ClearStartsAt clears the value of the "starts_at" field.
func (u *RechargeBonusRuleUpsertOne) ClearStartsAt() *RechargeBonusRuleUpsertOne {
	return u.Update(func(s *RechargeBonusRuleUpsert) {
		s.ClearStartsAt()
	})
}

// SetEndsAt sets the "ends_at" field.
func (u *RechargeBonusRuleUpsertOne) SetEndsAt(v time.Time) *RechargeBonusRuleUpsertOne {
	return u.Update(func(s *RechargeBonusRuleUpsert) {
		s.SetEndsAt(v)
	})
}

// UpdateEndsAt sets the "ends_at" field to the value that was provided on create.
func (u *RechargeBonusRuleUpsertOne) UpdateEndsAt() *RechargeBonusRuleUpsertOne {
	return u.Update(func(s *RechargeBonusRuleUpsert) {
		s.UpdateEndsAt()
	})
}

// ClearEndsAt clears the value of the "ends_at" field.
func (u *RechargeBonusRuleUpsertOne) ClearEndsAt() *RechargeBonusRuleUpsertOne {
	return u.Update(func(s *RechargeBonusRuleUpsert) {
		s.ClearEndsAt()
	})
}

// SetNotes sets the "notes" field.
func (u *RechargeBonusRuleUpsertOne) SetNotes(v string) *RechargeBonusRuleUpsertOne {
	return u.Update(func(s *RechargeBonusRuleUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *RechargeBonusRuleUpsertOne) UpdateNotes() *RechargeBonusRuleUpsertOne {
	return u.Update(func(s *RechargeBonusRuleUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *RechargeBonusRuleUpsertOne) ClearNotes() *RechargeBonusRuleUpsertOne {
	return u.Update(func(s *RechargeBonusRuleUpsert) {
		s.ClearNotes()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RechargeBonusRuleUpsertOne) SetUpdatedAt(v time.Time) *RechargeBonusRuleUpsertOne {
	return u.Update(func(s *RechargeBonusRuleUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RechargeBonusRuleUpsertOne) UpdateUpdatedAt() *RechargeBonusRuleUpsertOne {
	return u.Update(func(s *RechargeBonusRuleUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *RechargeBonusRuleUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RechargeBonusRuleCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RechargeBonusRuleUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RechargeBonusRuleUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RechargeBonusRuleUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RechargeBonusRuleCreateBulk is the builder for creating many RechargeBonusRule entities in bulk.
type RechargeBonusRuleCreateBulk struct {
	config
	err      error
	builders []*RechargeBonusRuleCreate
	conflict []sql.ConflictOption
}

// Save creates the RechargeBonusRule entities in the database.
func (_c *RechargeBonusRuleCreateBulk) Save(ctx context.Context) ([]*RechargeBonusRule, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RechargeBonusRule, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RechargeBonusRuleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RechargeBonusRuleCreateBulk) SaveX(ctx context.Context) []*RechargeBonusRule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RechargeBonusRuleCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RechargeBonusRuleCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RechargeBonusRule.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RechargeBonusRuleUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *RechargeBonusRuleCreateBulk) OnConflict(opts ...sql.ConflictOption) *RechargeBonusRuleUpsertBulk {
	_c.conflict = opts
	return &RechargeBonusRuleUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RechargeBonusRule.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RechargeBonusRuleCreateBulk) OnConflictColumns(columns ...string) *RechargeBonusRuleUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RechargeBonusRuleUpsertBulk{
		create: _c,
	}
}

// RechargeBonusRuleUpsertBulk is the builder for "upsert"-ing
// a bulk of RechargeBonusRule nodes.
type RechargeBonusRuleUpsertBulk struct {
	create *RechargeBonusRuleCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.RechargeBonusRule.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RechargeBonusRuleUpsertBulk) UpdateNewValues() *RechargeBonusRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(rechargebonusrule.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RechargeBonusRule.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RechargeBonusRuleUpsertBulk) Ignore() *RechargeBonusRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RechargeBonusRuleUpsertBulk) DoNothing() *RechargeBonusRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RechargeBonusRuleCreateBulk.OnConflict
// documentation for more info.
func (u *RechargeBonusRuleUpsertBulk) Update(set func(*RechargeBonusRuleUpsert)) *RechargeBonusRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RechargeBonusRuleUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *RechargeBonusRuleUpsertBulk) SetName(v string) *RechargeBonusRuleUpsertBulk {
	return u.Update(func(s *RechargeBonusRuleUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *RechargeBonusRuleUpsertBulk) UpdateName() *RechargeBonusRuleUpsertBulk {
	return u.Update(func(s *RechargeBonusRuleUpsert) {
		s.UpdateName()
	})
}

// SetEnabled sets the "enabled" field.
func (u *RechargeBonusRuleUpsertBulk) SetEnabled(v bool) *RechargeBonusRuleUpsertBulk {
	return u.Update(func(s *RechargeBonusRuleUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *RechargeBonusRuleUpsertBulk) UpdateEnabled() *RechargeBonusRuleUpsertBulk {
	return u.Update(func(s *RechargeBonusRuleUpsert) {
		s.UpdateEnabled()
	})
}

// SetPriority sets the "priority" field.
func (u *RechargeBonusRuleUpsertBulk) SetPriority(v int) *RechargeBonusRuleUpsertBulk {
	return u.Update(func(s *RechargeBonusRuleUpsert) {
		s.SetPriority(v)
	})
}

// AddPriority adds v to the "priority" field.
func (u *RechargeBonusRuleUpsertBulk) AddPriority(v int) *RechargeBonusRuleUpsertBulk {
	return u.Update(func(s *RechargeBonusRuleUpsert) {
		s.AddPriority(v)
	})
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *RechargeBonusRuleUpsertBulk) UpdatePriority() *RechargeBonusRuleUpsertBulk {
	return u.Update(func(s *RechargeBonusRuleUpsert) {
		s.UpdatePriority()
	})
}

// SetMinAmount sets the "min_amount" field.
func (u *RechargeBonusRuleUpsertBulk) SetMinAmount(v float64) *RechargeBonusRuleUpsertBulk {
	return u.Update(func(s *RechargeBonusRuleUpsert) {
		s.SetMinAmount(v)
	})
}

// AddMinAmount adds v to the "min_amount" field.
func (u *RechargeBonusRuleUpsertBulk) AddMinAmount(v float64) *RechargeBonusRuleUpsertBulk {
	return u.Update(func(s *RechargeBonusRuleUpsert) {
		s.AddMinAmount(v)
	})
}

// UpdateMinAmount sets the "min_amount" field to the value that was provided on create.
func (u *RechargeBonusRuleUpsertBulk) UpdateMinAmount() *RechargeBonusRuleUpsertBulk {
	return u.Update(func(s *RechargeBonusRuleUpsert) {
		s.UpdateMinAmount()
	})
}

// SetMaxAmount sets the "max_amount" field.
func (u *RechargeBonusRuleUpsertBulk) SetMaxAmount(v float64) *RechargeBonusRuleUpsertBulk {
	return u.Update(func(s *RechargeBonusRuleUpsert) {
		s.SetMaxAmount(v)
	})
}

// AddMaxAmount adds v to the "max_amount" field.
func (u *RechargeBonusRuleUpsertBulk) AddMaxAmount(v float64) *RechargeBonusRuleUpsertBulk {
	return u.Update(func(s *RechargeBonusRuleUpsert) {
		s.AddMaxAmount(v)
	})
}

// UpdateMaxAmount sets the "max_amount" field to the value that was provided on create.
func (u *RechargeBonusRuleUpsertBulk) UpdateMaxAmount() *RechargeBonusRuleUpsertBulk {
	return u.Update(func(s *RechargeBonusRuleUpsert) {
		s.UpdateMaxAmount()
	})
}

// ClearMaxAmount clears the value of the "max_amount" field.
func (u *RechargeBonusRuleUpsertBulk) ClearMaxAmount() *RechargeBonusRuleUpsertBulk {
	return u.Update(func(s *RechargeBonusRuleUpsert) {
		s.ClearMaxAmount()
	})
}

// SetBonusType sets the "bonus_type" field.
func (u *RechargeBonusRuleUpsertBulk) SetBonusType(v string) *RechargeBonusRuleUpsertBulk {
	return u.Update(func(s *RechargeBonusRuleUpsert) {
		s.SetBonusType(v)
	})
}

// UpdateBonusType sets the "bonus_type" field to the value that was provided on create.
func (u *RechargeBonusRuleUpsertBulk) UpdateBonusType() *RechargeBonusRuleUpsertBulk {
	return u.Update(func(s *RechargeBonusRuleUpsert) {
		s.UpdateBonusType()
	})
}

// SetBonusValue sets the "bonus_value" field.
func (u *RechargeBonusRuleUpsertBulk) SetBonusValue(v float64) *RechargeBonusRuleUpsertBulk {
	return u.Update(func(s *RechargeBonusRuleUpsert) {
		s.SetBonusValue(v)
	})
}

// AddBonusValue adds v to the "bonus_value" field.
func (u *RechargeBonusRuleUpsertBulk) AddBonusValue(v float64) *RechargeBonusRuleUpsertBulk {
	return u.Update(func(s *RechargeBonusRuleUpsert) {
		s.AddBonusValue(v)
	})
}

// UpdateBonusValue sets the "bonus_value" field to the value that was provided on create.
func (u *RechargeBonusRuleUpsertBulk) UpdateBonusValue() *RechargeBonusRuleUpsertBulk {
	return u.Update(func(s *RechargeBonusRuleUpsert) {
		s.UpdateBonusValue()
	})
}

// SetStartsAt sets the "starts_at" field.
func (u *RechargeBonusRuleUpsertBulk) SetStartsAt(v time.Time) *RechargeBonusRuleUpsertBulk {
	return u.Update(func(s *RechargeBonusRuleUpsert) {
		s.SetStartsAt(v)
	})
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *RechargeBonusRuleUpsertBulk) UpdateStartsAt() *RechargeBonusRuleUpsertBulk {
	return u.Update(func(s *RechargeBonusRuleUpsert) {
		s.UpdateStartsAt()
	})
}

// ClearStartsAt clears the value of the "starts_at" field.
func (u *RechargeBonusRuleUpsertBulk) ClearStartsAt() *RechargeBonusRuleUpsertBulk {
	return u.Update(func(s *RechargeBonusRuleUpsert) {
		s.ClearStartsAt()
	})
}

// SetEndsAt sets the "ends_at" field.
func (u *RechargeBonusRuleUpsertBulk) SetEndsAt(v time.Time) *RechargeBonusRuleUpsertBulk {
	return u.Update(func(s *RechargeBonusRuleUpsert) {
		s.SetEndsAt(v)
	})
}

// UpdateEndsAt sets the "ends_at" field to the value that was provided on create.
func (u *RechargeBonusRuleUpsertBulk) UpdateEndsAt() *RechargeBonusRuleUpsertBulk {
	return u.Update(func(s *RechargeBonusRuleUpsert) {
		s.UpdateEndsAt()
	})
}

// ClearEndsAt clears the value of the "ends_at" field.
func (u *RechargeBonusRuleUpsertBulk) ClearEndsAt() *RechargeBonusRuleUpsertBulk {
	return u.Update(func(s *RechargeBonusRuleUpsert) {
		s.ClearEndsAt()
	})
}

// SetNotes sets the "notes" field.
func (u *RechargeBonusRuleUpsertBulk) SetNotes(v string) *RechargeBonusRuleUpsertBulk {
	return u.Update(func(s *RechargeBonusRuleUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *RechargeBonusRuleUpsertBulk) UpdateNotes() *RechargeBonusRuleUpsertBulk {
	return u.Update(func(s *RechargeBonusRuleUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *RechargeBonusRuleUpsertBulk) ClearNotes() *RechargeBonusRuleUpsertBulk {
	return u.Update(func(s *RechargeBonusRuleUpsert) {
		s.ClearNotes()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RechargeBonusRuleUpsertBulk) SetUpdatedAt(v time.Time) *RechargeBonusRuleUpsertBulk {
	return u.Update(func(s *RechargeBonusRuleUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RechargeBonusRuleUpsertBulk) UpdateUpdatedAt() *RechargeBonusRuleUpsertBulk {
	return u.Update(func(s *RechargeBonusRuleUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *RechargeBonusRuleUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RechargeBonusRuleCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RechargeBonusRuleCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RechargeBonusRuleUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
