// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/paymentorder"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/rechargebonusrule"
)

// RechargeBonusRuleQuery is the builder for querying RechargeBonusRule entities.
type RechargeBonusRuleQuery struct {
	config
	ctx               *QueryContext
	order             []rechargebonusrule.OrderOption
	inters            []Interceptor
	predicates        []predicate.RechargeBonusRule
	withPaymentOrders *PaymentOrderQuery
	modifiers         []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the RechargeBonusRuleQuery builder.
func (_q *RechargeBonusRuleQuery) Where(ps ...predicate.RechargeBonusRule) *RechargeBonusRuleQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *RechargeBonusRuleQuery) Limit(limit int) *RechargeBonusRuleQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *RechargeBonusRuleQuery) Offset(offset int) *RechargeBonusRuleQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *RechargeBonusRuleQuery) Unique(unique bool) *RechargeBonusRuleQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *RechargeBonusRuleQuery) Order(o ...rechargebonusrule.OrderOption) *RechargeBonusRuleQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryPaymentOrders chains the current query on the "payment_orders" edge.
func (_q *RechargeBonusRuleQuery) QueryPaymentOrders() *PaymentOrderQuery {
	query := (&PaymentOrderClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(rechargebonusrule.Table, rechargebonusrule.FieldID, selector),
			sqlgraph.To(paymentorder.Table, paymentorder.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, rechargebonusrule.PaymentOrdersTable, rechargebonusrule.PaymentOrdersColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first RechargeBonusRule entity from the query.
// Returns a *NotFoundError when no RechargeBonusRule was found.
func (_q *RechargeBonusRuleQuery) First(ctx context.Context) (*RechargeBonusRule, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{rechargebonusrule.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *RechargeBonusRuleQuery) FirstX(ctx context.Context) *RechargeBonusRule {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first RechargeBonusRule ID from the query.
// Returns a *NotFoundError when no RechargeBonusRule ID was found.
func (_q *RechargeBonusRuleQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{rechargebonusrule.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *RechargeBonusRuleQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single RechargeBonusRule entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one RechargeBonusRule entity is found.
// Returns a *NotFoundError when no RechargeBonusRule entities are found.
func (_q *RechargeBonusRuleQuery) Only(ctx context.Context) (*RechargeBonusRule, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{rechargebonusrule.Label}
	default:
		return nil, &NotSingularError{rechargebonusrule.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *RechargeBonusRuleQuery) OnlyX(ctx context.Context) *RechargeBonusRule {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only RechargeBonusRule ID in the query.
// Returns a *NotSingularError when more than one RechargeBonusRule ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *RechargeBonusRuleQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{rechargebonusrule.Label}
	default:
		err = &NotSingularError{rechargebonusrule.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *RechargeBonusRuleQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of RechargeBonusRules.
func (_q *RechargeBonusRuleQuery) All(ctx context.Context) ([]*RechargeBonusRule, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*RechargeBonusRule, *RechargeBonusRuleQuery]()
	return withInterceptors[[]*RechargeBonusRule](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *RechargeBonusRuleQuery) AllX(ctx context.Context) []*RechargeBonusRule {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of RechargeBonusRule IDs.
func (_q *RechargeBonusRuleQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(rechargebonusrule.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *RechargeBonusRuleQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *RechargeBonusRuleQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*RechargeBonusRuleQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *RechargeBonusRuleQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *RechargeBonusRuleQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *RechargeBonusRuleQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the RechargeBonusRuleQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *RechargeBonusRuleQuery) Clone() *RechargeBonusRuleQuery {
	if _q == nil {
		return nil
	}
	return &RechargeBonusRuleQuery{
		config:            _q.config,
		ctx:               _q.ctx.Clone(),
		order:             append([]rechargebonusrule.OrderOption{}, _q.order...),
		inters:            append([]Interceptor{}, _q.inters...),
		predicates:        append([]predicate.RechargeBonusRule{}, _q.predicates...),
		withPaymentOrders: _q.withPaymentOrders.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithPaymentOrders tells the query-builder to eager-load the nodes that are connected to
// the "payment_orders" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *RechargeBonusRuleQuery) WithPaymentOrders(opts ...func(*PaymentOrderQuery)) *RechargeBonusRuleQuery {
	query := (&PaymentOrderClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withPaymentOrders = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.RechargeBonusRule.Query().
//		GroupBy(rechargebonusrule.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *RechargeBonusRuleQuery) GroupBy(field string, fields ...string) *RechargeBonusRuleGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &RechargeBonusRuleGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = rechargebonusrule.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.RechargeBonusRule.Query().
//		Select(rechargebonusrule.FieldName).
//		Scan(ctx, &v)
func (_q *RechargeBonusRuleQuery) Select(fields ...string) *RechargeBonusRuleSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &RechargeBonusRuleSelect{RechargeBonusRuleQuery: _q}
	sbuild.label = rechargebonusrule.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a RechargeBonusRuleSelect configured with the given aggregations.
func (_q *RechargeBonusRuleQuery) Aggregate(fns ...AggregateFunc) *RechargeBonusRuleSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *RechargeBonusRuleQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !rechargebonusrule.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *RechargeBonusRuleQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*RechargeBonusRule, error) {
	var (
		nodes       = []*RechargeBonusRule{}
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withPaymentOrders != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*RechargeBonusRule).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &RechargeBonusRule{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withPaymentOrders; query != nil {
		if err := _q.loadPaymentOrders(ctx, query, nodes,
			func(n *RechargeBonusRule) { n.Edges.PaymentOrders = []*PaymentOrder{} },
			func(n *RechargeBonusRule, e *PaymentOrder) { n.Edges.PaymentOrders = append(n.Edges.PaymentOrders, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *RechargeBonusRuleQuery) loadPaymentOrders(ctx context.Context, query *PaymentOrderQuery, nodes []*RechargeBonusRule, init func(*RechargeBonusRule), assign func(*RechargeBonusRule, *PaymentOrder)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*RechargeBonusRule)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(paymentorder.FieldRechargeBonusRuleID)
	}
	query.Where(predicate.PaymentOrder(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(rechargebonusrule.PaymentOrdersColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.RechargeBonusRuleID
		if fk == nil {
			return fmt.Errorf(`foreign-key "recharge_bonus_rule_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "recharge_bonus_rule_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *RechargeBonusRuleQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *RechargeBonusRuleQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(rechargebonusrule.Table, rechargebonusrule.Columns, sqlgraph.NewFieldSpec(rechargebonusrule.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, rechargebonusrule.FieldID)
		for i := range fields {
			if fields[i] != rechargebonusrule.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *RechargeBonusRuleQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(rechargebonusrule.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = rechargebonusrule.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *RechargeBonusRuleQuery) ForUpdate(opts ...sql.LockOption) *RechargeBonusRuleQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *RechargeBonusRuleQuery) ForShare(opts ...sql.LockOption) *RechargeBonusRuleQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// RechargeBonusRuleGroupBy is the group-by builder for RechargeBonusRule entities.
type RechargeBonusRuleGroupBy struct {
	selector
	build *RechargeBonusRuleQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *RechargeBonusRuleGroupBy) Aggregate(fns ...AggregateFunc) *RechargeBonusRuleGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *RechargeBonusRuleGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RechargeBonusRuleQuery, *RechargeBonusRuleGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *RechargeBonusRuleGroupBy) sqlScan(ctx context.Context, root *RechargeBonusRuleQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// RechargeBonusRuleSelect is the builder for selecting fields of RechargeBonusRule entities.
type RechargeBonusRuleSelect struct {
	*RechargeBonusRuleQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *RechargeBonusRuleSelect) Aggregate(fns ...AggregateFunc) *RechargeBonusRuleSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *RechargeBonusRuleSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RechargeBonusRuleQuery, *RechargeBonusRuleSelect](ctx, _s.RechargeBonusRuleQuery, _s, _s.inters, v)
}

func (_s *RechargeBonusRuleSelect) sqlScan(ctx context.Context, root *RechargeBonusRuleQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
