// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionplan"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionsettlementorder"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/usersubscription"
)

// SubscriptionSettlementOrder is the model entity for the SubscriptionSettlementOrder schema.
type SubscriptionSettlementOrder struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// PrevSettlementID holds the value of the "prev_settlement_id" field.
	PrevSettlementID *int64 `json:"prev_settlement_id,omitempty"`
	// ActionType holds the value of the "action_type" field.
	ActionType string `json:"action_type,omitempty"`
	// ActionSource holds the value of the "action_source" field.
	ActionSource string `json:"action_source,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// TriggerRefType holds the value of the "trigger_ref_type" field.
	TriggerRefType string `json:"trigger_ref_type,omitempty"`
	// TriggerRefID holds the value of the "trigger_ref_id" field.
	TriggerRefID *int64 `json:"trigger_ref_id,omitempty"`
	// OperatorUserID holds the value of the "operator_user_id" field.
	OperatorUserID int64 `json:"operator_user_id,omitempty"`
	// ActionNote holds the value of the "action_note" field.
	ActionNote *string `json:"action_note,omitempty"`
	// CarryInResidualValue holds the value of the "carry_in_residual_value" field.
	CarryInResidualValue float64 `json:"carry_in_residual_value,omitempty"`
	// ActionDeltaValue holds the value of the "action_delta_value" field.
	ActionDeltaValue float64 `json:"action_delta_value,omitempty"`
	// AfterSettlementValue holds the value of the "after_settlement_value" field.
	AfterSettlementValue float64 `json:"after_settlement_value,omitempty"`
	// RefundResidualValue holds the value of the "refund_residual_value" field.
	RefundResidualValue *float64 `json:"refund_residual_value,omitempty"`
	// WriteoffValue holds the value of the "writeoff_value" field.
	WriteoffValue float64 `json:"writeoff_value,omitempty"`
	// AfterUserSubscriptionID holds the value of the "after_user_subscription_id" field.
	AfterUserSubscriptionID *int64 `json:"after_user_subscription_id,omitempty"`
	// AfterPlanID holds the value of the "after_plan_id" field.
	AfterPlanID *int64 `json:"after_plan_id,omitempty"`
	// AfterPlanNameSnapshot holds the value of the "after_plan_name_snapshot" field.
	AfterPlanNameSnapshot *string `json:"after_plan_name_snapshot,omitempty"`
	// AfterPlanPriceSnapshot holds the value of the "after_plan_price_snapshot" field.
	AfterPlanPriceSnapshot *float64 `json:"after_plan_price_snapshot,omitempty"`
	// AfterValidityDaysSnapshot holds the value of the "after_validity_days_snapshot" field.
	AfterValidityDaysSnapshot *int `json:"after_validity_days_snapshot,omitempty"`
	// AfterValidityUnitSnapshot holds the value of the "after_validity_unit_snapshot" field.
	AfterValidityUnitSnapshot *string `json:"after_validity_unit_snapshot,omitempty"`
	// AfterStartsAt holds the value of the "after_starts_at" field.
	AfterStartsAt *time.Time `json:"after_starts_at,omitempty"`
	// AfterExpiresAt holds the value of the "after_expires_at" field.
	AfterExpiresAt *time.Time `json:"after_expires_at,omitempty"`
	// AfterDailyQuotaKnivesSnapshot holds the value of the "after_daily_quota_knives_snapshot" field.
	AfterDailyQuotaKnivesSnapshot *float64 `json:"after_daily_quota_knives_snapshot,omitempty"`
	// AfterWeeklyQuotaKnivesSnapshot holds the value of the "after_weekly_quota_knives_snapshot" field.
	AfterWeeklyQuotaKnivesSnapshot *float64 `json:"after_weekly_quota_knives_snapshot,omitempty"`
	// AfterMonthlyQuotaKnivesSnapshot holds the value of the "after_monthly_quota_knives_snapshot" field.
	AfterMonthlyQuotaKnivesSnapshot *float64 `json:"after_monthly_quota_knives_snapshot,omitempty"`
	// AfterSubscriptionStatus holds the value of the "after_subscription_status" field.
	AfterSubscriptionStatus string `json:"after_subscription_status,omitempty"`
	// EffectiveAt holds the value of the "effective_at" field.
	EffectiveAt time.Time `json:"effective_at,omitempty"`
	// ClosedAt holds the value of the "closed_at" field.
	ClosedAt *time.Time `json:"closed_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SubscriptionSettlementOrderQuery when eager-loading is set.
	Edges        SubscriptionSettlementOrderEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SubscriptionSettlementOrderEdges holds the relations/edges for other nodes in the graph.
type SubscriptionSettlementOrderEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Operator holds the value of the operator edge.
	Operator *User `json:"operator,omitempty"`
	// Next holds the value of the next edge.
	Next *SubscriptionSettlementOrder `json:"next,omitempty"`
	// Previous holds the value of the previous edge.
	Previous *SubscriptionSettlementOrder `json:"previous,omitempty"`
	// AfterUserSubscription holds the value of the after_user_subscription edge.
	AfterUserSubscription *UserSubscription `json:"after_user_subscription,omitempty"`
	// AfterPlan holds the value of the after_plan edge.
	AfterPlan *SubscriptionPlan `json:"after_plan,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [6]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SubscriptionSettlementOrderEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// OperatorOrErr returns the Operator value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SubscriptionSettlementOrderEdges) OperatorOrErr() (*User, error) {
	if e.Operator != nil {
		return e.Operator, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "operator"}
}

// NextOrErr returns the Next value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SubscriptionSettlementOrderEdges) NextOrErr() (*SubscriptionSettlementOrder, error) {
	if e.Next != nil {
		return e.Next, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: subscriptionsettlementorder.Label}
	}
	return nil, &NotLoadedError{edge: "next"}
}

// PreviousOrErr returns the Previous value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SubscriptionSettlementOrderEdges) PreviousOrErr() (*SubscriptionSettlementOrder, error) {
	if e.Previous != nil {
		return e.Previous, nil
	} else if e.loadedTypes[3] {
		return nil, &NotFoundError{label: subscriptionsettlementorder.Label}
	}
	return nil, &NotLoadedError{edge: "previous"}
}

// AfterUserSubscriptionOrErr returns the AfterUserSubscription value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SubscriptionSettlementOrderEdges) AfterUserSubscriptionOrErr() (*UserSubscription, error) {
	if e.AfterUserSubscription != nil {
		return e.AfterUserSubscription, nil
	} else if e.loadedTypes[4] {
		return nil, &NotFoundError{label: usersubscription.Label}
	}
	return nil, &NotLoadedError{edge: "after_user_subscription"}
}

// AfterPlanOrErr returns the AfterPlan value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SubscriptionSettlementOrderEdges) AfterPlanOrErr() (*SubscriptionPlan, error) {
	if e.AfterPlan != nil {
		return e.AfterPlan, nil
	} else if e.loadedTypes[5] {
		return nil, &NotFoundError{label: subscriptionplan.Label}
	}
	return nil, &NotLoadedError{edge: "after_plan"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SubscriptionSettlementOrder) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case subscriptionsettlementorder.FieldCarryInResidualValue, subscriptionsettlementorder.FieldActionDeltaValue, subscriptionsettlementorder.FieldAfterSettlementValue, subscriptionsettlementorder.FieldRefundResidualValue, subscriptionsettlementorder.FieldWriteoffValue, subscriptionsettlementorder.FieldAfterPlanPriceSnapshot, subscriptionsettlementorder.FieldAfterDailyQuotaKnivesSnapshot, subscriptionsettlementorder.FieldAfterWeeklyQuotaKnivesSnapshot, subscriptionsettlementorder.FieldAfterMonthlyQuotaKnivesSnapshot:
			values[i] = new(sql.NullFloat64)
		case subscriptionsettlementorder.FieldID, subscriptionsettlementorder.FieldUserID, subscriptionsettlementorder.FieldPrevSettlementID, subscriptionsettlementorder.FieldTriggerRefID, subscriptionsettlementorder.FieldOperatorUserID, subscriptionsettlementorder.FieldAfterUserSubscriptionID, subscriptionsettlementorder.FieldAfterPlanID, subscriptionsettlementorder.FieldAfterValidityDaysSnapshot:
			values[i] = new(sql.NullInt64)
		case subscriptionsettlementorder.FieldActionType, subscriptionsettlementorder.FieldActionSource, subscriptionsettlementorder.FieldStatus, subscriptionsettlementorder.FieldTriggerRefType, subscriptionsettlementorder.FieldActionNote, subscriptionsettlementorder.FieldAfterPlanNameSnapshot, subscriptionsettlementorder.FieldAfterValidityUnitSnapshot, subscriptionsettlementorder.FieldAfterSubscriptionStatus:
			values[i] = new(sql.NullString)
		case subscriptionsettlementorder.FieldAfterStartsAt, subscriptionsettlementorder.FieldAfterExpiresAt, subscriptionsettlementorder.FieldEffectiveAt, subscriptionsettlementorder.FieldClosedAt, subscriptionsettlementorder.FieldCreatedAt, subscriptionsettlementorder.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SubscriptionSettlementOrder fields.
func (_m *SubscriptionSettlementOrder) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case subscriptionsettlementorder.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case subscriptionsettlementorder.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case subscriptionsettlementorder.FieldPrevSettlementID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field prev_settlement_id", values[i])
			} else if value.Valid {
				_m.PrevSettlementID = new(int64)
				*_m.PrevSettlementID = value.Int64
			}
		case subscriptionsettlementorder.FieldActionType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field action_type", values[i])
			} else if value.Valid {
				_m.ActionType = value.String
			}
		case subscriptionsettlementorder.FieldActionSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field action_source", values[i])
			} else if value.Valid {
				_m.ActionSource = value.String
			}
		case subscriptionsettlementorder.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case subscriptionsettlementorder.FieldTriggerRefType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field trigger_ref_type", values[i])
			} else if value.Valid {
				_m.TriggerRefType = value.String
			}
		case subscriptionsettlementorder.FieldTriggerRefID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field trigger_ref_id", values[i])
			} else if value.Valid {
				_m.TriggerRefID = new(int64)
				*_m.TriggerRefID = value.Int64
			}
		case subscriptionsettlementorder.FieldOperatorUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field operator_user_id", values[i])
			} else if value.Valid {
				_m.OperatorUserID = value.Int64
			}
		case subscriptionsettlementorder.FieldActionNote:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field action_note", values[i])
			} else if value.Valid {
				_m.ActionNote = new(string)
				*_m.ActionNote = value.String
			}
		case subscriptionsettlementorder.FieldCarryInResidualValue:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field carry_in_residual_value", values[i])
			} else if value.Valid {
				_m.CarryInResidualValue = value.Float64
			}
		case subscriptionsettlementorder.FieldActionDeltaValue:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field action_delta_value", values[i])
			} else if value.Valid {
				_m.ActionDeltaValue = value.Float64
			}
		case subscriptionsettlementorder.FieldAfterSettlementValue:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field after_settlement_value", values[i])
			} else if value.Valid {
				_m.AfterSettlementValue = value.Float64
			}
		case subscriptionsettlementorder.FieldRefundResidualValue:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field refund_residual_value", values[i])
			} else if value.Valid {
				_m.RefundResidualValue = new(float64)
				*_m.RefundResidualValue = value.Float64
			}
		case subscriptionsettlementorder.FieldWriteoffValue:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field writeoff_value", values[i])
			} else if value.Valid {
				_m.WriteoffValue = value.Float64
			}
		case subscriptionsettlementorder.FieldAfterUserSubscriptionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field after_user_subscription_id", values[i])
			} else if value.Valid {
				_m.AfterUserSubscriptionID = new(int64)
				*_m.AfterUserSubscriptionID = value.Int64
			}
		case subscriptionsettlementorder.FieldAfterPlanID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field after_plan_id", values[i])
			} else if value.Valid {
				_m.AfterPlanID = new(int64)
				*_m.AfterPlanID = value.Int64
			}
		case subscriptionsettlementorder.FieldAfterPlanNameSnapshot:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field after_plan_name_snapshot", values[i])
			} else if value.Valid {
				_m.AfterPlanNameSnapshot = new(string)
				*_m.AfterPlanNameSnapshot = value.String
			}
		case subscriptionsettlementorder.FieldAfterPlanPriceSnapshot:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field after_plan_price_snapshot", values[i])
			} else if value.Valid {
				_m.AfterPlanPriceSnapshot = new(float64)
				*_m.AfterPlanPriceSnapshot = value.Float64
			}
		case subscriptionsettlementorder.FieldAfterValidityDaysSnapshot:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field after_validity_days_snapshot", values[i])
			} else if value.Valid {
				_m.AfterValidityDaysSnapshot = new(int)
				*_m.AfterValidityDaysSnapshot = int(value.Int64)
			}
		case subscriptionsettlementorder.FieldAfterValidityUnitSnapshot:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field after_validity_unit_snapshot", values[i])
			} else if value.Valid {
				_m.AfterValidityUnitSnapshot = new(string)
				*_m.AfterValidityUnitSnapshot = value.String
			}
		case subscriptionsettlementorder.FieldAfterStartsAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field after_starts_at", values[i])
			} else if value.Valid {
				_m.AfterStartsAt = new(time.Time)
				*_m.AfterStartsAt = value.Time
			}
		case subscriptionsettlementorder.FieldAfterExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field after_expires_at", values[i])
			} else if value.Valid {
				_m.AfterExpiresAt = new(time.Time)
				*_m.AfterExpiresAt = value.Time
			}
		case subscriptionsettlementorder.FieldAfterDailyQuotaKnivesSnapshot:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field after_daily_quota_knives_snapshot", values[i])
			} else if value.Valid {
				_m.AfterDailyQuotaKnivesSnapshot = new(float64)
				*_m.AfterDailyQuotaKnivesSnapshot = value.Float64
			}
		case subscriptionsettlementorder.FieldAfterWeeklyQuotaKnivesSnapshot:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field after_weekly_quota_knives_snapshot", values[i])
			} else if value.Valid {
				_m.AfterWeeklyQuotaKnivesSnapshot = new(float64)
				*_m.AfterWeeklyQuotaKnivesSnapshot = value.Float64
			}
		case subscriptionsettlementorder.FieldAfterMonthlyQuotaKnivesSnapshot:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field after_monthly_quota_knives_snapshot", values[i])
			} else if value.Valid {
				_m.AfterMonthlyQuotaKnivesSnapshot = new(float64)
				*_m.AfterMonthlyQuotaKnivesSnapshot = value.Float64
			}
		case subscriptionsettlementorder.FieldAfterSubscriptionStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field after_subscription_status", values[i])
			} else if value.Valid {
				_m.AfterSubscriptionStatus = value.String
			}
		case subscriptionsettlementorder.FieldEffectiveAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field effective_at", values[i])
			} else if value.Valid {
				_m.EffectiveAt = value.Time
			}
		case subscriptionsettlementorder.FieldClosedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field closed_at", values[i])
			} else if value.Valid {
				_m.ClosedAt = new(time.Time)
				*_m.ClosedAt = value.Time
			}
		case subscriptionsettlementorder.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case subscriptionsettlementorder.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SubscriptionSettlementOrder.
// This includes values selected through modifiers, order, etc.
func (_m *SubscriptionSettlementOrder) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the SubscriptionSettlementOrder entity.
func (_m *SubscriptionSettlementOrder) QueryUser() *UserQuery {
	return NewSubscriptionSettlementOrderClient(_m.config).QueryUser(_m)
}

// QueryOperator queries the "operator" edge of the SubscriptionSettlementOrder entity.
func (_m *SubscriptionSettlementOrder) QueryOperator() *UserQuery {
	return NewSubscriptionSettlementOrderClient(_m.config).QueryOperator(_m)
}

// QueryNext queries the "next" edge of the SubscriptionSettlementOrder entity.
func (_m *SubscriptionSettlementOrder) QueryNext() *SubscriptionSettlementOrderQuery {
	return NewSubscriptionSettlementOrderClient(_m.config).QueryNext(_m)
}

// QueryPrevious queries the "previous" edge of the SubscriptionSettlementOrder entity.
func (_m *SubscriptionSettlementOrder) QueryPrevious() *SubscriptionSettlementOrderQuery {
	return NewSubscriptionSettlementOrderClient(_m.config).QueryPrevious(_m)
}

// QueryAfterUserSubscription queries the "after_user_subscription" edge of the SubscriptionSettlementOrder entity.
func (_m *SubscriptionSettlementOrder) QueryAfterUserSubscription() *UserSubscriptionQuery {
	return NewSubscriptionSettlementOrderClient(_m.config).QueryAfterUserSubscription(_m)
}

// QueryAfterPlan queries the "after_plan" edge of the SubscriptionSettlementOrder entity.
func (_m *SubscriptionSettlementOrder) QueryAfterPlan() *SubscriptionPlanQuery {
	return NewSubscriptionSettlementOrderClient(_m.config).QueryAfterPlan(_m)
}

// Update returns a builder for updating this SubscriptionSettlementOrder.
// Note that you need to call SubscriptionSettlementOrder.Unwrap() before calling this method if this SubscriptionSettlementOrder
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SubscriptionSettlementOrder) Update() *SubscriptionSettlementOrderUpdateOne {
	return NewSubscriptionSettlementOrderClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SubscriptionSettlementOrder entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SubscriptionSettlementOrder) Unwrap() *SubscriptionSettlementOrder {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SubscriptionSettlementOrder is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SubscriptionSettlementOrder) String() string {
	var builder strings.Builder
	builder.WriteString("SubscriptionSettlementOrder(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	if v := _m.PrevSettlementID; v != nil {
		builder.WriteString("prev_settlement_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("action_type=")
	builder.WriteString(_m.ActionType)
	builder.WriteString(", ")
	builder.WriteString("action_source=")
	builder.WriteString(_m.ActionSource)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("trigger_ref_type=")
	builder.WriteString(_m.TriggerRefType)
	builder.WriteString(", ")
	if v := _m.TriggerRefID; v != nil {
		builder.WriteString("trigger_ref_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("operator_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.OperatorUserID))
	builder.WriteString(", ")
	if v := _m.ActionNote; v != nil {
		builder.WriteString("action_note=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("carry_in_residual_value=")
	builder.WriteString(fmt.Sprintf("%v", _m.CarryInResidualValue))
	builder.WriteString(", ")
	builder.WriteString("action_delta_value=")
	builder.WriteString(fmt.Sprintf("%v", _m.ActionDeltaValue))
	builder.WriteString(", ")
	builder.WriteString("after_settlement_value=")
	builder.WriteString(fmt.Sprintf("%v", _m.AfterSettlementValue))
	builder.WriteString(", ")
	if v := _m.RefundResidualValue; v != nil {
		builder.WriteString("refund_residual_value=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("writeoff_value=")
	builder.WriteString(fmt.Sprintf("%v", _m.WriteoffValue))
	builder.WriteString(", ")
	if v := _m.AfterUserSubscriptionID; v != nil {
		builder.WriteString("after_user_subscription_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.AfterPlanID; v != nil {
		builder.WriteString("after_plan_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.AfterPlanNameSnapshot; v != nil {
		builder.WriteString("after_plan_name_snapshot=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.AfterPlanPriceSnapshot; v != nil {
		builder.WriteString("after_plan_price_snapshot=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.AfterValidityDaysSnapshot; v != nil {
		builder.WriteString("after_validity_days_snapshot=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.AfterValidityUnitSnapshot; v != nil {
		builder.WriteString("after_validity_unit_snapshot=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.AfterStartsAt; v != nil {
		builder.WriteString("after_starts_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.AfterExpiresAt; v != nil {
		builder.WriteString("after_expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.AfterDailyQuotaKnivesSnapshot; v != nil {
		builder.WriteString("after_daily_quota_knives_snapshot=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.AfterWeeklyQuotaKnivesSnapshot; v != nil {
		builder.WriteString("after_weekly_quota_knives_snapshot=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.AfterMonthlyQuotaKnivesSnapshot; v != nil {
		builder.WriteString("after_monthly_quota_knives_snapshot=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("after_subscription_status=")
	builder.WriteString(_m.AfterSubscriptionStatus)
	builder.WriteString(", ")
	builder.WriteString("effective_at=")
	builder.WriteString(_m.EffectiveAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.ClosedAt; v != nil {
		builder.WriteString("closed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SubscriptionSettlementOrders is a parsable slice of SubscriptionSettlementOrder.
type SubscriptionSettlementOrders []*SubscriptionSettlementOrder
