// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionrefundrequest"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionsettlementorder"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/usersubscription"
)

// SubscriptionRefundRequest is the model entity for the SubscriptionRefundRequest schema.
type SubscriptionRefundRequest struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// SubscriptionID holds the value of the "subscription_id" field.
	SubscriptionID int64 `json:"subscription_id,omitempty"`
	// SettlementID holds the value of the "settlement_id" field.
	SettlementID int64 `json:"settlement_id,omitempty"`
	// ExpectedSettlementID holds the value of the "expected_settlement_id" field.
	ExpectedSettlementID int64 `json:"expected_settlement_id,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// RefundMode holds the value of the "refund_mode" field.
	RefundMode string `json:"refund_mode,omitempty"`
	// Currency holds the value of the "currency" field.
	Currency *string `json:"currency,omitempty"`
	// Reason holds the value of the "reason" field.
	Reason *string `json:"reason,omitempty"`
	// RefundResidualValue holds the value of the "refund_residual_value" field.
	RefundResidualValue float64 `json:"refund_residual_value,omitempty"`
	// GatewayRefundableTotal holds the value of the "gateway_refundable_total" field.
	GatewayRefundableTotal float64 `json:"gateway_refundable_total,omitempty"`
	// ManualTransferAmount holds the value of the "manual_transfer_amount" field.
	ManualTransferAmount float64 `json:"manual_transfer_amount,omitempty"`
	// PreviewTokenHash holds the value of the "preview_token_hash" field.
	PreviewTokenHash string `json:"preview_token_hash,omitempty"`
	// PreviewFingerprint holds the value of the "preview_fingerprint" field.
	PreviewFingerprint *string `json:"preview_fingerprint,omitempty"`
	// PreviewIssuedAt holds the value of the "preview_issued_at" field.
	PreviewIssuedAt time.Time `json:"preview_issued_at,omitempty"`
	// PreviewExpiresAt holds the value of the "preview_expires_at" field.
	PreviewExpiresAt time.Time `json:"preview_expires_at,omitempty"`
	// SubmittedAt holds the value of the "submitted_at" field.
	SubmittedAt *time.Time `json:"submitted_at,omitempty"`
	// FrozenAt holds the value of the "frozen_at" field.
	FrozenAt *time.Time `json:"frozen_at,omitempty"`
	// CompletedAt holds the value of the "completed_at" field.
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	// CancelledAt holds the value of the "cancelled_at" field.
	CancelledAt *time.Time `json:"cancelled_at,omitempty"`
	// OriginalSubscriptionStatus holds the value of the "original_subscription_status" field.
	OriginalSubscriptionStatus *string `json:"original_subscription_status,omitempty"`
	// OriginalSubscriptionExpiresAt holds the value of the "original_subscription_expires_at" field.
	OriginalSubscriptionExpiresAt *time.Time `json:"original_subscription_expires_at,omitempty"`
	// ManualReceiverType holds the value of the "manual_receiver_type" field.
	ManualReceiverType *string `json:"manual_receiver_type,omitempty"`
	// ManualReceiverName holds the value of the "manual_receiver_name" field.
	ManualReceiverName *string `json:"manual_receiver_name,omitempty"`
	// ManualReceiverAccount holds the value of the "manual_receiver_account" field.
	ManualReceiverAccount *string `json:"manual_receiver_account,omitempty"`
	// ManualReceiverQrImageURL holds the value of the "manual_receiver_qr_image_url" field.
	ManualReceiverQrImageURL *string `json:"manual_receiver_qr_image_url,omitempty"`
	// ManualReceiverRemark holds the value of the "manual_receiver_remark" field.
	ManualReceiverRemark *string `json:"manual_receiver_remark,omitempty"`
	// ManualTransferProofURL holds the value of the "manual_transfer_proof_url" field.
	ManualTransferProofURL *string `json:"manual_transfer_proof_url,omitempty"`
	// ManualTransferProofUploadedAt holds the value of the "manual_transfer_proof_uploaded_at" field.
	ManualTransferProofUploadedAt *time.Time `json:"manual_transfer_proof_uploaded_at,omitempty"`
	// ManualTransferOperatorUserID holds the value of the "manual_transfer_operator_user_id" field.
	ManualTransferOperatorUserID *int64 `json:"manual_transfer_operator_user_id,omitempty"`
	// AdminNote holds the value of the "admin_note" field.
	AdminNote *string `json:"admin_note,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SubscriptionRefundRequestQuery when eager-loading is set.
	Edges        SubscriptionRefundRequestEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SubscriptionRefundRequestEdges holds the relations/edges for other nodes in the graph.
type SubscriptionRefundRequestEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Subscription holds the value of the subscription edge.
	Subscription *UserSubscription `json:"subscription,omitempty"`
	// Settlement holds the value of the settlement edge.
	Settlement *SubscriptionSettlementOrder `json:"settlement,omitempty"`
	// ExpectedSettlement holds the value of the expected_settlement edge.
	ExpectedSettlement *SubscriptionSettlementOrder `json:"expected_settlement,omitempty"`
	// ManualTransferOperator holds the value of the manual_transfer_operator edge.
	ManualTransferOperator *User `json:"manual_transfer_operator,omitempty"`
	// Allocations holds the value of the allocations edge.
	Allocations []*SubscriptionRefundAllocation `json:"allocations,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [6]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SubscriptionRefundRequestEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// SubscriptionOrErr returns the Subscription value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SubscriptionRefundRequestEdges) SubscriptionOrErr() (*UserSubscription, error) {
	if e.Subscription != nil {
		return e.Subscription, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: usersubscription.Label}
	}
	return nil, &NotLoadedError{edge: "subscription"}
}

// SettlementOrErr returns the Settlement value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SubscriptionRefundRequestEdges) SettlementOrErr() (*SubscriptionSettlementOrder, error) {
	if e.Settlement != nil {
		return e.Settlement, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: subscriptionsettlementorder.Label}
	}
	return nil, &NotLoadedError{edge: "settlement"}
}

// ExpectedSettlementOrErr returns the ExpectedSettlement value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SubscriptionRefundRequestEdges) ExpectedSettlementOrErr() (*SubscriptionSettlementOrder, error) {
	if e.ExpectedSettlement != nil {
		return e.ExpectedSettlement, nil
	} else if e.loadedTypes[3] {
		return nil, &NotFoundError{label: subscriptionsettlementorder.Label}
	}
	return nil, &NotLoadedError{edge: "expected_settlement"}
}

// ManualTransferOperatorOrErr returns the ManualTransferOperator value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SubscriptionRefundRequestEdges) ManualTransferOperatorOrErr() (*User, error) {
	if e.ManualTransferOperator != nil {
		return e.ManualTransferOperator, nil
	} else if e.loadedTypes[4] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "manual_transfer_operator"}
}

// AllocationsOrErr returns the Allocations value or an error if the edge
// was not loaded in eager-loading.
func (e SubscriptionRefundRequestEdges) AllocationsOrErr() ([]*SubscriptionRefundAllocation, error) {
	if e.loadedTypes[5] {
		return e.Allocations, nil
	}
	return nil, &NotLoadedError{edge: "allocations"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SubscriptionRefundRequest) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case subscriptionrefundrequest.FieldRefundResidualValue, subscriptionrefundrequest.FieldGatewayRefundableTotal, subscriptionrefundrequest.FieldManualTransferAmount:
			values[i] = new(sql.NullFloat64)
		case subscriptionrefundrequest.FieldID, subscriptionrefundrequest.FieldUserID, subscriptionrefundrequest.FieldSubscriptionID, subscriptionrefundrequest.FieldSettlementID, subscriptionrefundrequest.FieldExpectedSettlementID, subscriptionrefundrequest.FieldManualTransferOperatorUserID:
			values[i] = new(sql.NullInt64)
		case subscriptionrefundrequest.FieldStatus, subscriptionrefundrequest.FieldRefundMode, subscriptionrefundrequest.FieldCurrency, subscriptionrefundrequest.FieldReason, subscriptionrefundrequest.FieldPreviewTokenHash, subscriptionrefundrequest.FieldPreviewFingerprint, subscriptionrefundrequest.FieldOriginalSubscriptionStatus, subscriptionrefundrequest.FieldManualReceiverType, subscriptionrefundrequest.FieldManualReceiverName, subscriptionrefundrequest.FieldManualReceiverAccount, subscriptionrefundrequest.FieldManualReceiverQrImageURL, subscriptionrefundrequest.FieldManualReceiverRemark, subscriptionrefundrequest.FieldManualTransferProofURL, subscriptionrefundrequest.FieldAdminNote:
			values[i] = new(sql.NullString)
		case subscriptionrefundrequest.FieldPreviewIssuedAt, subscriptionrefundrequest.FieldPreviewExpiresAt, subscriptionrefundrequest.FieldSubmittedAt, subscriptionrefundrequest.FieldFrozenAt, subscriptionrefundrequest.FieldCompletedAt, subscriptionrefundrequest.FieldCancelledAt, subscriptionrefundrequest.FieldOriginalSubscriptionExpiresAt, subscriptionrefundrequest.FieldManualTransferProofUploadedAt, subscriptionrefundrequest.FieldCreatedAt, subscriptionrefundrequest.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SubscriptionRefundRequest fields.
func (_m *SubscriptionRefundRequest) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case subscriptionrefundrequest.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case subscriptionrefundrequest.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case subscriptionrefundrequest.FieldSubscriptionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field subscription_id", values[i])
			} else if value.Valid {
				_m.SubscriptionID = value.Int64
			}
		case subscriptionrefundrequest.FieldSettlementID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field settlement_id", values[i])
			} else if value.Valid {
				_m.SettlementID = value.Int64
			}
		case subscriptionrefundrequest.FieldExpectedSettlementID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field expected_settlement_id", values[i])
			} else if value.Valid {
				_m.ExpectedSettlementID = value.Int64
			}
		case subscriptionrefundrequest.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case subscriptionrefundrequest.FieldRefundMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field refund_mode", values[i])
			} else if value.Valid {
				_m.RefundMode = value.String
			}
		case subscriptionrefundrequest.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				_m.Currency = new(string)
				*_m.Currency = value.String
			}
		case subscriptionrefundrequest.FieldReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reason", values[i])
			} else if value.Valid {
				_m.Reason = new(string)
				*_m.Reason = value.String
			}
		case subscriptionrefundrequest.FieldRefundResidualValue:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field refund_residual_value", values[i])
			} else if value.Valid {
				_m.RefundResidualValue = value.Float64
			}
		case subscriptionrefundrequest.FieldGatewayRefundableTotal:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field gateway_refundable_total", values[i])
			} else if value.Valid {
				_m.GatewayRefundableTotal = value.Float64
			}
		case subscriptionrefundrequest.FieldManualTransferAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field manual_transfer_amount", values[i])
			} else if value.Valid {
				_m.ManualTransferAmount = value.Float64
			}
		case subscriptionrefundrequest.FieldPreviewTokenHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field preview_token_hash", values[i])
			} else if value.Valid {
				_m.PreviewTokenHash = value.String
			}
		case subscriptionrefundrequest.FieldPreviewFingerprint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field preview_fingerprint", values[i])
			} else if value.Valid {
				_m.PreviewFingerprint = new(string)
				*_m.PreviewFingerprint = value.String
			}
		case subscriptionrefundrequest.FieldPreviewIssuedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field preview_issued_at", values[i])
			} else if value.Valid {
				_m.PreviewIssuedAt = value.Time
			}
		case subscriptionrefundrequest.FieldPreviewExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field preview_expires_at", values[i])
			} else if value.Valid {
				_m.PreviewExpiresAt = value.Time
			}
		case subscriptionrefundrequest.FieldSubmittedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field submitted_at", values[i])
			} else if value.Valid {
				_m.SubmittedAt = new(time.Time)
				*_m.SubmittedAt = value.Time
			}
		case subscriptionrefundrequest.FieldFrozenAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field frozen_at", values[i])
			} else if value.Valid {
				_m.FrozenAt = new(time.Time)
				*_m.FrozenAt = value.Time
			}
		case subscriptionrefundrequest.FieldCompletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field completed_at", values[i])
			} else if value.Valid {
				_m.CompletedAt = new(time.Time)
				*_m.CompletedAt = value.Time
			}
		case subscriptionrefundrequest.FieldCancelledAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field cancelled_at", values[i])
			} else if value.Valid {
				_m.CancelledAt = new(time.Time)
				*_m.CancelledAt = value.Time
			}
		case subscriptionrefundrequest.FieldOriginalSubscriptionStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field original_subscription_status", values[i])
			} else if value.Valid {
				_m.OriginalSubscriptionStatus = new(string)
				*_m.OriginalSubscriptionStatus = value.String
			}
		case subscriptionrefundrequest.FieldOriginalSubscriptionExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field original_subscription_expires_at", values[i])
			} else if value.Valid {
				_m.OriginalSubscriptionExpiresAt = new(time.Time)
				*_m.OriginalSubscriptionExpiresAt = value.Time
			}
		case subscriptionrefundrequest.FieldManualReceiverType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field manual_receiver_type", values[i])
			} else if value.Valid {
				_m.ManualReceiverType = new(string)
				*_m.ManualReceiverType = value.String
			}
		case subscriptionrefundrequest.FieldManualReceiverName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field manual_receiver_name", values[i])
			} else if value.Valid {
				_m.ManualReceiverName = new(string)
				*_m.ManualReceiverName = value.String
			}
		case subscriptionrefundrequest.FieldManualReceiverAccount:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field manual_receiver_account", values[i])
			} else if value.Valid {
				_m.ManualReceiverAccount = new(string)
				*_m.ManualReceiverAccount = value.String
			}
		case subscriptionrefundrequest.FieldManualReceiverQrImageURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field manual_receiver_qr_image_url", values[i])
			} else if value.Valid {
				_m.ManualReceiverQrImageURL = new(string)
				*_m.ManualReceiverQrImageURL = value.String
			}
		case subscriptionrefundrequest.FieldManualReceiverRemark:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field manual_receiver_remark", values[i])
			} else if value.Valid {
				_m.ManualReceiverRemark = new(string)
				*_m.ManualReceiverRemark = value.String
			}
		case subscriptionrefundrequest.FieldManualTransferProofURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field manual_transfer_proof_url", values[i])
			} else if value.Valid {
				_m.ManualTransferProofURL = new(string)
				*_m.ManualTransferProofURL = value.String
			}
		case subscriptionrefundrequest.FieldManualTransferProofUploadedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field manual_transfer_proof_uploaded_at", values[i])
			} else if value.Valid {
				_m.ManualTransferProofUploadedAt = new(time.Time)
				*_m.ManualTransferProofUploadedAt = value.Time
			}
		case subscriptionrefundrequest.FieldManualTransferOperatorUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field manual_transfer_operator_user_id", values[i])
			} else if value.Valid {
				_m.ManualTransferOperatorUserID = new(int64)
				*_m.ManualTransferOperatorUserID = value.Int64
			}
		case subscriptionrefundrequest.FieldAdminNote:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field admin_note", values[i])
			} else if value.Valid {
				_m.AdminNote = new(string)
				*_m.AdminNote = value.String
			}
		case subscriptionrefundrequest.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case subscriptionrefundrequest.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SubscriptionRefundRequest.
// This includes values selected through modifiers, order, etc.
func (_m *SubscriptionRefundRequest) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the SubscriptionRefundRequest entity.
func (_m *SubscriptionRefundRequest) QueryUser() *UserQuery {
	return NewSubscriptionRefundRequestClient(_m.config).QueryUser(_m)
}

// QuerySubscription queries the "subscription" edge of the SubscriptionRefundRequest entity.
func (_m *SubscriptionRefundRequest) QuerySubscription() *UserSubscriptionQuery {
	return NewSubscriptionRefundRequestClient(_m.config).QuerySubscription(_m)
}

// QuerySettlement queries the "settlement" edge of the SubscriptionRefundRequest entity.
func (_m *SubscriptionRefundRequest) QuerySettlement() *SubscriptionSettlementOrderQuery {
	return NewSubscriptionRefundRequestClient(_m.config).QuerySettlement(_m)
}

// QueryExpectedSettlement queries the "expected_settlement" edge of the SubscriptionRefundRequest entity.
func (_m *SubscriptionRefundRequest) QueryExpectedSettlement() *SubscriptionSettlementOrderQuery {
	return NewSubscriptionRefundRequestClient(_m.config).QueryExpectedSettlement(_m)
}

// QueryManualTransferOperator queries the "manual_transfer_operator" edge of the SubscriptionRefundRequest entity.
func (_m *SubscriptionRefundRequest) QueryManualTransferOperator() *UserQuery {
	return NewSubscriptionRefundRequestClient(_m.config).QueryManualTransferOperator(_m)
}

// QueryAllocations queries the "allocations" edge of the SubscriptionRefundRequest entity.
func (_m *SubscriptionRefundRequest) QueryAllocations() *SubscriptionRefundAllocationQuery {
	return NewSubscriptionRefundRequestClient(_m.config).QueryAllocations(_m)
}

// Update returns a builder for updating this SubscriptionRefundRequest.
// Note that you need to call SubscriptionRefundRequest.Unwrap() before calling this method if this SubscriptionRefundRequest
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SubscriptionRefundRequest) Update() *SubscriptionRefundRequestUpdateOne {
	return NewSubscriptionRefundRequestClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SubscriptionRefundRequest entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SubscriptionRefundRequest) Unwrap() *SubscriptionRefundRequest {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SubscriptionRefundRequest is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SubscriptionRefundRequest) String() string {
	var builder strings.Builder
	builder.WriteString("SubscriptionRefundRequest(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("subscription_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SubscriptionID))
	builder.WriteString(", ")
	builder.WriteString("settlement_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SettlementID))
	builder.WriteString(", ")
	builder.WriteString("expected_settlement_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ExpectedSettlementID))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("refund_mode=")
	builder.WriteString(_m.RefundMode)
	builder.WriteString(", ")
	if v := _m.Currency; v != nil {
		builder.WriteString("currency=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Reason; v != nil {
		builder.WriteString("reason=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("refund_residual_value=")
	builder.WriteString(fmt.Sprintf("%v", _m.RefundResidualValue))
	builder.WriteString(", ")
	builder.WriteString("gateway_refundable_total=")
	builder.WriteString(fmt.Sprintf("%v", _m.GatewayRefundableTotal))
	builder.WriteString(", ")
	builder.WriteString("manual_transfer_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.ManualTransferAmount))
	builder.WriteString(", ")
	builder.WriteString("preview_token_hash=")
	builder.WriteString(_m.PreviewTokenHash)
	builder.WriteString(", ")
	if v := _m.PreviewFingerprint; v != nil {
		builder.WriteString("preview_fingerprint=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("preview_issued_at=")
	builder.WriteString(_m.PreviewIssuedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("preview_expires_at=")
	builder.WriteString(_m.PreviewExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.SubmittedAt; v != nil {
		builder.WriteString("submitted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.FrozenAt; v != nil {
		builder.WriteString("frozen_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.CompletedAt; v != nil {
		builder.WriteString("completed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.CancelledAt; v != nil {
		builder.WriteString("cancelled_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.OriginalSubscriptionStatus; v != nil {
		builder.WriteString("original_subscription_status=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.OriginalSubscriptionExpiresAt; v != nil {
		builder.WriteString("original_subscription_expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ManualReceiverType; v != nil {
		builder.WriteString("manual_receiver_type=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ManualReceiverName; v != nil {
		builder.WriteString("manual_receiver_name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ManualReceiverAccount; v != nil {
		builder.WriteString("manual_receiver_account=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ManualReceiverQrImageURL; v != nil {
		builder.WriteString("manual_receiver_qr_image_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ManualReceiverRemark; v != nil {
		builder.WriteString("manual_receiver_remark=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ManualTransferProofURL; v != nil {
		builder.WriteString("manual_transfer_proof_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ManualTransferProofUploadedAt; v != nil {
		builder.WriteString("manual_transfer_proof_uploaded_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ManualTransferOperatorUserID; v != nil {
		builder.WriteString("manual_transfer_operator_user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.AdminNote; v != nil {
		builder.WriteString("admin_note=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SubscriptionRefundRequests is a parsable slice of SubscriptionRefundRequest.
type SubscriptionRefundRequests []*SubscriptionRefundRequest
