// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionrefundallocation"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionrefundrequest"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionsettlementorder"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/usersubscription"
)

// SubscriptionRefundRequestQuery is the builder for querying SubscriptionRefundRequest entities.
type SubscriptionRefundRequestQuery struct {
	config
	ctx                        *QueryContext
	order                      []subscriptionrefundrequest.OrderOption
	inters                     []Interceptor
	predicates                 []predicate.SubscriptionRefundRequest
	withUser                   *UserQuery
	withSubscription           *UserSubscriptionQuery
	withSettlement             *SubscriptionSettlementOrderQuery
	withExpectedSettlement     *SubscriptionSettlementOrderQuery
	withManualTransferOperator *UserQuery
	withAllocations            *SubscriptionRefundAllocationQuery
	modifiers                  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SubscriptionRefundRequestQuery builder.
func (_q *SubscriptionRefundRequestQuery) Where(ps ...predicate.SubscriptionRefundRequest) *SubscriptionRefundRequestQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *SubscriptionRefundRequestQuery) Limit(limit int) *SubscriptionRefundRequestQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *SubscriptionRefundRequestQuery) Offset(offset int) *SubscriptionRefundRequestQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *SubscriptionRefundRequestQuery) Unique(unique bool) *SubscriptionRefundRequestQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *SubscriptionRefundRequestQuery) Order(o ...subscriptionrefundrequest.OrderOption) *SubscriptionRefundRequestQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryUser chains the current query on the "user" edge.
func (_q *SubscriptionRefundRequestQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(subscriptionrefundrequest.Table, subscriptionrefundrequest.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, subscriptionrefundrequest.UserTable, subscriptionrefundrequest.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QuerySubscription chains the current query on the "subscription" edge.
func (_q *SubscriptionRefundRequestQuery) QuerySubscription() *UserSubscriptionQuery {
	query := (&UserSubscriptionClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(subscriptionrefundrequest.Table, subscriptionrefundrequest.FieldID, selector),
			sqlgraph.To(usersubscription.Table, usersubscription.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, subscriptionrefundrequest.SubscriptionTable, subscriptionrefundrequest.SubscriptionColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QuerySettlement chains the current query on the "settlement" edge.
func (_q *SubscriptionRefundRequestQuery) QuerySettlement() *SubscriptionSettlementOrderQuery {
	query := (&SubscriptionSettlementOrderClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(subscriptionrefundrequest.Table, subscriptionrefundrequest.FieldID, selector),
			sqlgraph.To(subscriptionsettlementorder.Table, subscriptionsettlementorder.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, subscriptionrefundrequest.SettlementTable, subscriptionrefundrequest.SettlementColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryExpectedSettlement chains the current query on the "expected_settlement" edge.
func (_q *SubscriptionRefundRequestQuery) QueryExpectedSettlement() *SubscriptionSettlementOrderQuery {
	query := (&SubscriptionSettlementOrderClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(subscriptionrefundrequest.Table, subscriptionrefundrequest.FieldID, selector),
			sqlgraph.To(subscriptionsettlementorder.Table, subscriptionsettlementorder.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, subscriptionrefundrequest.ExpectedSettlementTable, subscriptionrefundrequest.ExpectedSettlementColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryManualTransferOperator chains the current query on the "manual_transfer_operator" edge.
func (_q *SubscriptionRefundRequestQuery) QueryManualTransferOperator() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(subscriptionrefundrequest.Table, subscriptionrefundrequest.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, subscriptionrefundrequest.ManualTransferOperatorTable, subscriptionrefundrequest.ManualTransferOperatorColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAllocations chains the current query on the "allocations" edge.
func (_q *SubscriptionRefundRequestQuery) QueryAllocations() *SubscriptionRefundAllocationQuery {
	query := (&SubscriptionRefundAllocationClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(subscriptionrefundrequest.Table, subscriptionrefundrequest.FieldID, selector),
			sqlgraph.To(subscriptionrefundallocation.Table, subscriptionrefundallocation.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, subscriptionrefundrequest.AllocationsTable, subscriptionrefundrequest.AllocationsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first SubscriptionRefundRequest entity from the query.
// Returns a *NotFoundError when no SubscriptionRefundRequest was found.
func (_q *SubscriptionRefundRequestQuery) First(ctx context.Context) (*SubscriptionRefundRequest, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{subscriptionrefundrequest.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *SubscriptionRefundRequestQuery) FirstX(ctx context.Context) *SubscriptionRefundRequest {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SubscriptionRefundRequest ID from the query.
// Returns a *NotFoundError when no SubscriptionRefundRequest ID was found.
func (_q *SubscriptionRefundRequestQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{subscriptionrefundrequest.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *SubscriptionRefundRequestQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SubscriptionRefundRequest entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SubscriptionRefundRequest entity is found.
// Returns a *NotFoundError when no SubscriptionRefundRequest entities are found.
func (_q *SubscriptionRefundRequestQuery) Only(ctx context.Context) (*SubscriptionRefundRequest, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{subscriptionrefundrequest.Label}
	default:
		return nil, &NotSingularError{subscriptionrefundrequest.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *SubscriptionRefundRequestQuery) OnlyX(ctx context.Context) *SubscriptionRefundRequest {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SubscriptionRefundRequest ID in the query.
// Returns a *NotSingularError when more than one SubscriptionRefundRequest ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *SubscriptionRefundRequestQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{subscriptionrefundrequest.Label}
	default:
		err = &NotSingularError{subscriptionrefundrequest.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *SubscriptionRefundRequestQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SubscriptionRefundRequests.
func (_q *SubscriptionRefundRequestQuery) All(ctx context.Context) ([]*SubscriptionRefundRequest, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SubscriptionRefundRequest, *SubscriptionRefundRequestQuery]()
	return withInterceptors[[]*SubscriptionRefundRequest](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *SubscriptionRefundRequestQuery) AllX(ctx context.Context) []*SubscriptionRefundRequest {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SubscriptionRefundRequest IDs.
func (_q *SubscriptionRefundRequestQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(subscriptionrefundrequest.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *SubscriptionRefundRequestQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *SubscriptionRefundRequestQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*SubscriptionRefundRequestQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *SubscriptionRefundRequestQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *SubscriptionRefundRequestQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *SubscriptionRefundRequestQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SubscriptionRefundRequestQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *SubscriptionRefundRequestQuery) Clone() *SubscriptionRefundRequestQuery {
	if _q == nil {
		return nil
	}
	return &SubscriptionRefundRequestQuery{
		config:                     _q.config,
		ctx:                        _q.ctx.Clone(),
		order:                      append([]subscriptionrefundrequest.OrderOption{}, _q.order...),
		inters:                     append([]Interceptor{}, _q.inters...),
		predicates:                 append([]predicate.SubscriptionRefundRequest{}, _q.predicates...),
		withUser:                   _q.withUser.Clone(),
		withSubscription:           _q.withSubscription.Clone(),
		withSettlement:             _q.withSettlement.Clone(),
		withExpectedSettlement:     _q.withExpectedSettlement.Clone(),
		withManualTransferOperator: _q.withManualTransferOperator.Clone(),
		withAllocations:            _q.withAllocations.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *SubscriptionRefundRequestQuery) WithUser(opts ...func(*UserQuery)) *SubscriptionRefundRequestQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withUser = query
	return _q
}

// WithSubscription tells the query-builder to eager-load the nodes that are connected to
// the "subscription" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *SubscriptionRefundRequestQuery) WithSubscription(opts ...func(*UserSubscriptionQuery)) *SubscriptionRefundRequestQuery {
	query := (&UserSubscriptionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSubscription = query
	return _q
}

// WithSettlement tells the query-builder to eager-load the nodes that are connected to
// the "settlement" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *SubscriptionRefundRequestQuery) WithSettlement(opts ...func(*SubscriptionSettlementOrderQuery)) *SubscriptionRefundRequestQuery {
	query := (&SubscriptionSettlementOrderClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSettlement = query
	return _q
}

// WithExpectedSettlement tells the query-builder to eager-load the nodes that are connected to
// the "expected_settlement" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *SubscriptionRefundRequestQuery) WithExpectedSettlement(opts ...func(*SubscriptionSettlementOrderQuery)) *SubscriptionRefundRequestQuery {
	query := (&SubscriptionSettlementOrderClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withExpectedSettlement = query
	return _q
}

// WithManualTransferOperator tells the query-builder to eager-load the nodes that are connected to
// the "manual_transfer_operator" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *SubscriptionRefundRequestQuery) WithManualTransferOperator(opts ...func(*UserQuery)) *SubscriptionRefundRequestQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withManualTransferOperator = query
	return _q
}

// WithAllocations tells the query-builder to eager-load the nodes that are connected to
// the "allocations" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *SubscriptionRefundRequestQuery) WithAllocations(opts ...func(*SubscriptionRefundAllocationQuery)) *SubscriptionRefundRequestQuery {
	query := (&SubscriptionRefundAllocationClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAllocations = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserID int64 `json:"user_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SubscriptionRefundRequest.Query().
//		GroupBy(subscriptionrefundrequest.FieldUserID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *SubscriptionRefundRequestQuery) GroupBy(field string, fields ...string) *SubscriptionRefundRequestGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SubscriptionRefundRequestGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = subscriptionrefundrequest.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserID int64 `json:"user_id,omitempty"`
//	}
//
//	client.SubscriptionRefundRequest.Query().
//		Select(subscriptionrefundrequest.FieldUserID).
//		Scan(ctx, &v)
func (_q *SubscriptionRefundRequestQuery) Select(fields ...string) *SubscriptionRefundRequestSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &SubscriptionRefundRequestSelect{SubscriptionRefundRequestQuery: _q}
	sbuild.label = subscriptionrefundrequest.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SubscriptionRefundRequestSelect configured with the given aggregations.
func (_q *SubscriptionRefundRequestQuery) Aggregate(fns ...AggregateFunc) *SubscriptionRefundRequestSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *SubscriptionRefundRequestQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !subscriptionrefundrequest.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *SubscriptionRefundRequestQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SubscriptionRefundRequest, error) {
	var (
		nodes       = []*SubscriptionRefundRequest{}
		_spec       = _q.querySpec()
		loadedTypes = [6]bool{
			_q.withUser != nil,
			_q.withSubscription != nil,
			_q.withSettlement != nil,
			_q.withExpectedSettlement != nil,
			_q.withManualTransferOperator != nil,
			_q.withAllocations != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SubscriptionRefundRequest).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SubscriptionRefundRequest{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withUser; query != nil {
		if err := _q.loadUser(ctx, query, nodes, nil,
			func(n *SubscriptionRefundRequest, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withSubscription; query != nil {
		if err := _q.loadSubscription(ctx, query, nodes, nil,
			func(n *SubscriptionRefundRequest, e *UserSubscription) { n.Edges.Subscription = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withSettlement; query != nil {
		if err := _q.loadSettlement(ctx, query, nodes, nil,
			func(n *SubscriptionRefundRequest, e *SubscriptionSettlementOrder) { n.Edges.Settlement = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withExpectedSettlement; query != nil {
		if err := _q.loadExpectedSettlement(ctx, query, nodes, nil,
			func(n *SubscriptionRefundRequest, e *SubscriptionSettlementOrder) { n.Edges.ExpectedSettlement = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withManualTransferOperator; query != nil {
		if err := _q.loadManualTransferOperator(ctx, query, nodes, nil,
			func(n *SubscriptionRefundRequest, e *User) { n.Edges.ManualTransferOperator = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withAllocations; query != nil {
		if err := _q.loadAllocations(ctx, query, nodes,
			func(n *SubscriptionRefundRequest) { n.Edges.Allocations = []*SubscriptionRefundAllocation{} },
			func(n *SubscriptionRefundRequest, e *SubscriptionRefundAllocation) {
				n.Edges.Allocations = append(n.Edges.Allocations, e)
			}); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *SubscriptionRefundRequestQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*SubscriptionRefundRequest, init func(*SubscriptionRefundRequest), assign func(*SubscriptionRefundRequest, *User)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*SubscriptionRefundRequest)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *SubscriptionRefundRequestQuery) loadSubscription(ctx context.Context, query *UserSubscriptionQuery, nodes []*SubscriptionRefundRequest, init func(*SubscriptionRefundRequest), assign func(*SubscriptionRefundRequest, *UserSubscription)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*SubscriptionRefundRequest)
	for i := range nodes {
		fk := nodes[i].SubscriptionID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(usersubscription.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "subscription_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *SubscriptionRefundRequestQuery) loadSettlement(ctx context.Context, query *SubscriptionSettlementOrderQuery, nodes []*SubscriptionRefundRequest, init func(*SubscriptionRefundRequest), assign func(*SubscriptionRefundRequest, *SubscriptionSettlementOrder)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*SubscriptionRefundRequest)
	for i := range nodes {
		fk := nodes[i].SettlementID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(subscriptionsettlementorder.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "settlement_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *SubscriptionRefundRequestQuery) loadExpectedSettlement(ctx context.Context, query *SubscriptionSettlementOrderQuery, nodes []*SubscriptionRefundRequest, init func(*SubscriptionRefundRequest), assign func(*SubscriptionRefundRequest, *SubscriptionSettlementOrder)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*SubscriptionRefundRequest)
	for i := range nodes {
		fk := nodes[i].ExpectedSettlementID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(subscriptionsettlementorder.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "expected_settlement_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *SubscriptionRefundRequestQuery) loadManualTransferOperator(ctx context.Context, query *UserQuery, nodes []*SubscriptionRefundRequest, init func(*SubscriptionRefundRequest), assign func(*SubscriptionRefundRequest, *User)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*SubscriptionRefundRequest)
	for i := range nodes {
		if nodes[i].ManualTransferOperatorUserID == nil {
			continue
		}
		fk := *nodes[i].ManualTransferOperatorUserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "manual_transfer_operator_user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *SubscriptionRefundRequestQuery) loadAllocations(ctx context.Context, query *SubscriptionRefundAllocationQuery, nodes []*SubscriptionRefundRequest, init func(*SubscriptionRefundRequest), assign func(*SubscriptionRefundRequest, *SubscriptionRefundAllocation)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*SubscriptionRefundRequest)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(subscriptionrefundallocation.FieldRefundRequestID)
	}
	query.Where(predicate.SubscriptionRefundAllocation(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(subscriptionrefundrequest.AllocationsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.RefundRequestID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "refund_request_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *SubscriptionRefundRequestQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *SubscriptionRefundRequestQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(subscriptionrefundrequest.Table, subscriptionrefundrequest.Columns, sqlgraph.NewFieldSpec(subscriptionrefundrequest.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subscriptionrefundrequest.FieldID)
		for i := range fields {
			if fields[i] != subscriptionrefundrequest.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withUser != nil {
			_spec.Node.AddColumnOnce(subscriptionrefundrequest.FieldUserID)
		}
		if _q.withSubscription != nil {
			_spec.Node.AddColumnOnce(subscriptionrefundrequest.FieldSubscriptionID)
		}
		if _q.withSettlement != nil {
			_spec.Node.AddColumnOnce(subscriptionrefundrequest.FieldSettlementID)
		}
		if _q.withExpectedSettlement != nil {
			_spec.Node.AddColumnOnce(subscriptionrefundrequest.FieldExpectedSettlementID)
		}
		if _q.withManualTransferOperator != nil {
			_spec.Node.AddColumnOnce(subscriptionrefundrequest.FieldManualTransferOperatorUserID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *SubscriptionRefundRequestQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(subscriptionrefundrequest.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = subscriptionrefundrequest.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *SubscriptionRefundRequestQuery) ForUpdate(opts ...sql.LockOption) *SubscriptionRefundRequestQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *SubscriptionRefundRequestQuery) ForShare(opts ...sql.LockOption) *SubscriptionRefundRequestQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// SubscriptionRefundRequestGroupBy is the group-by builder for SubscriptionRefundRequest entities.
type SubscriptionRefundRequestGroupBy struct {
	selector
	build *SubscriptionRefundRequestQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *SubscriptionRefundRequestGroupBy) Aggregate(fns ...AggregateFunc) *SubscriptionRefundRequestGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *SubscriptionRefundRequestGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SubscriptionRefundRequestQuery, *SubscriptionRefundRequestGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *SubscriptionRefundRequestGroupBy) sqlScan(ctx context.Context, root *SubscriptionRefundRequestQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SubscriptionRefundRequestSelect is the builder for selecting fields of SubscriptionRefundRequest entities.
type SubscriptionRefundRequestSelect struct {
	*SubscriptionRefundRequestQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *SubscriptionRefundRequestSelect) Aggregate(fns ...AggregateFunc) *SubscriptionRefundRequestSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *SubscriptionRefundRequestSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SubscriptionRefundRequestQuery, *SubscriptionRefundRequestSelect](ctx, _s.SubscriptionRefundRequestQuery, _s, _s.inters, v)
}

func (_s *SubscriptionRefundRequestSelect) sqlScan(ctx context.Context, root *SubscriptionRefundRequestQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
