// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionrefundrequest"
)

// SubscriptionRefundRequestDelete is the builder for deleting a SubscriptionRefundRequest entity.
type SubscriptionRefundRequestDelete struct {
	config
	hooks    []Hook
	mutation *SubscriptionRefundRequestMutation
}

// Where appends a list predicates to the SubscriptionRefundRequestDelete builder.
func (_d *SubscriptionRefundRequestDelete) Where(ps ...predicate.SubscriptionRefundRequest) *SubscriptionRefundRequestDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *SubscriptionRefundRequestDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SubscriptionRefundRequestDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *SubscriptionRefundRequestDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(subscriptionrefundrequest.Table, sqlgraph.NewFieldSpec(subscriptionrefundrequest.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// SubscriptionRefundRequestDeleteOne is the builder for deleting a single SubscriptionRefundRequest entity.
type SubscriptionRefundRequestDeleteOne struct {
	_d *SubscriptionRefundRequestDelete
}

// Where appends a list predicates to the SubscriptionRefundRequestDelete builder.
func (_d *SubscriptionRefundRequestDeleteOne) Where(ps ...predicate.SubscriptionRefundRequest) *SubscriptionRefundRequestDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *SubscriptionRefundRequestDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{subscriptionrefundrequest.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SubscriptionRefundRequestDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
