// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionplan"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionsettlementorder"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/usersubscription"
)

// SubscriptionSettlementOrderUpdate is the builder for updating SubscriptionSettlementOrder entities.
type SubscriptionSettlementOrderUpdate struct {
	config
	hooks    []Hook
	mutation *SubscriptionSettlementOrderMutation
}

// Where appends a list predicates to the SubscriptionSettlementOrderUpdate builder.
func (_u *SubscriptionSettlementOrderUpdate) Where(ps ...predicate.SubscriptionSettlementOrder) *SubscriptionSettlementOrderUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *SubscriptionSettlementOrderUpdate) SetUserID(v int64) *SubscriptionSettlementOrderUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SubscriptionSettlementOrderUpdate) SetNillableUserID(v *int64) *SubscriptionSettlementOrderUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetPrevSettlementID sets the "prev_settlement_id" field.
func (_u *SubscriptionSettlementOrderUpdate) SetPrevSettlementID(v int64) *SubscriptionSettlementOrderUpdate {
	_u.mutation.SetPrevSettlementID(v)
	return _u
}

// SetNillablePrevSettlementID sets the "prev_settlement_id" field if the given value is not nil.
func (_u *SubscriptionSettlementOrderUpdate) SetNillablePrevSettlementID(v *int64) *SubscriptionSettlementOrderUpdate {
	if v != nil {
		_u.SetPrevSettlementID(*v)
	}
	return _u
}

// ClearPrevSettlementID clears the value of the "prev_settlement_id" field.
func (_u *SubscriptionSettlementOrderUpdate) ClearPrevSettlementID() *SubscriptionSettlementOrderUpdate {
	_u.mutation.ClearPrevSettlementID()
	return _u
}

// SetActionType sets the "action_type" field.
func (_u *SubscriptionSettlementOrderUpdate) SetActionType(v string) *SubscriptionSettlementOrderUpdate {
	_u.mutation.SetActionType(v)
	return _u
}

// SetNillableActionType sets the "action_type" field if the given value is not nil.
func (_u *SubscriptionSettlementOrderUpdate) SetNillableActionType(v *string) *SubscriptionSettlementOrderUpdate {
	if v != nil {
		_u.SetActionType(*v)
	}
	return _u
}

// SetActionSource sets the "action_source" field.
func (_u *SubscriptionSettlementOrderUpdate) SetActionSource(v string) *SubscriptionSettlementOrderUpdate {
	_u.mutation.SetActionSource(v)
	return _u
}

// SetNillableActionSource sets the "action_source" field if the given value is not nil.
func (_u *SubscriptionSettlementOrderUpdate) SetNillableActionSource(v *string) *SubscriptionSettlementOrderUpdate {
	if v != nil {
		_u.SetActionSource(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SubscriptionSettlementOrderUpdate) SetStatus(v string) *SubscriptionSettlementOrderUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SubscriptionSettlementOrderUpdate) SetNillableStatus(v *string) *SubscriptionSettlementOrderUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetTriggerRefType sets the "trigger_ref_type" field.
func (_u *SubscriptionSettlementOrderUpdate) SetTriggerRefType(v string) *SubscriptionSettlementOrderUpdate {
	_u.mutation.SetTriggerRefType(v)
	return _u
}

// SetNillableTriggerRefType sets the "trigger_ref_type" field if the given value is not nil.
func (_u *SubscriptionSettlementOrderUpdate) SetNillableTriggerRefType(v *string) *SubscriptionSettlementOrderUpdate {
	if v != nil {
		_u.SetTriggerRefType(*v)
	}
	return _u
}

// SetTriggerRefID sets the "trigger_ref_id" field.
func (_u *SubscriptionSettlementOrderUpdate) SetTriggerRefID(v int64) *SubscriptionSettlementOrderUpdate {
	_u.mutation.ResetTriggerRefID()
	_u.mutation.SetTriggerRefID(v)
	return _u
}

// SetNillableTriggerRefID sets the "trigger_ref_id" field if the given value is not nil.
func (_u *SubscriptionSettlementOrderUpdate) SetNillableTriggerRefID(v *int64) *SubscriptionSettlementOrderUpdate {
	if v != nil {
		_u.SetTriggerRefID(*v)
	}
	return _u
}

// AddTriggerRefID adds value to the "trigger_ref_id" field.
func (_u *SubscriptionSettlementOrderUpdate) AddTriggerRefID(v int64) *SubscriptionSettlementOrderUpdate {
	_u.mutation.AddTriggerRefID(v)
	return _u
}

// ClearTriggerRefID clears the value of the "trigger_ref_id" field.
func (_u *SubscriptionSettlementOrderUpdate) ClearTriggerRefID() *SubscriptionSettlementOrderUpdate {
	_u.mutation.ClearTriggerRefID()
	return _u
}

// SetOperatorUserID sets the "operator_user_id" field.
func (_u *SubscriptionSettlementOrderUpdate) SetOperatorUserID(v int64) *SubscriptionSettlementOrderUpdate {
	_u.mutation.SetOperatorUserID(v)
	return _u
}

// SetNillableOperatorUserID sets the "operator_user_id" field if the given value is not nil.
func (_u *SubscriptionSettlementOrderUpdate) SetNillableOperatorUserID(v *int64) *SubscriptionSettlementOrderUpdate {
	if v != nil {
		_u.SetOperatorUserID(*v)
	}
	return _u
}

// SetActionNote sets the "action_note" field.
func (_u *SubscriptionSettlementOrderUpdate) SetActionNote(v string) *SubscriptionSettlementOrderUpdate {
	_u.mutation.SetActionNote(v)
	return _u
}

// SetNillableActionNote sets the "action_note" field if the given value is not nil.
func (_u *SubscriptionSettlementOrderUpdate) SetNillableActionNote(v *string) *SubscriptionSettlementOrderUpdate {
	if v != nil {
		_u.SetActionNote(*v)
	}
	return _u
}

// ClearActionNote clears the value of the "action_note" field.
func (_u *SubscriptionSettlementOrderUpdate) ClearActionNote() *SubscriptionSettlementOrderUpdate {
	_u.mutation.ClearActionNote()
	return _u
}

// SetCarryInResidualValue sets the "carry_in_residual_value" field.
func (_u *SubscriptionSettlementOrderUpdate) SetCarryInResidualValue(v float64) *SubscriptionSettlementOrderUpdate {
	_u.mutation.ResetCarryInResidualValue()
	_u.mutation.SetCarryInResidualValue(v)
	return _u
}

// SetNillableCarryInResidualValue sets the "carry_in_residual_value" field if the given value is not nil.
func (_u *SubscriptionSettlementOrderUpdate) SetNillableCarryInResidualValue(v *float64) *SubscriptionSettlementOrderUpdate {
	if v != nil {
		_u.SetCarryInResidualValue(*v)
	}
	return _u
}

// AddCarryInResidualValue adds value to the "carry_in_residual_value" field.
func (_u *SubscriptionSettlementOrderUpdate) AddCarryInResidualValue(v float64) *SubscriptionSettlementOrderUpdate {
	_u.mutation.AddCarryInResidualValue(v)
	return _u
}

// SetActionDeltaValue sets the "action_delta_value" field.
func (_u *SubscriptionSettlementOrderUpdate) SetActionDeltaValue(v float64) *SubscriptionSettlementOrderUpdate {
	_u.mutation.ResetActionDeltaValue()
	_u.mutation.SetActionDeltaValue(v)
	return _u
}

// SetNillableActionDeltaValue sets the "action_delta_value" field if the given value is not nil.
func (_u *SubscriptionSettlementOrderUpdate) SetNillableActionDeltaValue(v *float64) *SubscriptionSettlementOrderUpdate {
	if v != nil {
		_u.SetActionDeltaValue(*v)
	}
	return _u
}

// AddActionDeltaValue adds value to the "action_delta_value" field.
func (_u *SubscriptionSettlementOrderUpdate) AddActionDeltaValue(v float64) *SubscriptionSettlementOrderUpdate {
	_u.mutation.AddActionDeltaValue(v)
	return _u
}

// SetAfterSettlementValue sets the "after_settlement_value" field.
func (_u *SubscriptionSettlementOrderUpdate) SetAfterSettlementValue(v float64) *SubscriptionSettlementOrderUpdate {
	_u.mutation.ResetAfterSettlementValue()
	_u.mutation.SetAfterSettlementValue(v)
	return _u
}

// SetNillableAfterSettlementValue sets the "after_settlement_value" field if the given value is not nil.
func (_u *SubscriptionSettlementOrderUpdate) SetNillableAfterSettlementValue(v *float64) *SubscriptionSettlementOrderUpdate {
	if v != nil {
		_u.SetAfterSettlementValue(*v)
	}
	return _u
}

// AddAfterSettlementValue adds value to the "after_settlement_value" field.
func (_u *SubscriptionSettlementOrderUpdate) AddAfterSettlementValue(v float64) *SubscriptionSettlementOrderUpdate {
	_u.mutation.AddAfterSettlementValue(v)
	return _u
}

// SetRefundResidualValue sets the "refund_residual_value" field.
func (_u *SubscriptionSettlementOrderUpdate) SetRefundResidualValue(v float64) *SubscriptionSettlementOrderUpdate {
	_u.mutation.ResetRefundResidualValue()
	_u.mutation.SetRefundResidualValue(v)
	return _u
}

// SetNillableRefundResidualValue sets the "refund_residual_value" field if the given value is not nil.
func (_u *SubscriptionSettlementOrderUpdate) SetNillableRefundResidualValue(v *float64) *SubscriptionSettlementOrderUpdate {
	if v != nil {
		_u.SetRefundResidualValue(*v)
	}
	return _u
}

// AddRefundResidualValue adds value to the "refund_residual_value" field.
func (_u *SubscriptionSettlementOrderUpdate) AddRefundResidualValue(v float64) *SubscriptionSettlementOrderUpdate {
	_u.mutation.AddRefundResidualValue(v)
	return _u
}

// ClearRefundResidualValue clears the value of the "refund_residual_value" field.
func (_u *SubscriptionSettlementOrderUpdate) ClearRefundResidualValue() *SubscriptionSettlementOrderUpdate {
	_u.mutation.ClearRefundResidualValue()
	return _u
}

// SetWriteoffValue sets the "writeoff_value" field.
func (_u *SubscriptionSettlementOrderUpdate) SetWriteoffValue(v float64) *SubscriptionSettlementOrderUpdate {
	_u.mutation.ResetWriteoffValue()
	_u.mutation.SetWriteoffValue(v)
	return _u
}

// SetNillableWriteoffValue sets the "writeoff_value" field if the given value is not nil.
func (_u *SubscriptionSettlementOrderUpdate) SetNillableWriteoffValue(v *float64) *SubscriptionSettlementOrderUpdate {
	if v != nil {
		_u.SetWriteoffValue(*v)
	}
	return _u
}

// AddWriteoffValue adds value to the "writeoff_value" field.
func (_u *SubscriptionSettlementOrderUpdate) AddWriteoffValue(v float64) *SubscriptionSettlementOrderUpdate {
	_u.mutation.AddWriteoffValue(v)
	return _u
}

// SetAfterUserSubscriptionID sets the "after_user_subscription_id" field.
func (_u *SubscriptionSettlementOrderUpdate) SetAfterUserSubscriptionID(v int64) *SubscriptionSettlementOrderUpdate {
	_u.mutation.SetAfterUserSubscriptionID(v)
	return _u
}

// SetNillableAfterUserSubscriptionID sets the "after_user_subscription_id" field if the given value is not nil.
func (_u *SubscriptionSettlementOrderUpdate) SetNillableAfterUserSubscriptionID(v *int64) *SubscriptionSettlementOrderUpdate {
	if v != nil {
		_u.SetAfterUserSubscriptionID(*v)
	}
	return _u
}

// ClearAfterUserSubscriptionID clears the value of the "after_user_subscription_id" field.
func (_u *SubscriptionSettlementOrderUpdate) ClearAfterUserSubscriptionID() *SubscriptionSettlementOrderUpdate {
	_u.mutation.ClearAfterUserSubscriptionID()
	return _u
}

// SetAfterPlanID sets the "after_plan_id" field.
func (_u *SubscriptionSettlementOrderUpdate) SetAfterPlanID(v int64) *SubscriptionSettlementOrderUpdate {
	_u.mutation.SetAfterPlanID(v)
	return _u
}

// SetNillableAfterPlanID sets the "after_plan_id" field if the given value is not nil.
func (_u *SubscriptionSettlementOrderUpdate) SetNillableAfterPlanID(v *int64) *SubscriptionSettlementOrderUpdate {
	if v != nil {
		_u.SetAfterPlanID(*v)
	}
	return _u
}

// ClearAfterPlanID clears the value of the "after_plan_id" field.
func (_u *SubscriptionSettlementOrderUpdate) ClearAfterPlanID() *SubscriptionSettlementOrderUpdate {
	_u.mutation.ClearAfterPlanID()
	return _u
}

// SetAfterPlanNameSnapshot sets the "after_plan_name_snapshot" field.
func (_u *SubscriptionSettlementOrderUpdate) SetAfterPlanNameSnapshot(v string) *SubscriptionSettlementOrderUpdate {
	_u.mutation.SetAfterPlanNameSnapshot(v)
	return _u
}

// SetNillableAfterPlanNameSnapshot sets the "after_plan_name_snapshot" field if the given value is not nil.
func (_u *SubscriptionSettlementOrderUpdate) SetNillableAfterPlanNameSnapshot(v *string) *SubscriptionSettlementOrderUpdate {
	if v != nil {
		_u.SetAfterPlanNameSnapshot(*v)
	}
	return _u
}

// ClearAfterPlanNameSnapshot clears the value of the "after_plan_name_snapshot" field.
func (_u *SubscriptionSettlementOrderUpdate) ClearAfterPlanNameSnapshot() *SubscriptionSettlementOrderUpdate {
	_u.mutation.ClearAfterPlanNameSnapshot()
	return _u
}

// SetAfterPlanPriceSnapshot sets the "after_plan_price_snapshot" field.
func (_u *SubscriptionSettlementOrderUpdate) SetAfterPlanPriceSnapshot(v float64) *SubscriptionSettlementOrderUpdate {
	_u.mutation.ResetAfterPlanPriceSnapshot()
	_u.mutation.SetAfterPlanPriceSnapshot(v)
	return _u
}

// SetNillableAfterPlanPriceSnapshot sets the "after_plan_price_snapshot" field if the given value is not nil.
func (_u *SubscriptionSettlementOrderUpdate) SetNillableAfterPlanPriceSnapshot(v *float64) *SubscriptionSettlementOrderUpdate {
	if v != nil {
		_u.SetAfterPlanPriceSnapshot(*v)
	}
	return _u
}

// AddAfterPlanPriceSnapshot adds value to the "after_plan_price_snapshot" field.
func (_u *SubscriptionSettlementOrderUpdate) AddAfterPlanPriceSnapshot(v float64) *SubscriptionSettlementOrderUpdate {
	_u.mutation.AddAfterPlanPriceSnapshot(v)
	return _u
}

// ClearAfterPlanPriceSnapshot clears the value of the "after_plan_price_snapshot" field.
func (_u *SubscriptionSettlementOrderUpdate) ClearAfterPlanPriceSnapshot() *SubscriptionSettlementOrderUpdate {
	_u.mutation.ClearAfterPlanPriceSnapshot()
	return _u
}

// SetAfterValidityDaysSnapshot sets the "after_validity_days_snapshot" field.
func (_u *SubscriptionSettlementOrderUpdate) SetAfterValidityDaysSnapshot(v int) *SubscriptionSettlementOrderUpdate {
	_u.mutation.ResetAfterValidityDaysSnapshot()
	_u.mutation.SetAfterValidityDaysSnapshot(v)
	return _u
}

// SetNillableAfterValidityDaysSnapshot sets the "after_validity_days_snapshot" field if the given value is not nil.
func (_u *SubscriptionSettlementOrderUpdate) SetNillableAfterValidityDaysSnapshot(v *int) *SubscriptionSettlementOrderUpdate {
	if v != nil {
		_u.SetAfterValidityDaysSnapshot(*v)
	}
	return _u
}

// AddAfterValidityDaysSnapshot adds value to the "after_validity_days_snapshot" field.
func (_u *SubscriptionSettlementOrderUpdate) AddAfterValidityDaysSnapshot(v int) *SubscriptionSettlementOrderUpdate {
	_u.mutation.AddAfterValidityDaysSnapshot(v)
	return _u
}

// ClearAfterValidityDaysSnapshot clears the value of the "after_validity_days_snapshot" field.
func (_u *SubscriptionSettlementOrderUpdate) ClearAfterValidityDaysSnapshot() *SubscriptionSettlementOrderUpdate {
	_u.mutation.ClearAfterValidityDaysSnapshot()
	return _u
}

// SetAfterValidityUnitSnapshot sets the "after_validity_unit_snapshot" field.
func (_u *SubscriptionSettlementOrderUpdate) SetAfterValidityUnitSnapshot(v string) *SubscriptionSettlementOrderUpdate {
	_u.mutation.SetAfterValidityUnitSnapshot(v)
	return _u
}

// SetNillableAfterValidityUnitSnapshot sets the "after_validity_unit_snapshot" field if the given value is not nil.
func (_u *SubscriptionSettlementOrderUpdate) SetNillableAfterValidityUnitSnapshot(v *string) *SubscriptionSettlementOrderUpdate {
	if v != nil {
		_u.SetAfterValidityUnitSnapshot(*v)
	}
	return _u
}

// ClearAfterValidityUnitSnapshot clears the value of the "after_validity_unit_snapshot" field.
func (_u *SubscriptionSettlementOrderUpdate) ClearAfterValidityUnitSnapshot() *SubscriptionSettlementOrderUpdate {
	_u.mutation.ClearAfterValidityUnitSnapshot()
	return _u
}

// SetAfterStartsAt sets the "after_starts_at" field.
func (_u *SubscriptionSettlementOrderUpdate) SetAfterStartsAt(v time.Time) *SubscriptionSettlementOrderUpdate {
	_u.mutation.SetAfterStartsAt(v)
	return _u
}

// SetNillableAfterStartsAt sets the "after_starts_at" field if the given value is not nil.
func (_u *SubscriptionSettlementOrderUpdate) SetNillableAfterStartsAt(v *time.Time) *SubscriptionSettlementOrderUpdate {
	if v != nil {
		_u.SetAfterStartsAt(*v)
	}
	return _u
}

// ClearAfterStartsAt clears the value of the "after_starts_at" field.
func (_u *SubscriptionSettlementOrderUpdate) ClearAfterStartsAt() *SubscriptionSettlementOrderUpdate {
	_u.mutation.ClearAfterStartsAt()
	return _u
}

// SetAfterExpiresAt sets the "after_expires_at" field.
func (_u *SubscriptionSettlementOrderUpdate) SetAfterExpiresAt(v time.Time) *SubscriptionSettlementOrderUpdate {
	_u.mutation.SetAfterExpiresAt(v)
	return _u
}

// SetNillableAfterExpiresAt sets the "after_expires_at" field if the given value is not nil.
func (_u *SubscriptionSettlementOrderUpdate) SetNillableAfterExpiresAt(v *time.Time) *SubscriptionSettlementOrderUpdate {
	if v != nil {
		_u.SetAfterExpiresAt(*v)
	}
	return _u
}

// ClearAfterExpiresAt clears the value of the "after_expires_at" field.
func (_u *SubscriptionSettlementOrderUpdate) ClearAfterExpiresAt() *SubscriptionSettlementOrderUpdate {
	_u.mutation.ClearAfterExpiresAt()
	return _u
}

// SetAfterDailyQuotaKnivesSnapshot sets the "after_daily_quota_knives_snapshot" field.
func (_u *SubscriptionSettlementOrderUpdate) SetAfterDailyQuotaKnivesSnapshot(v float64) *SubscriptionSettlementOrderUpdate {
	_u.mutation.ResetAfterDailyQuotaKnivesSnapshot()
	_u.mutation.SetAfterDailyQuotaKnivesSnapshot(v)
	return _u
}

// SetNillableAfterDailyQuotaKnivesSnapshot sets the "after_daily_quota_knives_snapshot" field if the given value is not nil.
func (_u *SubscriptionSettlementOrderUpdate) SetNillableAfterDailyQuotaKnivesSnapshot(v *float64) *SubscriptionSettlementOrderUpdate {
	if v != nil {
		_u.SetAfterDailyQuotaKnivesSnapshot(*v)
	}
	return _u
}

// AddAfterDailyQuotaKnivesSnapshot adds value to the "after_daily_quota_knives_snapshot" field.
func (_u *SubscriptionSettlementOrderUpdate) AddAfterDailyQuotaKnivesSnapshot(v float64) *SubscriptionSettlementOrderUpdate {
	_u.mutation.AddAfterDailyQuotaKnivesSnapshot(v)
	return _u
}

// ClearAfterDailyQuotaKnivesSnapshot clears the value of the "after_daily_quota_knives_snapshot" field.
func (_u *SubscriptionSettlementOrderUpdate) ClearAfterDailyQuotaKnivesSnapshot() *SubscriptionSettlementOrderUpdate {
	_u.mutation.ClearAfterDailyQuotaKnivesSnapshot()
	return _u
}

// SetAfterWeeklyQuotaKnivesSnapshot sets the "after_weekly_quota_knives_snapshot" field.
func (_u *SubscriptionSettlementOrderUpdate) SetAfterWeeklyQuotaKnivesSnapshot(v float64) *SubscriptionSettlementOrderUpdate {
	_u.mutation.ResetAfterWeeklyQuotaKnivesSnapshot()
	_u.mutation.SetAfterWeeklyQuotaKnivesSnapshot(v)
	return _u
}

// SetNillableAfterWeeklyQuotaKnivesSnapshot sets the "after_weekly_quota_knives_snapshot" field if the given value is not nil.
func (_u *SubscriptionSettlementOrderUpdate) SetNillableAfterWeeklyQuotaKnivesSnapshot(v *float64) *SubscriptionSettlementOrderUpdate {
	if v != nil {
		_u.SetAfterWeeklyQuotaKnivesSnapshot(*v)
	}
	return _u
}

// AddAfterWeeklyQuotaKnivesSnapshot adds value to the "after_weekly_quota_knives_snapshot" field.
func (_u *SubscriptionSettlementOrderUpdate) AddAfterWeeklyQuotaKnivesSnapshot(v float64) *SubscriptionSettlementOrderUpdate {
	_u.mutation.AddAfterWeeklyQuotaKnivesSnapshot(v)
	return _u
}

// ClearAfterWeeklyQuotaKnivesSnapshot clears the value of the "after_weekly_quota_knives_snapshot" field.
func (_u *SubscriptionSettlementOrderUpdate) ClearAfterWeeklyQuotaKnivesSnapshot() *SubscriptionSettlementOrderUpdate {
	_u.mutation.ClearAfterWeeklyQuotaKnivesSnapshot()
	return _u
}

// SetAfterMonthlyQuotaKnivesSnapshot sets the "after_monthly_quota_knives_snapshot" field.
func (_u *SubscriptionSettlementOrderUpdate) SetAfterMonthlyQuotaKnivesSnapshot(v float64) *SubscriptionSettlementOrderUpdate {
	_u.mutation.ResetAfterMonthlyQuotaKnivesSnapshot()
	_u.mutation.SetAfterMonthlyQuotaKnivesSnapshot(v)
	return _u
}

// SetNillableAfterMonthlyQuotaKnivesSnapshot sets the "after_monthly_quota_knives_snapshot" field if the given value is not nil.
func (_u *SubscriptionSettlementOrderUpdate) SetNillableAfterMonthlyQuotaKnivesSnapshot(v *float64) *SubscriptionSettlementOrderUpdate {
	if v != nil {
		_u.SetAfterMonthlyQuotaKnivesSnapshot(*v)
	}
	return _u
}

// AddAfterMonthlyQuotaKnivesSnapshot adds value to the "after_monthly_quota_knives_snapshot" field.
func (_u *SubscriptionSettlementOrderUpdate) AddAfterMonthlyQuotaKnivesSnapshot(v float64) *SubscriptionSettlementOrderUpdate {
	_u.mutation.AddAfterMonthlyQuotaKnivesSnapshot(v)
	return _u
}

// ClearAfterMonthlyQuotaKnivesSnapshot clears the value of the "after_monthly_quota_knives_snapshot" field.
func (_u *SubscriptionSettlementOrderUpdate) ClearAfterMonthlyQuotaKnivesSnapshot() *SubscriptionSettlementOrderUpdate {
	_u.mutation.ClearAfterMonthlyQuotaKnivesSnapshot()
	return _u
}

// SetAfterSubscriptionStatus sets the "after_subscription_status" field.
func (_u *SubscriptionSettlementOrderUpdate) SetAfterSubscriptionStatus(v string) *SubscriptionSettlementOrderUpdate {
	_u.mutation.SetAfterSubscriptionStatus(v)
	return _u
}

// SetNillableAfterSubscriptionStatus sets the "after_subscription_status" field if the given value is not nil.
func (_u *SubscriptionSettlementOrderUpdate) SetNillableAfterSubscriptionStatus(v *string) *SubscriptionSettlementOrderUpdate {
	if v != nil {
		_u.SetAfterSubscriptionStatus(*v)
	}
	return _u
}

// SetEffectiveAt sets the "effective_at" field.
func (_u *SubscriptionSettlementOrderUpdate) SetEffectiveAt(v time.Time) *SubscriptionSettlementOrderUpdate {
	_u.mutation.SetEffectiveAt(v)
	return _u
}

// SetNillableEffectiveAt sets the "effective_at" field if the given value is not nil.
func (_u *SubscriptionSettlementOrderUpdate) SetNillableEffectiveAt(v *time.Time) *SubscriptionSettlementOrderUpdate {
	if v != nil {
		_u.SetEffectiveAt(*v)
	}
	return _u
}

// SetClosedAt sets the "closed_at" field.
func (_u *SubscriptionSettlementOrderUpdate) SetClosedAt(v time.Time) *SubscriptionSettlementOrderUpdate {
	_u.mutation.SetClosedAt(v)
	return _u
}

// SetNillableClosedAt sets the "closed_at" field if the given value is not nil.
func (_u *SubscriptionSettlementOrderUpdate) SetNillableClosedAt(v *time.Time) *SubscriptionSettlementOrderUpdate {
	if v != nil {
		_u.SetClosedAt(*v)
	}
	return _u
}

// ClearClosedAt clears the value of the "closed_at" field.
func (_u *SubscriptionSettlementOrderUpdate) ClearClosedAt() *SubscriptionSettlementOrderUpdate {
	_u.mutation.ClearClosedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SubscriptionSettlementOrderUpdate) SetUpdatedAt(v time.Time) *SubscriptionSettlementOrderUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *SubscriptionSettlementOrderUpdate) SetUser(v *User) *SubscriptionSettlementOrderUpdate {
	return _u.SetUserID(v.ID)
}

// SetOperatorID sets the "operator" edge to the User entity by ID.
func (_u *SubscriptionSettlementOrderUpdate) SetOperatorID(id int64) *SubscriptionSettlementOrderUpdate {
	_u.mutation.SetOperatorID(id)
	return _u
}

// SetOperator sets the "operator" edge to the User entity.
func (_u *SubscriptionSettlementOrderUpdate) SetOperator(v *User) *SubscriptionSettlementOrderUpdate {
	return _u.SetOperatorID(v.ID)
}

// SetNextID sets the "next" edge to the SubscriptionSettlementOrder entity by ID.
func (_u *SubscriptionSettlementOrderUpdate) SetNextID(id int64) *SubscriptionSettlementOrderUpdate {
	_u.mutation.SetNextID(id)
	return _u
}

// SetNillableNextID sets the "next" edge to the SubscriptionSettlementOrder entity by ID if the given value is not nil.
func (_u *SubscriptionSettlementOrderUpdate) SetNillableNextID(id *int64) *SubscriptionSettlementOrderUpdate {
	if id != nil {
		_u = _u.SetNextID(*id)
	}
	return _u
}

// SetNext sets the "next" edge to the SubscriptionSettlementOrder entity.
func (_u *SubscriptionSettlementOrderUpdate) SetNext(v *SubscriptionSettlementOrder) *SubscriptionSettlementOrderUpdate {
	return _u.SetNextID(v.ID)
}

// SetPreviousID sets the "previous" edge to the SubscriptionSettlementOrder entity by ID.
func (_u *SubscriptionSettlementOrderUpdate) SetPreviousID(id int64) *SubscriptionSettlementOrderUpdate {
	_u.mutation.SetPreviousID(id)
	return _u
}

// SetNillablePreviousID sets the "previous" edge to the SubscriptionSettlementOrder entity by ID if the given value is not nil.
func (_u *SubscriptionSettlementOrderUpdate) SetNillablePreviousID(id *int64) *SubscriptionSettlementOrderUpdate {
	if id != nil {
		_u = _u.SetPreviousID(*id)
	}
	return _u
}

// SetPrevious sets the "previous" edge to the SubscriptionSettlementOrder entity.
func (_u *SubscriptionSettlementOrderUpdate) SetPrevious(v *SubscriptionSettlementOrder) *SubscriptionSettlementOrderUpdate {
	return _u.SetPreviousID(v.ID)
}

// SetAfterUserSubscription sets the "after_user_subscription" edge to the UserSubscription entity.
func (_u *SubscriptionSettlementOrderUpdate) SetAfterUserSubscription(v *UserSubscription) *SubscriptionSettlementOrderUpdate {
	return _u.SetAfterUserSubscriptionID(v.ID)
}

// SetAfterPlan sets the "after_plan" edge to the SubscriptionPlan entity.
func (_u *SubscriptionSettlementOrderUpdate) SetAfterPlan(v *SubscriptionPlan) *SubscriptionSettlementOrderUpdate {
	return _u.SetAfterPlanID(v.ID)
}

// Mutation returns the SubscriptionSettlementOrderMutation object of the builder.
func (_u *SubscriptionSettlementOrderUpdate) Mutation() *SubscriptionSettlementOrderMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *SubscriptionSettlementOrderUpdate) ClearUser() *SubscriptionSettlementOrderUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearOperator clears the "operator" edge to the User entity.
func (_u *SubscriptionSettlementOrderUpdate) ClearOperator() *SubscriptionSettlementOrderUpdate {
	_u.mutation.ClearOperator()
	return _u
}

// ClearNext clears the "next" edge to the SubscriptionSettlementOrder entity.
func (_u *SubscriptionSettlementOrderUpdate) ClearNext() *SubscriptionSettlementOrderUpdate {
	_u.mutation.ClearNext()
	return _u
}

// ClearPrevious clears the "previous" edge to the SubscriptionSettlementOrder entity.
func (_u *SubscriptionSettlementOrderUpdate) ClearPrevious() *SubscriptionSettlementOrderUpdate {
	_u.mutation.ClearPrevious()
	return _u
}

// ClearAfterUserSubscription clears the "after_user_subscription" edge to the UserSubscription entity.
func (_u *SubscriptionSettlementOrderUpdate) ClearAfterUserSubscription() *SubscriptionSettlementOrderUpdate {
	_u.mutation.ClearAfterUserSubscription()
	return _u
}

// ClearAfterPlan clears the "after_plan" edge to the SubscriptionPlan entity.
func (_u *SubscriptionSettlementOrderUpdate) ClearAfterPlan() *SubscriptionSettlementOrderUpdate {
	_u.mutation.ClearAfterPlan()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SubscriptionSettlementOrderUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionSettlementOrderUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SubscriptionSettlementOrderUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionSettlementOrderUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SubscriptionSettlementOrderUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := subscriptionsettlementorder.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubscriptionSettlementOrderUpdate) check() error {
	if v, ok := _u.mutation.ActionType(); ok {
		if err := subscriptionsettlementorder.ActionTypeValidator(v); err != nil {
			return &ValidationError{Name: "action_type", err: fmt.Errorf(`ent: validator failed for field "SubscriptionSettlementOrder.action_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ActionSource(); ok {
		if err := subscriptionsettlementorder.ActionSourceValidator(v); err != nil {
			return &ValidationError{Name: "action_source", err: fmt.Errorf(`ent: validator failed for field "SubscriptionSettlementOrder.action_source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := subscriptionsettlementorder.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SubscriptionSettlementOrder.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TriggerRefType(); ok {
		if err := subscriptionsettlementorder.TriggerRefTypeValidator(v); err != nil {
			return &ValidationError{Name: "trigger_ref_type", err: fmt.Errorf(`ent: validator failed for field "SubscriptionSettlementOrder.trigger_ref_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AfterPlanNameSnapshot(); ok {
		if err := subscriptionsettlementorder.AfterPlanNameSnapshotValidator(v); err != nil {
			return &ValidationError{Name: "after_plan_name_snapshot", err: fmt.Errorf(`ent: validator failed for field "SubscriptionSettlementOrder.after_plan_name_snapshot": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AfterValidityUnitSnapshot(); ok {
		if err := subscriptionsettlementorder.AfterValidityUnitSnapshotValidator(v); err != nil {
			return &ValidationError{Name: "after_validity_unit_snapshot", err: fmt.Errorf(`ent: validator failed for field "SubscriptionSettlementOrder.after_validity_unit_snapshot": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AfterSubscriptionStatus(); ok {
		if err := subscriptionsettlementorder.AfterSubscriptionStatusValidator(v); err != nil {
			return &ValidationError{Name: "after_subscription_status", err: fmt.Errorf(`ent: validator failed for field "SubscriptionSettlementOrder.after_subscription_status": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubscriptionSettlementOrder.user"`)
	}
	if _u.mutation.OperatorCleared() && len(_u.mutation.OperatorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubscriptionSettlementOrder.operator"`)
	}
	return nil
}

func (_u *SubscriptionSettlementOrderUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscriptionsettlementorder.Table, subscriptionsettlementorder.Columns, sqlgraph.NewFieldSpec(subscriptionsettlementorder.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ActionType(); ok {
		_spec.SetField(subscriptionsettlementorder.FieldActionType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ActionSource(); ok {
		_spec.SetField(subscriptionsettlementorder.FieldActionSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(subscriptionsettlementorder.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.TriggerRefType(); ok {
		_spec.SetField(subscriptionsettlementorder.FieldTriggerRefType, field.TypeString, value)
	}
	if value, ok := _u.mutation.TriggerRefID(); ok {
		_spec.SetField(subscriptionsettlementorder.FieldTriggerRefID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTriggerRefID(); ok {
		_spec.AddField(subscriptionsettlementorder.FieldTriggerRefID, field.TypeInt64, value)
	}
	if _u.mutation.TriggerRefIDCleared() {
		_spec.ClearField(subscriptionsettlementorder.FieldTriggerRefID, field.TypeInt64)
	}
	if value, ok := _u.mutation.ActionNote(); ok {
		_spec.SetField(subscriptionsettlementorder.FieldActionNote, field.TypeString, value)
	}
	if _u.mutation.ActionNoteCleared() {
		_spec.ClearField(subscriptionsettlementorder.FieldActionNote, field.TypeString)
	}
	if value, ok := _u.mutation.CarryInResidualValue(); ok {
		_spec.SetField(subscriptionsettlementorder.FieldCarryInResidualValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCarryInResidualValue(); ok {
		_spec.AddField(subscriptionsettlementorder.FieldCarryInResidualValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ActionDeltaValue(); ok {
		_spec.SetField(subscriptionsettlementorder.FieldActionDeltaValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedActionDeltaValue(); ok {
		_spec.AddField(subscriptionsettlementorder.FieldActionDeltaValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AfterSettlementValue(); ok {
		_spec.SetField(subscriptionsettlementorder.FieldAfterSettlementValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAfterSettlementValue(); ok {
		_spec.AddField(subscriptionsettlementorder.FieldAfterSettlementValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RefundResidualValue(); ok {
		_spec.SetField(subscriptionsettlementorder.FieldRefundResidualValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRefundResidualValue(); ok {
		_spec.AddField(subscriptionsettlementorder.FieldRefundResidualValue, field.TypeFloat64, value)
	}
	if _u.mutation.RefundResidualValueCleared() {
		_spec.ClearField(subscriptionsettlementorder.FieldRefundResidualValue, field.TypeFloat64)
	}
	if value, ok := _u.mutation.WriteoffValue(); ok {
		_spec.SetField(subscriptionsettlementorder.FieldWriteoffValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedWriteoffValue(); ok {
		_spec.AddField(subscriptionsettlementorder.FieldWriteoffValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AfterPlanNameSnapshot(); ok {
		_spec.SetField(subscriptionsettlementorder.FieldAfterPlanNameSnapshot, field.TypeString, value)
	}
	if _u.mutation.AfterPlanNameSnapshotCleared() {
		_spec.ClearField(subscriptionsettlementorder.FieldAfterPlanNameSnapshot, field.TypeString)
	}
	if value, ok := _u.mutation.AfterPlanPriceSnapshot(); ok {
		_spec.SetField(subscriptionsettlementorder.FieldAfterPlanPriceSnapshot, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAfterPlanPriceSnapshot(); ok {
		_spec.AddField(subscriptionsettlementorder.FieldAfterPlanPriceSnapshot, field.TypeFloat64, value)
	}
	if _u.mutation.AfterPlanPriceSnapshotCleared() {
		_spec.ClearField(subscriptionsettlementorder.FieldAfterPlanPriceSnapshot, field.TypeFloat64)
	}
	if value, ok := _u.mutation.AfterValidityDaysSnapshot(); ok {
		_spec.SetField(subscriptionsettlementorder.FieldAfterValidityDaysSnapshot, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAfterValidityDaysSnapshot(); ok {
		_spec.AddField(subscriptionsettlementorder.FieldAfterValidityDaysSnapshot, field.TypeInt, value)
	}
	if _u.mutation.AfterValidityDaysSnapshotCleared() {
		_spec.ClearField(subscriptionsettlementorder.FieldAfterValidityDaysSnapshot, field.TypeInt)
	}
	if value, ok := _u.mutation.AfterValidityUnitSnapshot(); ok {
		_spec.SetField(subscriptionsettlementorder.FieldAfterValidityUnitSnapshot, field.TypeString, value)
	}
	if _u.mutation.AfterValidityUnitSnapshotCleared() {
		_spec.ClearField(subscriptionsettlementorder.FieldAfterValidityUnitSnapshot, field.TypeString)
	}
	if value, ok := _u.mutation.AfterStartsAt(); ok {
		_spec.SetField(subscriptionsettlementorder.FieldAfterStartsAt, field.TypeTime, value)
	}
	if _u.mutation.AfterStartsAtCleared() {
		_spec.ClearField(subscriptionsettlementorder.FieldAfterStartsAt, field.TypeTime)
	}
	if value, ok := _u.mutation.AfterExpiresAt(); ok {
		_spec.SetField(subscriptionsettlementorder.FieldAfterExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.AfterExpiresAtCleared() {
		_spec.ClearField(subscriptionsettlementorder.FieldAfterExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.AfterDailyQuotaKnivesSnapshot(); ok {
		_spec.SetField(subscriptionsettlementorder.FieldAfterDailyQuotaKnivesSnapshot, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAfterDailyQuotaKnivesSnapshot(); ok {
		_spec.AddField(subscriptionsettlementorder.FieldAfterDailyQuotaKnivesSnapshot, field.TypeFloat64, value)
	}
	if _u.mutation.AfterDailyQuotaKnivesSnapshotCleared() {
		_spec.ClearField(subscriptionsettlementorder.FieldAfterDailyQuotaKnivesSnapshot, field.TypeFloat64)
	}
	if value, ok := _u.mutation.AfterWeeklyQuotaKnivesSnapshot(); ok {
		_spec.SetField(subscriptionsettlementorder.FieldAfterWeeklyQuotaKnivesSnapshot, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAfterWeeklyQuotaKnivesSnapshot(); ok {
		_spec.AddField(subscriptionsettlementorder.FieldAfterWeeklyQuotaKnivesSnapshot, field.TypeFloat64, value)
	}
	if _u.mutation.AfterWeeklyQuotaKnivesSnapshotCleared() {
		_spec.ClearField(subscriptionsettlementorder.FieldAfterWeeklyQuotaKnivesSnapshot, field.TypeFloat64)
	}
	if value, ok := _u.mutation.AfterMonthlyQuotaKnivesSnapshot(); ok {
		_spec.SetField(subscriptionsettlementorder.FieldAfterMonthlyQuotaKnivesSnapshot, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAfterMonthlyQuotaKnivesSnapshot(); ok {
		_spec.AddField(subscriptionsettlementorder.FieldAfterMonthlyQuotaKnivesSnapshot, field.TypeFloat64, value)
	}
	if _u.mutation.AfterMonthlyQuotaKnivesSnapshotCleared() {
		_spec.ClearField(subscriptionsettlementorder.FieldAfterMonthlyQuotaKnivesSnapshot, field.TypeFloat64)
	}
	if value, ok := _u.mutation.AfterSubscriptionStatus(); ok {
		_spec.SetField(subscriptionsettlementorder.FieldAfterSubscriptionStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.EffectiveAt(); ok {
		_spec.SetField(subscriptionsettlementorder.FieldEffectiveAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ClosedAt(); ok {
		_spec.SetField(subscriptionsettlementorder.FieldClosedAt, field.TypeTime, value)
	}
	if _u.mutation.ClosedAtCleared() {
		_spec.ClearField(subscriptionsettlementorder.FieldClosedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(subscriptionsettlementorder.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionsettlementorder.UserTable,
			Columns: []string{subscriptionsettlementorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionsettlementorder.UserTable,
			Columns: []string{subscriptionsettlementorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OperatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionsettlementorder.OperatorTable,
			Columns: []string{subscriptionsettlementorder.OperatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OperatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionsettlementorder.OperatorTable,
			Columns: []string{subscriptionsettlementorder.OperatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.NextCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   subscriptionsettlementorder.NextTable,
			Columns: []string{subscriptionsettlementorder.NextColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionsettlementorder.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.NextIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   subscriptionsettlementorder.NextTable,
			Columns: []string{subscriptionsettlementorder.NextColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionsettlementorder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PreviousCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   subscriptionsettlementorder.PreviousTable,
			Columns: []string{subscriptionsettlementorder.PreviousColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionsettlementorder.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PreviousIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   subscriptionsettlementorder.PreviousTable,
			Columns: []string{subscriptionsettlementorder.PreviousColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionsettlementorder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AfterUserSubscriptionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionsettlementorder.AfterUserSubscriptionTable,
			Columns: []string{subscriptionsettlementorder.AfterUserSubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AfterUserSubscriptionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionsettlementorder.AfterUserSubscriptionTable,
			Columns: []string{subscriptionsettlementorder.AfterUserSubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AfterPlanCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionsettlementorder.AfterPlanTable,
			Columns: []string{subscriptionsettlementorder.AfterPlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionplan.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AfterPlanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionsettlementorder.AfterPlanTable,
			Columns: []string{subscriptionsettlementorder.AfterPlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionplan.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscriptionsettlementorder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SubscriptionSettlementOrderUpdateOne is the builder for updating a single SubscriptionSettlementOrder entity.
type SubscriptionSettlementOrderUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SubscriptionSettlementOrderMutation
}

// SetUserID sets the "user_id" field.
func (_u *SubscriptionSettlementOrderUpdateOne) SetUserID(v int64) *SubscriptionSettlementOrderUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SubscriptionSettlementOrderUpdateOne) SetNillableUserID(v *int64) *SubscriptionSettlementOrderUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetPrevSettlementID sets the "prev_settlement_id" field.
func (_u *SubscriptionSettlementOrderUpdateOne) SetPrevSettlementID(v int64) *SubscriptionSettlementOrderUpdateOne {
	_u.mutation.SetPrevSettlementID(v)
	return _u
}

// SetNillablePrevSettlementID sets the "prev_settlement_id" field if the given value is not nil.
func (_u *SubscriptionSettlementOrderUpdateOne) SetNillablePrevSettlementID(v *int64) *SubscriptionSettlementOrderUpdateOne {
	if v != nil {
		_u.SetPrevSettlementID(*v)
	}
	return _u
}

// ClearPrevSettlementID clears the value of the "prev_settlement_id" field.
func (_u *SubscriptionSettlementOrderUpdateOne) ClearPrevSettlementID() *SubscriptionSettlementOrderUpdateOne {
	_u.mutation.ClearPrevSettlementID()
	return _u
}

// SetActionType sets the "action_type" field.
func (_u *SubscriptionSettlementOrderUpdateOne) SetActionType(v string) *SubscriptionSettlementOrderUpdateOne {
	_u.mutation.SetActionType(v)
	return _u
}

// SetNillableActionType sets the "action_type" field if the given value is not nil.
func (_u *SubscriptionSettlementOrderUpdateOne) SetNillableActionType(v *string) *SubscriptionSettlementOrderUpdateOne {
	if v != nil {
		_u.SetActionType(*v)
	}
	return _u
}

// SetActionSource sets the "action_source" field.
func (_u *SubscriptionSettlementOrderUpdateOne) SetActionSource(v string) *SubscriptionSettlementOrderUpdateOne {
	_u.mutation.SetActionSource(v)
	return _u
}

// SetNillableActionSource sets the "action_source" field if the given value is not nil.
func (_u *SubscriptionSettlementOrderUpdateOne) SetNillableActionSource(v *string) *SubscriptionSettlementOrderUpdateOne {
	if v != nil {
		_u.SetActionSource(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SubscriptionSettlementOrderUpdateOne) SetStatus(v string) *SubscriptionSettlementOrderUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SubscriptionSettlementOrderUpdateOne) SetNillableStatus(v *string) *SubscriptionSettlementOrderUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetTriggerRefType sets the "trigger_ref_type" field.
func (_u *SubscriptionSettlementOrderUpdateOne) SetTriggerRefType(v string) *SubscriptionSettlementOrderUpdateOne {
	_u.mutation.SetTriggerRefType(v)
	return _u
}

// SetNillableTriggerRefType sets the "trigger_ref_type" field if the given value is not nil.
func (_u *SubscriptionSettlementOrderUpdateOne) SetNillableTriggerRefType(v *string) *SubscriptionSettlementOrderUpdateOne {
	if v != nil {
		_u.SetTriggerRefType(*v)
	}
	return _u
}

// SetTriggerRefID sets the "trigger_ref_id" field.
func (_u *SubscriptionSettlementOrderUpdateOne) SetTriggerRefID(v int64) *SubscriptionSettlementOrderUpdateOne {
	_u.mutation.ResetTriggerRefID()
	_u.mutation.SetTriggerRefID(v)
	return _u
}

// SetNillableTriggerRefID sets the "trigger_ref_id" field if the given value is not nil.
func (_u *SubscriptionSettlementOrderUpdateOne) SetNillableTriggerRefID(v *int64) *SubscriptionSettlementOrderUpdateOne {
	if v != nil {
		_u.SetTriggerRefID(*v)
	}
	return _u
}

// AddTriggerRefID adds value to the "trigger_ref_id" field.
func (_u *SubscriptionSettlementOrderUpdateOne) AddTriggerRefID(v int64) *SubscriptionSettlementOrderUpdateOne {
	_u.mutation.AddTriggerRefID(v)
	return _u
}

// ClearTriggerRefID clears the value of the "trigger_ref_id" field.
func (_u *SubscriptionSettlementOrderUpdateOne) ClearTriggerRefID() *SubscriptionSettlementOrderUpdateOne {
	_u.mutation.ClearTriggerRefID()
	return _u
}

// SetOperatorUserID sets the "operator_user_id" field.
func (_u *SubscriptionSettlementOrderUpdateOne) SetOperatorUserID(v int64) *SubscriptionSettlementOrderUpdateOne {
	_u.mutation.SetOperatorUserID(v)
	return _u
}

// SetNillableOperatorUserID sets the "operator_user_id" field if the given value is not nil.
func (_u *SubscriptionSettlementOrderUpdateOne) SetNillableOperatorUserID(v *int64) *SubscriptionSettlementOrderUpdateOne {
	if v != nil {
		_u.SetOperatorUserID(*v)
	}
	return _u
}

// SetActionNote sets the "action_note" field.
func (_u *SubscriptionSettlementOrderUpdateOne) SetActionNote(v string) *SubscriptionSettlementOrderUpdateOne {
	_u.mutation.SetActionNote(v)
	return _u
}

// SetNillableActionNote sets the "action_note" field if the given value is not nil.
func (_u *SubscriptionSettlementOrderUpdateOne) SetNillableActionNote(v *string) *SubscriptionSettlementOrderUpdateOne {
	if v != nil {
		_u.SetActionNote(*v)
	}
	return _u
}

// ClearActionNote clears the value of the "action_note" field.
func (_u *SubscriptionSettlementOrderUpdateOne) ClearActionNote() *SubscriptionSettlementOrderUpdateOne {
	_u.mutation.ClearActionNote()
	return _u
}

// SetCarryInResidualValue sets the "carry_in_residual_value" field.
func (_u *SubscriptionSettlementOrderUpdateOne) SetCarryInResidualValue(v float64) *SubscriptionSettlementOrderUpdateOne {
	_u.mutation.ResetCarryInResidualValue()
	_u.mutation.SetCarryInResidualValue(v)
	return _u
}

// SetNillableCarryInResidualValue sets the "carry_in_residual_value" field if the given value is not nil.
func (_u *SubscriptionSettlementOrderUpdateOne) SetNillableCarryInResidualValue(v *float64) *SubscriptionSettlementOrderUpdateOne {
	if v != nil {
		_u.SetCarryInResidualValue(*v)
	}
	return _u
}

// AddCarryInResidualValue adds value to the "carry_in_residual_value" field.
func (_u *SubscriptionSettlementOrderUpdateOne) AddCarryInResidualValue(v float64) *SubscriptionSettlementOrderUpdateOne {
	_u.mutation.AddCarryInResidualValue(v)
	return _u
}

// SetActionDeltaValue sets the "action_delta_value" field.
func (_u *SubscriptionSettlementOrderUpdateOne) SetActionDeltaValue(v float64) *SubscriptionSettlementOrderUpdateOne {
	_u.mutation.ResetActionDeltaValue()
	_u.mutation.SetActionDeltaValue(v)
	return _u
}

// SetNillableActionDeltaValue sets the "action_delta_value" field if the given value is not nil.
func (_u *SubscriptionSettlementOrderUpdateOne) SetNillableActionDeltaValue(v *float64) *SubscriptionSettlementOrderUpdateOne {
	if v != nil {
		_u.SetActionDeltaValue(*v)
	}
	return _u
}

// AddActionDeltaValue adds value to the "action_delta_value" field.
func (_u *SubscriptionSettlementOrderUpdateOne) AddActionDeltaValue(v float64) *SubscriptionSettlementOrderUpdateOne {
	_u.mutation.AddActionDeltaValue(v)
	return _u
}

// SetAfterSettlementValue sets the "after_settlement_value" field.
func (_u *SubscriptionSettlementOrderUpdateOne) SetAfterSettlementValue(v float64) *SubscriptionSettlementOrderUpdateOne {
	_u.mutation.ResetAfterSettlementValue()
	_u.mutation.SetAfterSettlementValue(v)
	return _u
}

// SetNillableAfterSettlementValue sets the "after_settlement_value" field if the given value is not nil.
func (_u *SubscriptionSettlementOrderUpdateOne) SetNillableAfterSettlementValue(v *float64) *SubscriptionSettlementOrderUpdateOne {
	if v != nil {
		_u.SetAfterSettlementValue(*v)
	}
	return _u
}

// AddAfterSettlementValue adds value to the "after_settlement_value" field.
func (_u *SubscriptionSettlementOrderUpdateOne) AddAfterSettlementValue(v float64) *SubscriptionSettlementOrderUpdateOne {
	_u.mutation.AddAfterSettlementValue(v)
	return _u
}

// SetRefundResidualValue sets the "refund_residual_value" field.
func (_u *SubscriptionSettlementOrderUpdateOne) SetRefundResidualValue(v float64) *SubscriptionSettlementOrderUpdateOne {
	_u.mutation.ResetRefundResidualValue()
	_u.mutation.SetRefundResidualValue(v)
	return _u
}

// SetNillableRefundResidualValue sets the "refund_residual_value" field if the given value is not nil.
func (_u *SubscriptionSettlementOrderUpdateOne) SetNillableRefundResidualValue(v *float64) *SubscriptionSettlementOrderUpdateOne {
	if v != nil {
		_u.SetRefundResidualValue(*v)
	}
	return _u
}

// AddRefundResidualValue adds value to the "refund_residual_value" field.
func (_u *SubscriptionSettlementOrderUpdateOne) AddRefundResidualValue(v float64) *SubscriptionSettlementOrderUpdateOne {
	_u.mutation.AddRefundResidualValue(v)
	return _u
}

// ClearRefundResidualValue clears the value of the "refund_residual_value" field.
func (_u *SubscriptionSettlementOrderUpdateOne) ClearRefundResidualValue() *SubscriptionSettlementOrderUpdateOne {
	_u.mutation.ClearRefundResidualValue()
	return _u
}

// SetWriteoffValue sets the "writeoff_value" field.
func (_u *SubscriptionSettlementOrderUpdateOne) SetWriteoffValue(v float64) *SubscriptionSettlementOrderUpdateOne {
	_u.mutation.ResetWriteoffValue()
	_u.mutation.SetWriteoffValue(v)
	return _u
}

// SetNillableWriteoffValue sets the "writeoff_value" field if the given value is not nil.
func (_u *SubscriptionSettlementOrderUpdateOne) SetNillableWriteoffValue(v *float64) *SubscriptionSettlementOrderUpdateOne {
	if v != nil {
		_u.SetWriteoffValue(*v)
	}
	return _u
}

// AddWriteoffValue adds value to the "writeoff_value" field.
func (_u *SubscriptionSettlementOrderUpdateOne) AddWriteoffValue(v float64) *SubscriptionSettlementOrderUpdateOne {
	_u.mutation.AddWriteoffValue(v)
	return _u
}

// SetAfterUserSubscriptionID sets the "after_user_subscription_id" field.
func (_u *SubscriptionSettlementOrderUpdateOne) SetAfterUserSubscriptionID(v int64) *SubscriptionSettlementOrderUpdateOne {
	_u.mutation.SetAfterUserSubscriptionID(v)
	return _u
}

// SetNillableAfterUserSubscriptionID sets the "after_user_subscription_id" field if the given value is not nil.
func (_u *SubscriptionSettlementOrderUpdateOne) SetNillableAfterUserSubscriptionID(v *int64) *SubscriptionSettlementOrderUpdateOne {
	if v != nil {
		_u.SetAfterUserSubscriptionID(*v)
	}
	return _u
}

// ClearAfterUserSubscriptionID clears the value of the "after_user_subscription_id" field.
func (_u *SubscriptionSettlementOrderUpdateOne) ClearAfterUserSubscriptionID() *SubscriptionSettlementOrderUpdateOne {
	_u.mutation.ClearAfterUserSubscriptionID()
	return _u
}

// SetAfterPlanID sets the "after_plan_id" field.
func (_u *SubscriptionSettlementOrderUpdateOne) SetAfterPlanID(v int64) *SubscriptionSettlementOrderUpdateOne {
	_u.mutation.SetAfterPlanID(v)
	return _u
}

// SetNillableAfterPlanID sets the "after_plan_id" field if the given value is not nil.
func (_u *SubscriptionSettlementOrderUpdateOne) SetNillableAfterPlanID(v *int64) *SubscriptionSettlementOrderUpdateOne {
	if v != nil {
		_u.SetAfterPlanID(*v)
	}
	return _u
}

// ClearAfterPlanID clears the value of the "after_plan_id" field.
func (_u *SubscriptionSettlementOrderUpdateOne) ClearAfterPlanID() *SubscriptionSettlementOrderUpdateOne {
	_u.mutation.ClearAfterPlanID()
	return _u
}

// SetAfterPlanNameSnapshot sets the "after_plan_name_snapshot" field.
func (_u *SubscriptionSettlementOrderUpdateOne) SetAfterPlanNameSnapshot(v string) *SubscriptionSettlementOrderUpdateOne {
	_u.mutation.SetAfterPlanNameSnapshot(v)
	return _u
}

// SetNillableAfterPlanNameSnapshot sets the "after_plan_name_snapshot" field if the given value is not nil.
func (_u *SubscriptionSettlementOrderUpdateOne) SetNillableAfterPlanNameSnapshot(v *string) *SubscriptionSettlementOrderUpdateOne {
	if v != nil {
		_u.SetAfterPlanNameSnapshot(*v)
	}
	return _u
}

// ClearAfterPlanNameSnapshot clears the value of the "after_plan_name_snapshot" field.
func (_u *SubscriptionSettlementOrderUpdateOne) ClearAfterPlanNameSnapshot() *SubscriptionSettlementOrderUpdateOne {
	_u.mutation.ClearAfterPlanNameSnapshot()
	return _u
}

// SetAfterPlanPriceSnapshot sets the "after_plan_price_snapshot" field.
func (_u *SubscriptionSettlementOrderUpdateOne) SetAfterPlanPriceSnapshot(v float64) *SubscriptionSettlementOrderUpdateOne {
	_u.mutation.ResetAfterPlanPriceSnapshot()
	_u.mutation.SetAfterPlanPriceSnapshot(v)
	return _u
}

// SetNillableAfterPlanPriceSnapshot sets the "after_plan_price_snapshot" field if the given value is not nil.
func (_u *SubscriptionSettlementOrderUpdateOne) SetNillableAfterPlanPriceSnapshot(v *float64) *SubscriptionSettlementOrderUpdateOne {
	if v != nil {
		_u.SetAfterPlanPriceSnapshot(*v)
	}
	return _u
}

// AddAfterPlanPriceSnapshot adds value to the "after_plan_price_snapshot" field.
func (_u *SubscriptionSettlementOrderUpdateOne) AddAfterPlanPriceSnapshot(v float64) *SubscriptionSettlementOrderUpdateOne {
	_u.mutation.AddAfterPlanPriceSnapshot(v)
	return _u
}

// ClearAfterPlanPriceSnapshot clears the value of the "after_plan_price_snapshot" field.
func (_u *SubscriptionSettlementOrderUpdateOne) ClearAfterPlanPriceSnapshot() *SubscriptionSettlementOrderUpdateOne {
	_u.mutation.ClearAfterPlanPriceSnapshot()
	return _u
}

// SetAfterValidityDaysSnapshot sets the "after_validity_days_snapshot" field.
func (_u *SubscriptionSettlementOrderUpdateOne) SetAfterValidityDaysSnapshot(v int) *SubscriptionSettlementOrderUpdateOne {
	_u.mutation.ResetAfterValidityDaysSnapshot()
	_u.mutation.SetAfterValidityDaysSnapshot(v)
	return _u
}

// SetNillableAfterValidityDaysSnapshot sets the "after_validity_days_snapshot" field if the given value is not nil.
func (_u *SubscriptionSettlementOrderUpdateOne) SetNillableAfterValidityDaysSnapshot(v *int) *SubscriptionSettlementOrderUpdateOne {
	if v != nil {
		_u.SetAfterValidityDaysSnapshot(*v)
	}
	return _u
}

// AddAfterValidityDaysSnapshot adds value to the "after_validity_days_snapshot" field.
func (_u *SubscriptionSettlementOrderUpdateOne) AddAfterValidityDaysSnapshot(v int) *SubscriptionSettlementOrderUpdateOne {
	_u.mutation.AddAfterValidityDaysSnapshot(v)
	return _u
}

// ClearAfterValidityDaysSnapshot clears the value of the "after_validity_days_snapshot" field.
func (_u *SubscriptionSettlementOrderUpdateOne) ClearAfterValidityDaysSnapshot() *SubscriptionSettlementOrderUpdateOne {
	_u.mutation.ClearAfterValidityDaysSnapshot()
	return _u
}

// SetAfterValidityUnitSnapshot sets the "after_validity_unit_snapshot" field.
func (_u *SubscriptionSettlementOrderUpdateOne) SetAfterValidityUnitSnapshot(v string) *SubscriptionSettlementOrderUpdateOne {
	_u.mutation.SetAfterValidityUnitSnapshot(v)
	return _u
}

// SetNillableAfterValidityUnitSnapshot sets the "after_validity_unit_snapshot" field if the given value is not nil.
func (_u *SubscriptionSettlementOrderUpdateOne) SetNillableAfterValidityUnitSnapshot(v *string) *SubscriptionSettlementOrderUpdateOne {
	if v != nil {
		_u.SetAfterValidityUnitSnapshot(*v)
	}
	return _u
}

// ClearAfterValidityUnitSnapshot clears the value of the "after_validity_unit_snapshot" field.
func (_u *SubscriptionSettlementOrderUpdateOne) ClearAfterValidityUnitSnapshot() *SubscriptionSettlementOrderUpdateOne {
	_u.mutation.ClearAfterValidityUnitSnapshot()
	return _u
}

// SetAfterStartsAt sets the "after_starts_at" field.
func (_u *SubscriptionSettlementOrderUpdateOne) SetAfterStartsAt(v time.Time) *SubscriptionSettlementOrderUpdateOne {
	_u.mutation.SetAfterStartsAt(v)
	return _u
}

// SetNillableAfterStartsAt sets the "after_starts_at" field if the given value is not nil.
func (_u *SubscriptionSettlementOrderUpdateOne) SetNillableAfterStartsAt(v *time.Time) *SubscriptionSettlementOrderUpdateOne {
	if v != nil {
		_u.SetAfterStartsAt(*v)
	}
	return _u
}

// ClearAfterStartsAt clears the value of the "after_starts_at" field.
func (_u *SubscriptionSettlementOrderUpdateOne) ClearAfterStartsAt() *SubscriptionSettlementOrderUpdateOne {
	_u.mutation.ClearAfterStartsAt()
	return _u
}

// SetAfterExpiresAt sets the "after_expires_at" field.
func (_u *SubscriptionSettlementOrderUpdateOne) SetAfterExpiresAt(v time.Time) *SubscriptionSettlementOrderUpdateOne {
	_u.mutation.SetAfterExpiresAt(v)
	return _u
}

// SetNillableAfterExpiresAt sets the "after_expires_at" field if the given value is not nil.
func (_u *SubscriptionSettlementOrderUpdateOne) SetNillableAfterExpiresAt(v *time.Time) *SubscriptionSettlementOrderUpdateOne {
	if v != nil {
		_u.SetAfterExpiresAt(*v)
	}
	return _u
}

// ClearAfterExpiresAt clears the value of the "after_expires_at" field.
func (_u *SubscriptionSettlementOrderUpdateOne) ClearAfterExpiresAt() *SubscriptionSettlementOrderUpdateOne {
	_u.mutation.ClearAfterExpiresAt()
	return _u
}

// SetAfterDailyQuotaKnivesSnapshot sets the "after_daily_quota_knives_snapshot" field.
func (_u *SubscriptionSettlementOrderUpdateOne) SetAfterDailyQuotaKnivesSnapshot(v float64) *SubscriptionSettlementOrderUpdateOne {
	_u.mutation.ResetAfterDailyQuotaKnivesSnapshot()
	_u.mutation.SetAfterDailyQuotaKnivesSnapshot(v)
	return _u
}

// SetNillableAfterDailyQuotaKnivesSnapshot sets the "after_daily_quota_knives_snapshot" field if the given value is not nil.
func (_u *SubscriptionSettlementOrderUpdateOne) SetNillableAfterDailyQuotaKnivesSnapshot(v *float64) *SubscriptionSettlementOrderUpdateOne {
	if v != nil {
		_u.SetAfterDailyQuotaKnivesSnapshot(*v)
	}
	return _u
}

// AddAfterDailyQuotaKnivesSnapshot adds value to the "after_daily_quota_knives_snapshot" field.
func (_u *SubscriptionSettlementOrderUpdateOne) AddAfterDailyQuotaKnivesSnapshot(v float64) *SubscriptionSettlementOrderUpdateOne {
	_u.mutation.AddAfterDailyQuotaKnivesSnapshot(v)
	return _u
}

// ClearAfterDailyQuotaKnivesSnapshot clears the value of the "after_daily_quota_knives_snapshot" field.
func (_u *SubscriptionSettlementOrderUpdateOne) ClearAfterDailyQuotaKnivesSnapshot() *SubscriptionSettlementOrderUpdateOne {
	_u.mutation.ClearAfterDailyQuotaKnivesSnapshot()
	return _u
}

// SetAfterWeeklyQuotaKnivesSnapshot sets the "after_weekly_quota_knives_snapshot" field.
func (_u *SubscriptionSettlementOrderUpdateOne) SetAfterWeeklyQuotaKnivesSnapshot(v float64) *SubscriptionSettlementOrderUpdateOne {
	_u.mutation.ResetAfterWeeklyQuotaKnivesSnapshot()
	_u.mutation.SetAfterWeeklyQuotaKnivesSnapshot(v)
	return _u
}

// SetNillableAfterWeeklyQuotaKnivesSnapshot sets the "after_weekly_quota_knives_snapshot" field if the given value is not nil.
func (_u *SubscriptionSettlementOrderUpdateOne) SetNillableAfterWeeklyQuotaKnivesSnapshot(v *float64) *SubscriptionSettlementOrderUpdateOne {
	if v != nil {
		_u.SetAfterWeeklyQuotaKnivesSnapshot(*v)
	}
	return _u
}

// AddAfterWeeklyQuotaKnivesSnapshot adds value to the "after_weekly_quota_knives_snapshot" field.
func (_u *SubscriptionSettlementOrderUpdateOne) AddAfterWeeklyQuotaKnivesSnapshot(v float64) *SubscriptionSettlementOrderUpdateOne {
	_u.mutation.AddAfterWeeklyQuotaKnivesSnapshot(v)
	return _u
}

// ClearAfterWeeklyQuotaKnivesSnapshot clears the value of the "after_weekly_quota_knives_snapshot" field.
func (_u *SubscriptionSettlementOrderUpdateOne) ClearAfterWeeklyQuotaKnivesSnapshot() *SubscriptionSettlementOrderUpdateOne {
	_u.mutation.ClearAfterWeeklyQuotaKnivesSnapshot()
	return _u
}

// SetAfterMonthlyQuotaKnivesSnapshot sets the "after_monthly_quota_knives_snapshot" field.
func (_u *SubscriptionSettlementOrderUpdateOne) SetAfterMonthlyQuotaKnivesSnapshot(v float64) *SubscriptionSettlementOrderUpdateOne {
	_u.mutation.ResetAfterMonthlyQuotaKnivesSnapshot()
	_u.mutation.SetAfterMonthlyQuotaKnivesSnapshot(v)
	return _u
}

// SetNillableAfterMonthlyQuotaKnivesSnapshot sets the "after_monthly_quota_knives_snapshot" field if the given value is not nil.
func (_u *SubscriptionSettlementOrderUpdateOne) SetNillableAfterMonthlyQuotaKnivesSnapshot(v *float64) *SubscriptionSettlementOrderUpdateOne {
	if v != nil {
		_u.SetAfterMonthlyQuotaKnivesSnapshot(*v)
	}
	return _u
}

// AddAfterMonthlyQuotaKnivesSnapshot adds value to the "after_monthly_quota_knives_snapshot" field.
func (_u *SubscriptionSettlementOrderUpdateOne) AddAfterMonthlyQuotaKnivesSnapshot(v float64) *SubscriptionSettlementOrderUpdateOne {
	_u.mutation.AddAfterMonthlyQuotaKnivesSnapshot(v)
	return _u
}

// ClearAfterMonthlyQuotaKnivesSnapshot clears the value of the "after_monthly_quota_knives_snapshot" field.
func (_u *SubscriptionSettlementOrderUpdateOne) ClearAfterMonthlyQuotaKnivesSnapshot() *SubscriptionSettlementOrderUpdateOne {
	_u.mutation.ClearAfterMonthlyQuotaKnivesSnapshot()
	return _u
}

// SetAfterSubscriptionStatus sets the "after_subscription_status" field.
func (_u *SubscriptionSettlementOrderUpdateOne) SetAfterSubscriptionStatus(v string) *SubscriptionSettlementOrderUpdateOne {
	_u.mutation.SetAfterSubscriptionStatus(v)
	return _u
}

// SetNillableAfterSubscriptionStatus sets the "after_subscription_status" field if the given value is not nil.
func (_u *SubscriptionSettlementOrderUpdateOne) SetNillableAfterSubscriptionStatus(v *string) *SubscriptionSettlementOrderUpdateOne {
	if v != nil {
		_u.SetAfterSubscriptionStatus(*v)
	}
	return _u
}

// SetEffectiveAt sets the "effective_at" field.
func (_u *SubscriptionSettlementOrderUpdateOne) SetEffectiveAt(v time.Time) *SubscriptionSettlementOrderUpdateOne {
	_u.mutation.SetEffectiveAt(v)
	return _u
}

// SetNillableEffectiveAt sets the "effective_at" field if the given value is not nil.
func (_u *SubscriptionSettlementOrderUpdateOne) SetNillableEffectiveAt(v *time.Time) *SubscriptionSettlementOrderUpdateOne {
	if v != nil {
		_u.SetEffectiveAt(*v)
	}
	return _u
}

// SetClosedAt sets the "closed_at" field.
func (_u *SubscriptionSettlementOrderUpdateOne) SetClosedAt(v time.Time) *SubscriptionSettlementOrderUpdateOne {
	_u.mutation.SetClosedAt(v)
	return _u
}

// SetNillableClosedAt sets the "closed_at" field if the given value is not nil.
func (_u *SubscriptionSettlementOrderUpdateOne) SetNillableClosedAt(v *time.Time) *SubscriptionSettlementOrderUpdateOne {
	if v != nil {
		_u.SetClosedAt(*v)
	}
	return _u
}

// ClearClosedAt clears the value of the "closed_at" field.
func (_u *SubscriptionSettlementOrderUpdateOne) ClearClosedAt() *SubscriptionSettlementOrderUpdateOne {
	_u.mutation.ClearClosedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SubscriptionSettlementOrderUpdateOne) SetUpdatedAt(v time.Time) *SubscriptionSettlementOrderUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *SubscriptionSettlementOrderUpdateOne) SetUser(v *User) *SubscriptionSettlementOrderUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetOperatorID sets the "operator" edge to the User entity by ID.
func (_u *SubscriptionSettlementOrderUpdateOne) SetOperatorID(id int64) *SubscriptionSettlementOrderUpdateOne {
	_u.mutation.SetOperatorID(id)
	return _u
}

// SetOperator sets the "operator" edge to the User entity.
func (_u *SubscriptionSettlementOrderUpdateOne) SetOperator(v *User) *SubscriptionSettlementOrderUpdateOne {
	return _u.SetOperatorID(v.ID)
}

// SetNextID sets the "next" edge to the SubscriptionSettlementOrder entity by ID.
func (_u *SubscriptionSettlementOrderUpdateOne) SetNextID(id int64) *SubscriptionSettlementOrderUpdateOne {
	_u.mutation.SetNextID(id)
	return _u
}

// SetNillableNextID sets the "next" edge to the SubscriptionSettlementOrder entity by ID if the given value is not nil.
func (_u *SubscriptionSettlementOrderUpdateOne) SetNillableNextID(id *int64) *SubscriptionSettlementOrderUpdateOne {
	if id != nil {
		_u = _u.SetNextID(*id)
	}
	return _u
}

// SetNext sets the "next" edge to the SubscriptionSettlementOrder entity.
func (_u *SubscriptionSettlementOrderUpdateOne) SetNext(v *SubscriptionSettlementOrder) *SubscriptionSettlementOrderUpdateOne {
	return _u.SetNextID(v.ID)
}

// SetPreviousID sets the "previous" edge to the SubscriptionSettlementOrder entity by ID.
func (_u *SubscriptionSettlementOrderUpdateOne) SetPreviousID(id int64) *SubscriptionSettlementOrderUpdateOne {
	_u.mutation.SetPreviousID(id)
	return _u
}

// SetNillablePreviousID sets the "previous" edge to the SubscriptionSettlementOrder entity by ID if the given value is not nil.
func (_u *SubscriptionSettlementOrderUpdateOne) SetNillablePreviousID(id *int64) *SubscriptionSettlementOrderUpdateOne {
	if id != nil {
		_u = _u.SetPreviousID(*id)
	}
	return _u
}

// SetPrevious sets the "previous" edge to the SubscriptionSettlementOrder entity.
func (_u *SubscriptionSettlementOrderUpdateOne) SetPrevious(v *SubscriptionSettlementOrder) *SubscriptionSettlementOrderUpdateOne {
	return _u.SetPreviousID(v.ID)
}

// SetAfterUserSubscription sets the "after_user_subscription" edge to the UserSubscription entity.
func (_u *SubscriptionSettlementOrderUpdateOne) SetAfterUserSubscription(v *UserSubscription) *SubscriptionSettlementOrderUpdateOne {
	return _u.SetAfterUserSubscriptionID(v.ID)
}

// SetAfterPlan sets the "after_plan" edge to the SubscriptionPlan entity.
func (_u *SubscriptionSettlementOrderUpdateOne) SetAfterPlan(v *SubscriptionPlan) *SubscriptionSettlementOrderUpdateOne {
	return _u.SetAfterPlanID(v.ID)
}

// Mutation returns the SubscriptionSettlementOrderMutation object of the builder.
func (_u *SubscriptionSettlementOrderUpdateOne) Mutation() *SubscriptionSettlementOrderMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *SubscriptionSettlementOrderUpdateOne) ClearUser() *SubscriptionSettlementOrderUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearOperator clears the "operator" edge to the User entity.
func (_u *SubscriptionSettlementOrderUpdateOne) ClearOperator() *SubscriptionSettlementOrderUpdateOne {
	_u.mutation.ClearOperator()
	return _u
}

// ClearNext clears the "next" edge to the SubscriptionSettlementOrder entity.
func (_u *SubscriptionSettlementOrderUpdateOne) ClearNext() *SubscriptionSettlementOrderUpdateOne {
	_u.mutation.ClearNext()
	return _u
}

// ClearPrevious clears the "previous" edge to the SubscriptionSettlementOrder entity.
func (_u *SubscriptionSettlementOrderUpdateOne) ClearPrevious() *SubscriptionSettlementOrderUpdateOne {
	_u.mutation.ClearPrevious()
	return _u
}

// ClearAfterUserSubscription clears the "after_user_subscription" edge to the UserSubscription entity.
func (_u *SubscriptionSettlementOrderUpdateOne) ClearAfterUserSubscription() *SubscriptionSettlementOrderUpdateOne {
	_u.mutation.ClearAfterUserSubscription()
	return _u
}

// ClearAfterPlan clears the "after_plan" edge to the SubscriptionPlan entity.
func (_u *SubscriptionSettlementOrderUpdateOne) ClearAfterPlan() *SubscriptionSettlementOrderUpdateOne {
	_u.mutation.ClearAfterPlan()
	return _u
}

// Where appends a list predicates to the SubscriptionSettlementOrderUpdate builder.
func (_u *SubscriptionSettlementOrderUpdateOne) Where(ps ...predicate.SubscriptionSettlementOrder) *SubscriptionSettlementOrderUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SubscriptionSettlementOrderUpdateOne) Select(field string, fields ...string) *SubscriptionSettlementOrderUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SubscriptionSettlementOrder entity.
func (_u *SubscriptionSettlementOrderUpdateOne) Save(ctx context.Context) (*SubscriptionSettlementOrder, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionSettlementOrderUpdateOne) SaveX(ctx context.Context) *SubscriptionSettlementOrder {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SubscriptionSettlementOrderUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionSettlementOrderUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SubscriptionSettlementOrderUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := subscriptionsettlementorder.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubscriptionSettlementOrderUpdateOne) check() error {
	if v, ok := _u.mutation.ActionType(); ok {
		if err := subscriptionsettlementorder.ActionTypeValidator(v); err != nil {
			return &ValidationError{Name: "action_type", err: fmt.Errorf(`ent: validator failed for field "SubscriptionSettlementOrder.action_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ActionSource(); ok {
		if err := subscriptionsettlementorder.ActionSourceValidator(v); err != nil {
			return &ValidationError{Name: "action_source", err: fmt.Errorf(`ent: validator failed for field "SubscriptionSettlementOrder.action_source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := subscriptionsettlementorder.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SubscriptionSettlementOrder.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TriggerRefType(); ok {
		if err := subscriptionsettlementorder.TriggerRefTypeValidator(v); err != nil {
			return &ValidationError{Name: "trigger_ref_type", err: fmt.Errorf(`ent: validator failed for field "SubscriptionSettlementOrder.trigger_ref_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AfterPlanNameSnapshot(); ok {
		if err := subscriptionsettlementorder.AfterPlanNameSnapshotValidator(v); err != nil {
			return &ValidationError{Name: "after_plan_name_snapshot", err: fmt.Errorf(`ent: validator failed for field "SubscriptionSettlementOrder.after_plan_name_snapshot": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AfterValidityUnitSnapshot(); ok {
		if err := subscriptionsettlementorder.AfterValidityUnitSnapshotValidator(v); err != nil {
			return &ValidationError{Name: "after_validity_unit_snapshot", err: fmt.Errorf(`ent: validator failed for field "SubscriptionSettlementOrder.after_validity_unit_snapshot": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AfterSubscriptionStatus(); ok {
		if err := subscriptionsettlementorder.AfterSubscriptionStatusValidator(v); err != nil {
			return &ValidationError{Name: "after_subscription_status", err: fmt.Errorf(`ent: validator failed for field "SubscriptionSettlementOrder.after_subscription_status": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubscriptionSettlementOrder.user"`)
	}
	if _u.mutation.OperatorCleared() && len(_u.mutation.OperatorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubscriptionSettlementOrder.operator"`)
	}
	return nil
}

func (_u *SubscriptionSettlementOrderUpdateOne) sqlSave(ctx context.Context) (_node *SubscriptionSettlementOrder, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscriptionsettlementorder.Table, subscriptionsettlementorder.Columns, sqlgraph.NewFieldSpec(subscriptionsettlementorder.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SubscriptionSettlementOrder.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subscriptionsettlementorder.FieldID)
		for _, f := range fields {
			if !subscriptionsettlementorder.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != subscriptionsettlementorder.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ActionType(); ok {
		_spec.SetField(subscriptionsettlementorder.FieldActionType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ActionSource(); ok {
		_spec.SetField(subscriptionsettlementorder.FieldActionSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(subscriptionsettlementorder.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.TriggerRefType(); ok {
		_spec.SetField(subscriptionsettlementorder.FieldTriggerRefType, field.TypeString, value)
	}
	if value, ok := _u.mutation.TriggerRefID(); ok {
		_spec.SetField(subscriptionsettlementorder.FieldTriggerRefID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTriggerRefID(); ok {
		_spec.AddField(subscriptionsettlementorder.FieldTriggerRefID, field.TypeInt64, value)
	}
	if _u.mutation.TriggerRefIDCleared() {
		_spec.ClearField(subscriptionsettlementorder.FieldTriggerRefID, field.TypeInt64)
	}
	if value, ok := _u.mutation.ActionNote(); ok {
		_spec.SetField(subscriptionsettlementorder.FieldActionNote, field.TypeString, value)
	}
	if _u.mutation.ActionNoteCleared() {
		_spec.ClearField(subscriptionsettlementorder.FieldActionNote, field.TypeString)
	}
	if value, ok := _u.mutation.CarryInResidualValue(); ok {
		_spec.SetField(subscriptionsettlementorder.FieldCarryInResidualValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCarryInResidualValue(); ok {
		_spec.AddField(subscriptionsettlementorder.FieldCarryInResidualValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ActionDeltaValue(); ok {
		_spec.SetField(subscriptionsettlementorder.FieldActionDeltaValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedActionDeltaValue(); ok {
		_spec.AddField(subscriptionsettlementorder.FieldActionDeltaValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AfterSettlementValue(); ok {
		_spec.SetField(subscriptionsettlementorder.FieldAfterSettlementValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAfterSettlementValue(); ok {
		_spec.AddField(subscriptionsettlementorder.FieldAfterSettlementValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RefundResidualValue(); ok {
		_spec.SetField(subscriptionsettlementorder.FieldRefundResidualValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRefundResidualValue(); ok {
		_spec.AddField(subscriptionsettlementorder.FieldRefundResidualValue, field.TypeFloat64, value)
	}
	if _u.mutation.RefundResidualValueCleared() {
		_spec.ClearField(subscriptionsettlementorder.FieldRefundResidualValue, field.TypeFloat64)
	}
	if value, ok := _u.mutation.WriteoffValue(); ok {
		_spec.SetField(subscriptionsettlementorder.FieldWriteoffValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedWriteoffValue(); ok {
		_spec.AddField(subscriptionsettlementorder.FieldWriteoffValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AfterPlanNameSnapshot(); ok {
		_spec.SetField(subscriptionsettlementorder.FieldAfterPlanNameSnapshot, field.TypeString, value)
	}
	if _u.mutation.AfterPlanNameSnapshotCleared() {
		_spec.ClearField(subscriptionsettlementorder.FieldAfterPlanNameSnapshot, field.TypeString)
	}
	if value, ok := _u.mutation.AfterPlanPriceSnapshot(); ok {
		_spec.SetField(subscriptionsettlementorder.FieldAfterPlanPriceSnapshot, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAfterPlanPriceSnapshot(); ok {
		_spec.AddField(subscriptionsettlementorder.FieldAfterPlanPriceSnapshot, field.TypeFloat64, value)
	}
	if _u.mutation.AfterPlanPriceSnapshotCleared() {
		_spec.ClearField(subscriptionsettlementorder.FieldAfterPlanPriceSnapshot, field.TypeFloat64)
	}
	if value, ok := _u.mutation.AfterValidityDaysSnapshot(); ok {
		_spec.SetField(subscriptionsettlementorder.FieldAfterValidityDaysSnapshot, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAfterValidityDaysSnapshot(); ok {
		_spec.AddField(subscriptionsettlementorder.FieldAfterValidityDaysSnapshot, field.TypeInt, value)
	}
	if _u.mutation.AfterValidityDaysSnapshotCleared() {
		_spec.ClearField(subscriptionsettlementorder.FieldAfterValidityDaysSnapshot, field.TypeInt)
	}
	if value, ok := _u.mutation.AfterValidityUnitSnapshot(); ok {
		_spec.SetField(subscriptionsettlementorder.FieldAfterValidityUnitSnapshot, field.TypeString, value)
	}
	if _u.mutation.AfterValidityUnitSnapshotCleared() {
		_spec.ClearField(subscriptionsettlementorder.FieldAfterValidityUnitSnapshot, field.TypeString)
	}
	if value, ok := _u.mutation.AfterStartsAt(); ok {
		_spec.SetField(subscriptionsettlementorder.FieldAfterStartsAt, field.TypeTime, value)
	}
	if _u.mutation.AfterStartsAtCleared() {
		_spec.ClearField(subscriptionsettlementorder.FieldAfterStartsAt, field.TypeTime)
	}
	if value, ok := _u.mutation.AfterExpiresAt(); ok {
		_spec.SetField(subscriptionsettlementorder.FieldAfterExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.AfterExpiresAtCleared() {
		_spec.ClearField(subscriptionsettlementorder.FieldAfterExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.AfterDailyQuotaKnivesSnapshot(); ok {
		_spec.SetField(subscriptionsettlementorder.FieldAfterDailyQuotaKnivesSnapshot, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAfterDailyQuotaKnivesSnapshot(); ok {
		_spec.AddField(subscriptionsettlementorder.FieldAfterDailyQuotaKnivesSnapshot, field.TypeFloat64, value)
	}
	if _u.mutation.AfterDailyQuotaKnivesSnapshotCleared() {
		_spec.ClearField(subscriptionsettlementorder.FieldAfterDailyQuotaKnivesSnapshot, field.TypeFloat64)
	}
	if value, ok := _u.mutation.AfterWeeklyQuotaKnivesSnapshot(); ok {
		_spec.SetField(subscriptionsettlementorder.FieldAfterWeeklyQuotaKnivesSnapshot, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAfterWeeklyQuotaKnivesSnapshot(); ok {
		_spec.AddField(subscriptionsettlementorder.FieldAfterWeeklyQuotaKnivesSnapshot, field.TypeFloat64, value)
	}
	if _u.mutation.AfterWeeklyQuotaKnivesSnapshotCleared() {
		_spec.ClearField(subscriptionsettlementorder.FieldAfterWeeklyQuotaKnivesSnapshot, field.TypeFloat64)
	}
	if value, ok := _u.mutation.AfterMonthlyQuotaKnivesSnapshot(); ok {
		_spec.SetField(subscriptionsettlementorder.FieldAfterMonthlyQuotaKnivesSnapshot, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAfterMonthlyQuotaKnivesSnapshot(); ok {
		_spec.AddField(subscriptionsettlementorder.FieldAfterMonthlyQuotaKnivesSnapshot, field.TypeFloat64, value)
	}
	if _u.mutation.AfterMonthlyQuotaKnivesSnapshotCleared() {
		_spec.ClearField(subscriptionsettlementorder.FieldAfterMonthlyQuotaKnivesSnapshot, field.TypeFloat64)
	}
	if value, ok := _u.mutation.AfterSubscriptionStatus(); ok {
		_spec.SetField(subscriptionsettlementorder.FieldAfterSubscriptionStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.EffectiveAt(); ok {
		_spec.SetField(subscriptionsettlementorder.FieldEffectiveAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ClosedAt(); ok {
		_spec.SetField(subscriptionsettlementorder.FieldClosedAt, field.TypeTime, value)
	}
	if _u.mutation.ClosedAtCleared() {
		_spec.ClearField(subscriptionsettlementorder.FieldClosedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(subscriptionsettlementorder.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionsettlementorder.UserTable,
			Columns: []string{subscriptionsettlementorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionsettlementorder.UserTable,
			Columns: []string{subscriptionsettlementorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OperatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionsettlementorder.OperatorTable,
			Columns: []string{subscriptionsettlementorder.OperatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OperatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionsettlementorder.OperatorTable,
			Columns: []string{subscriptionsettlementorder.OperatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.NextCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   subscriptionsettlementorder.NextTable,
			Columns: []string{subscriptionsettlementorder.NextColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionsettlementorder.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.NextIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   subscriptionsettlementorder.NextTable,
			Columns: []string{subscriptionsettlementorder.NextColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionsettlementorder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PreviousCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   subscriptionsettlementorder.PreviousTable,
			Columns: []string{subscriptionsettlementorder.PreviousColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionsettlementorder.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PreviousIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   subscriptionsettlementorder.PreviousTable,
			Columns: []string{subscriptionsettlementorder.PreviousColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionsettlementorder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AfterUserSubscriptionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionsettlementorder.AfterUserSubscriptionTable,
			Columns: []string{subscriptionsettlementorder.AfterUserSubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AfterUserSubscriptionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionsettlementorder.AfterUserSubscriptionTable,
			Columns: []string{subscriptionsettlementorder.AfterUserSubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AfterPlanCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionsettlementorder.AfterPlanTable,
			Columns: []string{subscriptionsettlementorder.AfterPlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionplan.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AfterPlanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionsettlementorder.AfterPlanTable,
			Columns: []string{subscriptionsettlementorder.AfterPlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionplan.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SubscriptionSettlementOrder{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscriptionsettlementorder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
