// Code generated by ent, DO NOT EDIT.

package subscriptionsettlementorder

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldEQ(FieldUserID, v))
}

// PrevSettlementID applies equality check predicate on the "prev_settlement_id" field. It's identical to PrevSettlementIDEQ.
func PrevSettlementID(v int64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldEQ(FieldPrevSettlementID, v))
}

// ActionType applies equality check predicate on the "action_type" field. It's identical to ActionTypeEQ.
func ActionType(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldEQ(FieldActionType, v))
}

// ActionSource applies equality check predicate on the "action_source" field. It's identical to ActionSourceEQ.
func ActionSource(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldEQ(FieldActionSource, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldEQ(FieldStatus, v))
}

// TriggerRefType applies equality check predicate on the "trigger_ref_type" field. It's identical to TriggerRefTypeEQ.
func TriggerRefType(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldEQ(FieldTriggerRefType, v))
}

// TriggerRefID applies equality check predicate on the "trigger_ref_id" field. It's identical to TriggerRefIDEQ.
func TriggerRefID(v int64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldEQ(FieldTriggerRefID, v))
}

// OperatorUserID applies equality check predicate on the "operator_user_id" field. It's identical to OperatorUserIDEQ.
func OperatorUserID(v int64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldEQ(FieldOperatorUserID, v))
}

// ActionNote applies equality check predicate on the "action_note" field. It's identical to ActionNoteEQ.
func ActionNote(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldEQ(FieldActionNote, v))
}

// CarryInResidualValue applies equality check predicate on the "carry_in_residual_value" field. It's identical to CarryInResidualValueEQ.
func CarryInResidualValue(v float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldEQ(FieldCarryInResidualValue, v))
}

// ActionDeltaValue applies equality check predicate on the "action_delta_value" field. It's identical to ActionDeltaValueEQ.
func ActionDeltaValue(v float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldEQ(FieldActionDeltaValue, v))
}

// AfterSettlementValue applies equality check predicate on the "after_settlement_value" field. It's identical to AfterSettlementValueEQ.
func AfterSettlementValue(v float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldEQ(FieldAfterSettlementValue, v))
}

// RefundResidualValue applies equality check predicate on the "refund_residual_value" field. It's identical to RefundResidualValueEQ.
func RefundResidualValue(v float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldEQ(FieldRefundResidualValue, v))
}

// WriteoffValue applies equality check predicate on the "writeoff_value" field. It's identical to WriteoffValueEQ.
func WriteoffValue(v float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldEQ(FieldWriteoffValue, v))
}

// AfterUserSubscriptionID applies equality check predicate on the "after_user_subscription_id" field. It's identical to AfterUserSubscriptionIDEQ.
func AfterUserSubscriptionID(v int64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldEQ(FieldAfterUserSubscriptionID, v))
}

// AfterPlanID applies equality check predicate on the "after_plan_id" field. It's identical to AfterPlanIDEQ.
func AfterPlanID(v int64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldEQ(FieldAfterPlanID, v))
}

// AfterPlanNameSnapshot applies equality check predicate on the "after_plan_name_snapshot" field. It's identical to AfterPlanNameSnapshotEQ.
func AfterPlanNameSnapshot(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldEQ(FieldAfterPlanNameSnapshot, v))
}

// AfterPlanPriceSnapshot applies equality check predicate on the "after_plan_price_snapshot" field. It's identical to AfterPlanPriceSnapshotEQ.
func AfterPlanPriceSnapshot(v float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldEQ(FieldAfterPlanPriceSnapshot, v))
}

// AfterValidityDaysSnapshot applies equality check predicate on the "after_validity_days_snapshot" field. It's identical to AfterValidityDaysSnapshotEQ.
func AfterValidityDaysSnapshot(v int) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldEQ(FieldAfterValidityDaysSnapshot, v))
}

// AfterValidityUnitSnapshot applies equality check predicate on the "after_validity_unit_snapshot" field. It's identical to AfterValidityUnitSnapshotEQ.
func AfterValidityUnitSnapshot(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldEQ(FieldAfterValidityUnitSnapshot, v))
}

// AfterStartsAt applies equality check predicate on the "after_starts_at" field. It's identical to AfterStartsAtEQ.
func AfterStartsAt(v time.Time) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldEQ(FieldAfterStartsAt, v))
}

// AfterExpiresAt applies equality check predicate on the "after_expires_at" field. It's identical to AfterExpiresAtEQ.
func AfterExpiresAt(v time.Time) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldEQ(FieldAfterExpiresAt, v))
}

// AfterDailyQuotaKnivesSnapshot applies equality check predicate on the "after_daily_quota_knives_snapshot" field. It's identical to AfterDailyQuotaKnivesSnapshotEQ.
func AfterDailyQuotaKnivesSnapshot(v float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldEQ(FieldAfterDailyQuotaKnivesSnapshot, v))
}

// AfterWeeklyQuotaKnivesSnapshot applies equality check predicate on the "after_weekly_quota_knives_snapshot" field. It's identical to AfterWeeklyQuotaKnivesSnapshotEQ.
func AfterWeeklyQuotaKnivesSnapshot(v float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldEQ(FieldAfterWeeklyQuotaKnivesSnapshot, v))
}

// AfterMonthlyQuotaKnivesSnapshot applies equality check predicate on the "after_monthly_quota_knives_snapshot" field. It's identical to AfterMonthlyQuotaKnivesSnapshotEQ.
func AfterMonthlyQuotaKnivesSnapshot(v float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldEQ(FieldAfterMonthlyQuotaKnivesSnapshot, v))
}

// AfterSubscriptionStatus applies equality check predicate on the "after_subscription_status" field. It's identical to AfterSubscriptionStatusEQ.
func AfterSubscriptionStatus(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldEQ(FieldAfterSubscriptionStatus, v))
}

// EffectiveAt applies equality check predicate on the "effective_at" field. It's identical to EffectiveAtEQ.
func EffectiveAt(v time.Time) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldEQ(FieldEffectiveAt, v))
}

// ClosedAt applies equality check predicate on the "closed_at" field. It's identical to ClosedAtEQ.
func ClosedAt(v time.Time) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldEQ(FieldClosedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNotIn(FieldUserID, vs...))
}

// PrevSettlementIDEQ applies the EQ predicate on the "prev_settlement_id" field.
func PrevSettlementIDEQ(v int64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldEQ(FieldPrevSettlementID, v))
}

// PrevSettlementIDNEQ applies the NEQ predicate on the "prev_settlement_id" field.
func PrevSettlementIDNEQ(v int64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNEQ(FieldPrevSettlementID, v))
}

// PrevSettlementIDIn applies the In predicate on the "prev_settlement_id" field.
func PrevSettlementIDIn(vs ...int64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldIn(FieldPrevSettlementID, vs...))
}

// PrevSettlementIDNotIn applies the NotIn predicate on the "prev_settlement_id" field.
func PrevSettlementIDNotIn(vs ...int64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNotIn(FieldPrevSettlementID, vs...))
}

// PrevSettlementIDIsNil applies the IsNil predicate on the "prev_settlement_id" field.
func PrevSettlementIDIsNil() predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldIsNull(FieldPrevSettlementID))
}

// PrevSettlementIDNotNil applies the NotNil predicate on the "prev_settlement_id" field.
func PrevSettlementIDNotNil() predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNotNull(FieldPrevSettlementID))
}

// ActionTypeEQ applies the EQ predicate on the "action_type" field.
func ActionTypeEQ(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldEQ(FieldActionType, v))
}

// ActionTypeNEQ applies the NEQ predicate on the "action_type" field.
func ActionTypeNEQ(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNEQ(FieldActionType, v))
}

// ActionTypeIn applies the In predicate on the "action_type" field.
func ActionTypeIn(vs ...string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldIn(FieldActionType, vs...))
}

// ActionTypeNotIn applies the NotIn predicate on the "action_type" field.
func ActionTypeNotIn(vs ...string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNotIn(FieldActionType, vs...))
}

// ActionTypeGT applies the GT predicate on the "action_type" field.
func ActionTypeGT(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldGT(FieldActionType, v))
}

// ActionTypeGTE applies the GTE predicate on the "action_type" field.
func ActionTypeGTE(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldGTE(FieldActionType, v))
}

// ActionTypeLT applies the LT predicate on the "action_type" field.
func ActionTypeLT(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldLT(FieldActionType, v))
}

// ActionTypeLTE applies the LTE predicate on the "action_type" field.
func ActionTypeLTE(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldLTE(FieldActionType, v))
}

// ActionTypeContains applies the Contains predicate on the "action_type" field.
func ActionTypeContains(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldContains(FieldActionType, v))
}

// ActionTypeHasPrefix applies the HasPrefix predicate on the "action_type" field.
func ActionTypeHasPrefix(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldHasPrefix(FieldActionType, v))
}

// ActionTypeHasSuffix applies the HasSuffix predicate on the "action_type" field.
func ActionTypeHasSuffix(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldHasSuffix(FieldActionType, v))
}

// ActionTypeEqualFold applies the EqualFold predicate on the "action_type" field.
func ActionTypeEqualFold(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldEqualFold(FieldActionType, v))
}

// ActionTypeContainsFold applies the ContainsFold predicate on the "action_type" field.
func ActionTypeContainsFold(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldContainsFold(FieldActionType, v))
}

// ActionSourceEQ applies the EQ predicate on the "action_source" field.
func ActionSourceEQ(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldEQ(FieldActionSource, v))
}

// ActionSourceNEQ applies the NEQ predicate on the "action_source" field.
func ActionSourceNEQ(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNEQ(FieldActionSource, v))
}

// ActionSourceIn applies the In predicate on the "action_source" field.
func ActionSourceIn(vs ...string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldIn(FieldActionSource, vs...))
}

// ActionSourceNotIn applies the NotIn predicate on the "action_source" field.
func ActionSourceNotIn(vs ...string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNotIn(FieldActionSource, vs...))
}

// ActionSourceGT applies the GT predicate on the "action_source" field.
func ActionSourceGT(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldGT(FieldActionSource, v))
}

// ActionSourceGTE applies the GTE predicate on the "action_source" field.
func ActionSourceGTE(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldGTE(FieldActionSource, v))
}

// ActionSourceLT applies the LT predicate on the "action_source" field.
func ActionSourceLT(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldLT(FieldActionSource, v))
}

// ActionSourceLTE applies the LTE predicate on the "action_source" field.
func ActionSourceLTE(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldLTE(FieldActionSource, v))
}

// ActionSourceContains applies the Contains predicate on the "action_source" field.
func ActionSourceContains(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldContains(FieldActionSource, v))
}

// ActionSourceHasPrefix applies the HasPrefix predicate on the "action_source" field.
func ActionSourceHasPrefix(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldHasPrefix(FieldActionSource, v))
}

// ActionSourceHasSuffix applies the HasSuffix predicate on the "action_source" field.
func ActionSourceHasSuffix(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldHasSuffix(FieldActionSource, v))
}

// ActionSourceEqualFold applies the EqualFold predicate on the "action_source" field.
func ActionSourceEqualFold(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldEqualFold(FieldActionSource, v))
}

// ActionSourceContainsFold applies the ContainsFold predicate on the "action_source" field.
func ActionSourceContainsFold(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldContainsFold(FieldActionSource, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldContainsFold(FieldStatus, v))
}

// TriggerRefTypeEQ applies the EQ predicate on the "trigger_ref_type" field.
func TriggerRefTypeEQ(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldEQ(FieldTriggerRefType, v))
}

// TriggerRefTypeNEQ applies the NEQ predicate on the "trigger_ref_type" field.
func TriggerRefTypeNEQ(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNEQ(FieldTriggerRefType, v))
}

// TriggerRefTypeIn applies the In predicate on the "trigger_ref_type" field.
func TriggerRefTypeIn(vs ...string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldIn(FieldTriggerRefType, vs...))
}

// TriggerRefTypeNotIn applies the NotIn predicate on the "trigger_ref_type" field.
func TriggerRefTypeNotIn(vs ...string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNotIn(FieldTriggerRefType, vs...))
}

// TriggerRefTypeGT applies the GT predicate on the "trigger_ref_type" field.
func TriggerRefTypeGT(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldGT(FieldTriggerRefType, v))
}

// TriggerRefTypeGTE applies the GTE predicate on the "trigger_ref_type" field.
func TriggerRefTypeGTE(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldGTE(FieldTriggerRefType, v))
}

// TriggerRefTypeLT applies the LT predicate on the "trigger_ref_type" field.
func TriggerRefTypeLT(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldLT(FieldTriggerRefType, v))
}

// TriggerRefTypeLTE applies the LTE predicate on the "trigger_ref_type" field.
func TriggerRefTypeLTE(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldLTE(FieldTriggerRefType, v))
}

// TriggerRefTypeContains applies the Contains predicate on the "trigger_ref_type" field.
func TriggerRefTypeContains(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldContains(FieldTriggerRefType, v))
}

// TriggerRefTypeHasPrefix applies the HasPrefix predicate on the "trigger_ref_type" field.
func TriggerRefTypeHasPrefix(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldHasPrefix(FieldTriggerRefType, v))
}

// TriggerRefTypeHasSuffix applies the HasSuffix predicate on the "trigger_ref_type" field.
func TriggerRefTypeHasSuffix(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldHasSuffix(FieldTriggerRefType, v))
}

// TriggerRefTypeEqualFold applies the EqualFold predicate on the "trigger_ref_type" field.
func TriggerRefTypeEqualFold(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldEqualFold(FieldTriggerRefType, v))
}

// TriggerRefTypeContainsFold applies the ContainsFold predicate on the "trigger_ref_type" field.
func TriggerRefTypeContainsFold(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldContainsFold(FieldTriggerRefType, v))
}

// TriggerRefIDEQ applies the EQ predicate on the "trigger_ref_id" field.
func TriggerRefIDEQ(v int64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldEQ(FieldTriggerRefID, v))
}

// TriggerRefIDNEQ applies the NEQ predicate on the "trigger_ref_id" field.
func TriggerRefIDNEQ(v int64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNEQ(FieldTriggerRefID, v))
}

// TriggerRefIDIn applies the In predicate on the "trigger_ref_id" field.
func TriggerRefIDIn(vs ...int64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldIn(FieldTriggerRefID, vs...))
}

// TriggerRefIDNotIn applies the NotIn predicate on the "trigger_ref_id" field.
func TriggerRefIDNotIn(vs ...int64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNotIn(FieldTriggerRefID, vs...))
}

// TriggerRefIDGT applies the GT predicate on the "trigger_ref_id" field.
func TriggerRefIDGT(v int64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldGT(FieldTriggerRefID, v))
}

// TriggerRefIDGTE applies the GTE predicate on the "trigger_ref_id" field.
func TriggerRefIDGTE(v int64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldGTE(FieldTriggerRefID, v))
}

// TriggerRefIDLT applies the LT predicate on the "trigger_ref_id" field.
func TriggerRefIDLT(v int64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldLT(FieldTriggerRefID, v))
}

// TriggerRefIDLTE applies the LTE predicate on the "trigger_ref_id" field.
func TriggerRefIDLTE(v int64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldLTE(FieldTriggerRefID, v))
}

// TriggerRefIDIsNil applies the IsNil predicate on the "trigger_ref_id" field.
func TriggerRefIDIsNil() predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldIsNull(FieldTriggerRefID))
}

// TriggerRefIDNotNil applies the NotNil predicate on the "trigger_ref_id" field.
func TriggerRefIDNotNil() predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNotNull(FieldTriggerRefID))
}

// OperatorUserIDEQ applies the EQ predicate on the "operator_user_id" field.
func OperatorUserIDEQ(v int64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldEQ(FieldOperatorUserID, v))
}

// OperatorUserIDNEQ applies the NEQ predicate on the "operator_user_id" field.
func OperatorUserIDNEQ(v int64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNEQ(FieldOperatorUserID, v))
}

// OperatorUserIDIn applies the In predicate on the "operator_user_id" field.
func OperatorUserIDIn(vs ...int64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldIn(FieldOperatorUserID, vs...))
}

// OperatorUserIDNotIn applies the NotIn predicate on the "operator_user_id" field.
func OperatorUserIDNotIn(vs ...int64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNotIn(FieldOperatorUserID, vs...))
}

// ActionNoteEQ applies the EQ predicate on the "action_note" field.
func ActionNoteEQ(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldEQ(FieldActionNote, v))
}

// ActionNoteNEQ applies the NEQ predicate on the "action_note" field.
func ActionNoteNEQ(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNEQ(FieldActionNote, v))
}

// ActionNoteIn applies the In predicate on the "action_note" field.
func ActionNoteIn(vs ...string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldIn(FieldActionNote, vs...))
}

// ActionNoteNotIn applies the NotIn predicate on the "action_note" field.
func ActionNoteNotIn(vs ...string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNotIn(FieldActionNote, vs...))
}

// ActionNoteGT applies the GT predicate on the "action_note" field.
func ActionNoteGT(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldGT(FieldActionNote, v))
}

// ActionNoteGTE applies the GTE predicate on the "action_note" field.
func ActionNoteGTE(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldGTE(FieldActionNote, v))
}

// ActionNoteLT applies the LT predicate on the "action_note" field.
func ActionNoteLT(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldLT(FieldActionNote, v))
}

// ActionNoteLTE applies the LTE predicate on the "action_note" field.
func ActionNoteLTE(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldLTE(FieldActionNote, v))
}

// ActionNoteContains applies the Contains predicate on the "action_note" field.
func ActionNoteContains(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldContains(FieldActionNote, v))
}

// ActionNoteHasPrefix applies the HasPrefix predicate on the "action_note" field.
func ActionNoteHasPrefix(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldHasPrefix(FieldActionNote, v))
}

// ActionNoteHasSuffix applies the HasSuffix predicate on the "action_note" field.
func ActionNoteHasSuffix(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldHasSuffix(FieldActionNote, v))
}

// ActionNoteIsNil applies the IsNil predicate on the "action_note" field.
func ActionNoteIsNil() predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldIsNull(FieldActionNote))
}

// ActionNoteNotNil applies the NotNil predicate on the "action_note" field.
func ActionNoteNotNil() predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNotNull(FieldActionNote))
}

// ActionNoteEqualFold applies the EqualFold predicate on the "action_note" field.
func ActionNoteEqualFold(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldEqualFold(FieldActionNote, v))
}

// ActionNoteContainsFold applies the ContainsFold predicate on the "action_note" field.
func ActionNoteContainsFold(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldContainsFold(FieldActionNote, v))
}

// CarryInResidualValueEQ applies the EQ predicate on the "carry_in_residual_value" field.
func CarryInResidualValueEQ(v float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldEQ(FieldCarryInResidualValue, v))
}

// CarryInResidualValueNEQ applies the NEQ predicate on the "carry_in_residual_value" field.
func CarryInResidualValueNEQ(v float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNEQ(FieldCarryInResidualValue, v))
}

// CarryInResidualValueIn applies the In predicate on the "carry_in_residual_value" field.
func CarryInResidualValueIn(vs ...float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldIn(FieldCarryInResidualValue, vs...))
}

// CarryInResidualValueNotIn applies the NotIn predicate on the "carry_in_residual_value" field.
func CarryInResidualValueNotIn(vs ...float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNotIn(FieldCarryInResidualValue, vs...))
}

// CarryInResidualValueGT applies the GT predicate on the "carry_in_residual_value" field.
func CarryInResidualValueGT(v float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldGT(FieldCarryInResidualValue, v))
}

// CarryInResidualValueGTE applies the GTE predicate on the "carry_in_residual_value" field.
func CarryInResidualValueGTE(v float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldGTE(FieldCarryInResidualValue, v))
}

// CarryInResidualValueLT applies the LT predicate on the "carry_in_residual_value" field.
func CarryInResidualValueLT(v float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldLT(FieldCarryInResidualValue, v))
}

// CarryInResidualValueLTE applies the LTE predicate on the "carry_in_residual_value" field.
func CarryInResidualValueLTE(v float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldLTE(FieldCarryInResidualValue, v))
}

// ActionDeltaValueEQ applies the EQ predicate on the "action_delta_value" field.
func ActionDeltaValueEQ(v float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldEQ(FieldActionDeltaValue, v))
}

// ActionDeltaValueNEQ applies the NEQ predicate on the "action_delta_value" field.
func ActionDeltaValueNEQ(v float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNEQ(FieldActionDeltaValue, v))
}

// ActionDeltaValueIn applies the In predicate on the "action_delta_value" field.
func ActionDeltaValueIn(vs ...float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldIn(FieldActionDeltaValue, vs...))
}

// ActionDeltaValueNotIn applies the NotIn predicate on the "action_delta_value" field.
func ActionDeltaValueNotIn(vs ...float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNotIn(FieldActionDeltaValue, vs...))
}

// ActionDeltaValueGT applies the GT predicate on the "action_delta_value" field.
func ActionDeltaValueGT(v float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldGT(FieldActionDeltaValue, v))
}

// ActionDeltaValueGTE applies the GTE predicate on the "action_delta_value" field.
func ActionDeltaValueGTE(v float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldGTE(FieldActionDeltaValue, v))
}

// ActionDeltaValueLT applies the LT predicate on the "action_delta_value" field.
func ActionDeltaValueLT(v float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldLT(FieldActionDeltaValue, v))
}

// ActionDeltaValueLTE applies the LTE predicate on the "action_delta_value" field.
func ActionDeltaValueLTE(v float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldLTE(FieldActionDeltaValue, v))
}

// AfterSettlementValueEQ applies the EQ predicate on the "after_settlement_value" field.
func AfterSettlementValueEQ(v float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldEQ(FieldAfterSettlementValue, v))
}

// AfterSettlementValueNEQ applies the NEQ predicate on the "after_settlement_value" field.
func AfterSettlementValueNEQ(v float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNEQ(FieldAfterSettlementValue, v))
}

// AfterSettlementValueIn applies the In predicate on the "after_settlement_value" field.
func AfterSettlementValueIn(vs ...float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldIn(FieldAfterSettlementValue, vs...))
}

// AfterSettlementValueNotIn applies the NotIn predicate on the "after_settlement_value" field.
func AfterSettlementValueNotIn(vs ...float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNotIn(FieldAfterSettlementValue, vs...))
}

// AfterSettlementValueGT applies the GT predicate on the "after_settlement_value" field.
func AfterSettlementValueGT(v float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldGT(FieldAfterSettlementValue, v))
}

// AfterSettlementValueGTE applies the GTE predicate on the "after_settlement_value" field.
func AfterSettlementValueGTE(v float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldGTE(FieldAfterSettlementValue, v))
}

// AfterSettlementValueLT applies the LT predicate on the "after_settlement_value" field.
func AfterSettlementValueLT(v float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldLT(FieldAfterSettlementValue, v))
}

// AfterSettlementValueLTE applies the LTE predicate on the "after_settlement_value" field.
func AfterSettlementValueLTE(v float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldLTE(FieldAfterSettlementValue, v))
}

// RefundResidualValueEQ applies the EQ predicate on the "refund_residual_value" field.
func RefundResidualValueEQ(v float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldEQ(FieldRefundResidualValue, v))
}

// RefundResidualValueNEQ applies the NEQ predicate on the "refund_residual_value" field.
func RefundResidualValueNEQ(v float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNEQ(FieldRefundResidualValue, v))
}

// RefundResidualValueIn applies the In predicate on the "refund_residual_value" field.
func RefundResidualValueIn(vs ...float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldIn(FieldRefundResidualValue, vs...))
}

// RefundResidualValueNotIn applies the NotIn predicate on the "refund_residual_value" field.
func RefundResidualValueNotIn(vs ...float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNotIn(FieldRefundResidualValue, vs...))
}

// RefundResidualValueGT applies the GT predicate on the "refund_residual_value" field.
func RefundResidualValueGT(v float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldGT(FieldRefundResidualValue, v))
}

// RefundResidualValueGTE applies the GTE predicate on the "refund_residual_value" field.
func RefundResidualValueGTE(v float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldGTE(FieldRefundResidualValue, v))
}

// RefundResidualValueLT applies the LT predicate on the "refund_residual_value" field.
func RefundResidualValueLT(v float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldLT(FieldRefundResidualValue, v))
}

// RefundResidualValueLTE applies the LTE predicate on the "refund_residual_value" field.
func RefundResidualValueLTE(v float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldLTE(FieldRefundResidualValue, v))
}

// RefundResidualValueIsNil applies the IsNil predicate on the "refund_residual_value" field.
func RefundResidualValueIsNil() predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldIsNull(FieldRefundResidualValue))
}

// RefundResidualValueNotNil applies the NotNil predicate on the "refund_residual_value" field.
func RefundResidualValueNotNil() predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNotNull(FieldRefundResidualValue))
}

// WriteoffValueEQ applies the EQ predicate on the "writeoff_value" field.
func WriteoffValueEQ(v float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldEQ(FieldWriteoffValue, v))
}

// WriteoffValueNEQ applies the NEQ predicate on the "writeoff_value" field.
func WriteoffValueNEQ(v float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNEQ(FieldWriteoffValue, v))
}

// WriteoffValueIn applies the In predicate on the "writeoff_value" field.
func WriteoffValueIn(vs ...float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldIn(FieldWriteoffValue, vs...))
}

// WriteoffValueNotIn applies the NotIn predicate on the "writeoff_value" field.
func WriteoffValueNotIn(vs ...float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNotIn(FieldWriteoffValue, vs...))
}

// WriteoffValueGT applies the GT predicate on the "writeoff_value" field.
func WriteoffValueGT(v float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldGT(FieldWriteoffValue, v))
}

// WriteoffValueGTE applies the GTE predicate on the "writeoff_value" field.
func WriteoffValueGTE(v float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldGTE(FieldWriteoffValue, v))
}

// WriteoffValueLT applies the LT predicate on the "writeoff_value" field.
func WriteoffValueLT(v float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldLT(FieldWriteoffValue, v))
}

// WriteoffValueLTE applies the LTE predicate on the "writeoff_value" field.
func WriteoffValueLTE(v float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldLTE(FieldWriteoffValue, v))
}

// AfterUserSubscriptionIDEQ applies the EQ predicate on the "after_user_subscription_id" field.
func AfterUserSubscriptionIDEQ(v int64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldEQ(FieldAfterUserSubscriptionID, v))
}

// AfterUserSubscriptionIDNEQ applies the NEQ predicate on the "after_user_subscription_id" field.
func AfterUserSubscriptionIDNEQ(v int64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNEQ(FieldAfterUserSubscriptionID, v))
}

// AfterUserSubscriptionIDIn applies the In predicate on the "after_user_subscription_id" field.
func AfterUserSubscriptionIDIn(vs ...int64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldIn(FieldAfterUserSubscriptionID, vs...))
}

// AfterUserSubscriptionIDNotIn applies the NotIn predicate on the "after_user_subscription_id" field.
func AfterUserSubscriptionIDNotIn(vs ...int64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNotIn(FieldAfterUserSubscriptionID, vs...))
}

// AfterUserSubscriptionIDIsNil applies the IsNil predicate on the "after_user_subscription_id" field.
func AfterUserSubscriptionIDIsNil() predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldIsNull(FieldAfterUserSubscriptionID))
}

// AfterUserSubscriptionIDNotNil applies the NotNil predicate on the "after_user_subscription_id" field.
func AfterUserSubscriptionIDNotNil() predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNotNull(FieldAfterUserSubscriptionID))
}

// AfterPlanIDEQ applies the EQ predicate on the "after_plan_id" field.
func AfterPlanIDEQ(v int64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldEQ(FieldAfterPlanID, v))
}

// AfterPlanIDNEQ applies the NEQ predicate on the "after_plan_id" field.
func AfterPlanIDNEQ(v int64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNEQ(FieldAfterPlanID, v))
}

// AfterPlanIDIn applies the In predicate on the "after_plan_id" field.
func AfterPlanIDIn(vs ...int64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldIn(FieldAfterPlanID, vs...))
}

// AfterPlanIDNotIn applies the NotIn predicate on the "after_plan_id" field.
func AfterPlanIDNotIn(vs ...int64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNotIn(FieldAfterPlanID, vs...))
}

// AfterPlanIDIsNil applies the IsNil predicate on the "after_plan_id" field.
func AfterPlanIDIsNil() predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldIsNull(FieldAfterPlanID))
}

// AfterPlanIDNotNil applies the NotNil predicate on the "after_plan_id" field.
func AfterPlanIDNotNil() predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNotNull(FieldAfterPlanID))
}

// AfterPlanNameSnapshotEQ applies the EQ predicate on the "after_plan_name_snapshot" field.
func AfterPlanNameSnapshotEQ(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldEQ(FieldAfterPlanNameSnapshot, v))
}

// AfterPlanNameSnapshotNEQ applies the NEQ predicate on the "after_plan_name_snapshot" field.
func AfterPlanNameSnapshotNEQ(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNEQ(FieldAfterPlanNameSnapshot, v))
}

// AfterPlanNameSnapshotIn applies the In predicate on the "after_plan_name_snapshot" field.
func AfterPlanNameSnapshotIn(vs ...string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldIn(FieldAfterPlanNameSnapshot, vs...))
}

// AfterPlanNameSnapshotNotIn applies the NotIn predicate on the "after_plan_name_snapshot" field.
func AfterPlanNameSnapshotNotIn(vs ...string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNotIn(FieldAfterPlanNameSnapshot, vs...))
}

// AfterPlanNameSnapshotGT applies the GT predicate on the "after_plan_name_snapshot" field.
func AfterPlanNameSnapshotGT(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldGT(FieldAfterPlanNameSnapshot, v))
}

// AfterPlanNameSnapshotGTE applies the GTE predicate on the "after_plan_name_snapshot" field.
func AfterPlanNameSnapshotGTE(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldGTE(FieldAfterPlanNameSnapshot, v))
}

// AfterPlanNameSnapshotLT applies the LT predicate on the "after_plan_name_snapshot" field.
func AfterPlanNameSnapshotLT(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldLT(FieldAfterPlanNameSnapshot, v))
}

// AfterPlanNameSnapshotLTE applies the LTE predicate on the "after_plan_name_snapshot" field.
func AfterPlanNameSnapshotLTE(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldLTE(FieldAfterPlanNameSnapshot, v))
}

// AfterPlanNameSnapshotContains applies the Contains predicate on the "after_plan_name_snapshot" field.
func AfterPlanNameSnapshotContains(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldContains(FieldAfterPlanNameSnapshot, v))
}

// AfterPlanNameSnapshotHasPrefix applies the HasPrefix predicate on the "after_plan_name_snapshot" field.
func AfterPlanNameSnapshotHasPrefix(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldHasPrefix(FieldAfterPlanNameSnapshot, v))
}

// AfterPlanNameSnapshotHasSuffix applies the HasSuffix predicate on the "after_plan_name_snapshot" field.
func AfterPlanNameSnapshotHasSuffix(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldHasSuffix(FieldAfterPlanNameSnapshot, v))
}

// AfterPlanNameSnapshotIsNil applies the IsNil predicate on the "after_plan_name_snapshot" field.
func AfterPlanNameSnapshotIsNil() predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldIsNull(FieldAfterPlanNameSnapshot))
}

// AfterPlanNameSnapshotNotNil applies the NotNil predicate on the "after_plan_name_snapshot" field.
func AfterPlanNameSnapshotNotNil() predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNotNull(FieldAfterPlanNameSnapshot))
}

// AfterPlanNameSnapshotEqualFold applies the EqualFold predicate on the "after_plan_name_snapshot" field.
func AfterPlanNameSnapshotEqualFold(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldEqualFold(FieldAfterPlanNameSnapshot, v))
}

// AfterPlanNameSnapshotContainsFold applies the ContainsFold predicate on the "after_plan_name_snapshot" field.
func AfterPlanNameSnapshotContainsFold(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldContainsFold(FieldAfterPlanNameSnapshot, v))
}

// AfterPlanPriceSnapshotEQ applies the EQ predicate on the "after_plan_price_snapshot" field.
func AfterPlanPriceSnapshotEQ(v float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldEQ(FieldAfterPlanPriceSnapshot, v))
}

// AfterPlanPriceSnapshotNEQ applies the NEQ predicate on the "after_plan_price_snapshot" field.
func AfterPlanPriceSnapshotNEQ(v float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNEQ(FieldAfterPlanPriceSnapshot, v))
}

// AfterPlanPriceSnapshotIn applies the In predicate on the "after_plan_price_snapshot" field.
func AfterPlanPriceSnapshotIn(vs ...float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldIn(FieldAfterPlanPriceSnapshot, vs...))
}

// AfterPlanPriceSnapshotNotIn applies the NotIn predicate on the "after_plan_price_snapshot" field.
func AfterPlanPriceSnapshotNotIn(vs ...float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNotIn(FieldAfterPlanPriceSnapshot, vs...))
}

// AfterPlanPriceSnapshotGT applies the GT predicate on the "after_plan_price_snapshot" field.
func AfterPlanPriceSnapshotGT(v float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldGT(FieldAfterPlanPriceSnapshot, v))
}

// AfterPlanPriceSnapshotGTE applies the GTE predicate on the "after_plan_price_snapshot" field.
func AfterPlanPriceSnapshotGTE(v float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldGTE(FieldAfterPlanPriceSnapshot, v))
}

// AfterPlanPriceSnapshotLT applies the LT predicate on the "after_plan_price_snapshot" field.
func AfterPlanPriceSnapshotLT(v float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldLT(FieldAfterPlanPriceSnapshot, v))
}

// AfterPlanPriceSnapshotLTE applies the LTE predicate on the "after_plan_price_snapshot" field.
func AfterPlanPriceSnapshotLTE(v float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldLTE(FieldAfterPlanPriceSnapshot, v))
}

// AfterPlanPriceSnapshotIsNil applies the IsNil predicate on the "after_plan_price_snapshot" field.
func AfterPlanPriceSnapshotIsNil() predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldIsNull(FieldAfterPlanPriceSnapshot))
}

// AfterPlanPriceSnapshotNotNil applies the NotNil predicate on the "after_plan_price_snapshot" field.
func AfterPlanPriceSnapshotNotNil() predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNotNull(FieldAfterPlanPriceSnapshot))
}

// AfterValidityDaysSnapshotEQ applies the EQ predicate on the "after_validity_days_snapshot" field.
func AfterValidityDaysSnapshotEQ(v int) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldEQ(FieldAfterValidityDaysSnapshot, v))
}

// AfterValidityDaysSnapshotNEQ applies the NEQ predicate on the "after_validity_days_snapshot" field.
func AfterValidityDaysSnapshotNEQ(v int) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNEQ(FieldAfterValidityDaysSnapshot, v))
}

// AfterValidityDaysSnapshotIn applies the In predicate on the "after_validity_days_snapshot" field.
func AfterValidityDaysSnapshotIn(vs ...int) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldIn(FieldAfterValidityDaysSnapshot, vs...))
}

// AfterValidityDaysSnapshotNotIn applies the NotIn predicate on the "after_validity_days_snapshot" field.
func AfterValidityDaysSnapshotNotIn(vs ...int) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNotIn(FieldAfterValidityDaysSnapshot, vs...))
}

// AfterValidityDaysSnapshotGT applies the GT predicate on the "after_validity_days_snapshot" field.
func AfterValidityDaysSnapshotGT(v int) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldGT(FieldAfterValidityDaysSnapshot, v))
}

// AfterValidityDaysSnapshotGTE applies the GTE predicate on the "after_validity_days_snapshot" field.
func AfterValidityDaysSnapshotGTE(v int) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldGTE(FieldAfterValidityDaysSnapshot, v))
}

// AfterValidityDaysSnapshotLT applies the LT predicate on the "after_validity_days_snapshot" field.
func AfterValidityDaysSnapshotLT(v int) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldLT(FieldAfterValidityDaysSnapshot, v))
}

// AfterValidityDaysSnapshotLTE applies the LTE predicate on the "after_validity_days_snapshot" field.
func AfterValidityDaysSnapshotLTE(v int) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldLTE(FieldAfterValidityDaysSnapshot, v))
}

// AfterValidityDaysSnapshotIsNil applies the IsNil predicate on the "after_validity_days_snapshot" field.
func AfterValidityDaysSnapshotIsNil() predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldIsNull(FieldAfterValidityDaysSnapshot))
}

// AfterValidityDaysSnapshotNotNil applies the NotNil predicate on the "after_validity_days_snapshot" field.
func AfterValidityDaysSnapshotNotNil() predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNotNull(FieldAfterValidityDaysSnapshot))
}

// AfterValidityUnitSnapshotEQ applies the EQ predicate on the "after_validity_unit_snapshot" field.
func AfterValidityUnitSnapshotEQ(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldEQ(FieldAfterValidityUnitSnapshot, v))
}

// AfterValidityUnitSnapshotNEQ applies the NEQ predicate on the "after_validity_unit_snapshot" field.
func AfterValidityUnitSnapshotNEQ(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNEQ(FieldAfterValidityUnitSnapshot, v))
}

// AfterValidityUnitSnapshotIn applies the In predicate on the "after_validity_unit_snapshot" field.
func AfterValidityUnitSnapshotIn(vs ...string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldIn(FieldAfterValidityUnitSnapshot, vs...))
}

// AfterValidityUnitSnapshotNotIn applies the NotIn predicate on the "after_validity_unit_snapshot" field.
func AfterValidityUnitSnapshotNotIn(vs ...string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNotIn(FieldAfterValidityUnitSnapshot, vs...))
}

// AfterValidityUnitSnapshotGT applies the GT predicate on the "after_validity_unit_snapshot" field.
func AfterValidityUnitSnapshotGT(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldGT(FieldAfterValidityUnitSnapshot, v))
}

// AfterValidityUnitSnapshotGTE applies the GTE predicate on the "after_validity_unit_snapshot" field.
func AfterValidityUnitSnapshotGTE(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldGTE(FieldAfterValidityUnitSnapshot, v))
}

// AfterValidityUnitSnapshotLT applies the LT predicate on the "after_validity_unit_snapshot" field.
func AfterValidityUnitSnapshotLT(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldLT(FieldAfterValidityUnitSnapshot, v))
}

// AfterValidityUnitSnapshotLTE applies the LTE predicate on the "after_validity_unit_snapshot" field.
func AfterValidityUnitSnapshotLTE(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldLTE(FieldAfterValidityUnitSnapshot, v))
}

// AfterValidityUnitSnapshotContains applies the Contains predicate on the "after_validity_unit_snapshot" field.
func AfterValidityUnitSnapshotContains(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldContains(FieldAfterValidityUnitSnapshot, v))
}

// AfterValidityUnitSnapshotHasPrefix applies the HasPrefix predicate on the "after_validity_unit_snapshot" field.
func AfterValidityUnitSnapshotHasPrefix(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldHasPrefix(FieldAfterValidityUnitSnapshot, v))
}

// AfterValidityUnitSnapshotHasSuffix applies the HasSuffix predicate on the "after_validity_unit_snapshot" field.
func AfterValidityUnitSnapshotHasSuffix(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldHasSuffix(FieldAfterValidityUnitSnapshot, v))
}

// AfterValidityUnitSnapshotIsNil applies the IsNil predicate on the "after_validity_unit_snapshot" field.
func AfterValidityUnitSnapshotIsNil() predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldIsNull(FieldAfterValidityUnitSnapshot))
}

// AfterValidityUnitSnapshotNotNil applies the NotNil predicate on the "after_validity_unit_snapshot" field.
func AfterValidityUnitSnapshotNotNil() predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNotNull(FieldAfterValidityUnitSnapshot))
}

// AfterValidityUnitSnapshotEqualFold applies the EqualFold predicate on the "after_validity_unit_snapshot" field.
func AfterValidityUnitSnapshotEqualFold(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldEqualFold(FieldAfterValidityUnitSnapshot, v))
}

// AfterValidityUnitSnapshotContainsFold applies the ContainsFold predicate on the "after_validity_unit_snapshot" field.
func AfterValidityUnitSnapshotContainsFold(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldContainsFold(FieldAfterValidityUnitSnapshot, v))
}

// AfterStartsAtEQ applies the EQ predicate on the "after_starts_at" field.
func AfterStartsAtEQ(v time.Time) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldEQ(FieldAfterStartsAt, v))
}

// AfterStartsAtNEQ applies the NEQ predicate on the "after_starts_at" field.
func AfterStartsAtNEQ(v time.Time) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNEQ(FieldAfterStartsAt, v))
}

// AfterStartsAtIn applies the In predicate on the "after_starts_at" field.
func AfterStartsAtIn(vs ...time.Time) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldIn(FieldAfterStartsAt, vs...))
}

// AfterStartsAtNotIn applies the NotIn predicate on the "after_starts_at" field.
func AfterStartsAtNotIn(vs ...time.Time) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNotIn(FieldAfterStartsAt, vs...))
}

// AfterStartsAtGT applies the GT predicate on the "after_starts_at" field.
func AfterStartsAtGT(v time.Time) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldGT(FieldAfterStartsAt, v))
}

// AfterStartsAtGTE applies the GTE predicate on the "after_starts_at" field.
func AfterStartsAtGTE(v time.Time) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldGTE(FieldAfterStartsAt, v))
}

// AfterStartsAtLT applies the LT predicate on the "after_starts_at" field.
func AfterStartsAtLT(v time.Time) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldLT(FieldAfterStartsAt, v))
}

// AfterStartsAtLTE applies the LTE predicate on the "after_starts_at" field.
func AfterStartsAtLTE(v time.Time) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldLTE(FieldAfterStartsAt, v))
}

// AfterStartsAtIsNil applies the IsNil predicate on the "after_starts_at" field.
func AfterStartsAtIsNil() predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldIsNull(FieldAfterStartsAt))
}

// AfterStartsAtNotNil applies the NotNil predicate on the "after_starts_at" field.
func AfterStartsAtNotNil() predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNotNull(FieldAfterStartsAt))
}

// AfterExpiresAtEQ applies the EQ predicate on the "after_expires_at" field.
func AfterExpiresAtEQ(v time.Time) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldEQ(FieldAfterExpiresAt, v))
}

// AfterExpiresAtNEQ applies the NEQ predicate on the "after_expires_at" field.
func AfterExpiresAtNEQ(v time.Time) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNEQ(FieldAfterExpiresAt, v))
}

// AfterExpiresAtIn applies the In predicate on the "after_expires_at" field.
func AfterExpiresAtIn(vs ...time.Time) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldIn(FieldAfterExpiresAt, vs...))
}

// AfterExpiresAtNotIn applies the NotIn predicate on the "after_expires_at" field.
func AfterExpiresAtNotIn(vs ...time.Time) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNotIn(FieldAfterExpiresAt, vs...))
}

// AfterExpiresAtGT applies the GT predicate on the "after_expires_at" field.
func AfterExpiresAtGT(v time.Time) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldGT(FieldAfterExpiresAt, v))
}

// AfterExpiresAtGTE applies the GTE predicate on the "after_expires_at" field.
func AfterExpiresAtGTE(v time.Time) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldGTE(FieldAfterExpiresAt, v))
}

// AfterExpiresAtLT applies the LT predicate on the "after_expires_at" field.
func AfterExpiresAtLT(v time.Time) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldLT(FieldAfterExpiresAt, v))
}

// AfterExpiresAtLTE applies the LTE predicate on the "after_expires_at" field.
func AfterExpiresAtLTE(v time.Time) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldLTE(FieldAfterExpiresAt, v))
}

// AfterExpiresAtIsNil applies the IsNil predicate on the "after_expires_at" field.
func AfterExpiresAtIsNil() predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldIsNull(FieldAfterExpiresAt))
}

// AfterExpiresAtNotNil applies the NotNil predicate on the "after_expires_at" field.
func AfterExpiresAtNotNil() predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNotNull(FieldAfterExpiresAt))
}

// AfterDailyQuotaKnivesSnapshotEQ applies the EQ predicate on the "after_daily_quota_knives_snapshot" field.
func AfterDailyQuotaKnivesSnapshotEQ(v float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldEQ(FieldAfterDailyQuotaKnivesSnapshot, v))
}

// AfterDailyQuotaKnivesSnapshotNEQ applies the NEQ predicate on the "after_daily_quota_knives_snapshot" field.
func AfterDailyQuotaKnivesSnapshotNEQ(v float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNEQ(FieldAfterDailyQuotaKnivesSnapshot, v))
}

// AfterDailyQuotaKnivesSnapshotIn applies the In predicate on the "after_daily_quota_knives_snapshot" field.
func AfterDailyQuotaKnivesSnapshotIn(vs ...float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldIn(FieldAfterDailyQuotaKnivesSnapshot, vs...))
}

// AfterDailyQuotaKnivesSnapshotNotIn applies the NotIn predicate on the "after_daily_quota_knives_snapshot" field.
func AfterDailyQuotaKnivesSnapshotNotIn(vs ...float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNotIn(FieldAfterDailyQuotaKnivesSnapshot, vs...))
}

// AfterDailyQuotaKnivesSnapshotGT applies the GT predicate on the "after_daily_quota_knives_snapshot" field.
func AfterDailyQuotaKnivesSnapshotGT(v float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldGT(FieldAfterDailyQuotaKnivesSnapshot, v))
}

// AfterDailyQuotaKnivesSnapshotGTE applies the GTE predicate on the "after_daily_quota_knives_snapshot" field.
func AfterDailyQuotaKnivesSnapshotGTE(v float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldGTE(FieldAfterDailyQuotaKnivesSnapshot, v))
}

// AfterDailyQuotaKnivesSnapshotLT applies the LT predicate on the "after_daily_quota_knives_snapshot" field.
func AfterDailyQuotaKnivesSnapshotLT(v float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldLT(FieldAfterDailyQuotaKnivesSnapshot, v))
}

// AfterDailyQuotaKnivesSnapshotLTE applies the LTE predicate on the "after_daily_quota_knives_snapshot" field.
func AfterDailyQuotaKnivesSnapshotLTE(v float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldLTE(FieldAfterDailyQuotaKnivesSnapshot, v))
}

// AfterDailyQuotaKnivesSnapshotIsNil applies the IsNil predicate on the "after_daily_quota_knives_snapshot" field.
func AfterDailyQuotaKnivesSnapshotIsNil() predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldIsNull(FieldAfterDailyQuotaKnivesSnapshot))
}

// AfterDailyQuotaKnivesSnapshotNotNil applies the NotNil predicate on the "after_daily_quota_knives_snapshot" field.
func AfterDailyQuotaKnivesSnapshotNotNil() predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNotNull(FieldAfterDailyQuotaKnivesSnapshot))
}

// AfterWeeklyQuotaKnivesSnapshotEQ applies the EQ predicate on the "after_weekly_quota_knives_snapshot" field.
func AfterWeeklyQuotaKnivesSnapshotEQ(v float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldEQ(FieldAfterWeeklyQuotaKnivesSnapshot, v))
}

// AfterWeeklyQuotaKnivesSnapshotNEQ applies the NEQ predicate on the "after_weekly_quota_knives_snapshot" field.
func AfterWeeklyQuotaKnivesSnapshotNEQ(v float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNEQ(FieldAfterWeeklyQuotaKnivesSnapshot, v))
}

// AfterWeeklyQuotaKnivesSnapshotIn applies the In predicate on the "after_weekly_quota_knives_snapshot" field.
func AfterWeeklyQuotaKnivesSnapshotIn(vs ...float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldIn(FieldAfterWeeklyQuotaKnivesSnapshot, vs...))
}

// AfterWeeklyQuotaKnivesSnapshotNotIn applies the NotIn predicate on the "after_weekly_quota_knives_snapshot" field.
func AfterWeeklyQuotaKnivesSnapshotNotIn(vs ...float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNotIn(FieldAfterWeeklyQuotaKnivesSnapshot, vs...))
}

// AfterWeeklyQuotaKnivesSnapshotGT applies the GT predicate on the "after_weekly_quota_knives_snapshot" field.
func AfterWeeklyQuotaKnivesSnapshotGT(v float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldGT(FieldAfterWeeklyQuotaKnivesSnapshot, v))
}

// AfterWeeklyQuotaKnivesSnapshotGTE applies the GTE predicate on the "after_weekly_quota_knives_snapshot" field.
func AfterWeeklyQuotaKnivesSnapshotGTE(v float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldGTE(FieldAfterWeeklyQuotaKnivesSnapshot, v))
}

// AfterWeeklyQuotaKnivesSnapshotLT applies the LT predicate on the "after_weekly_quota_knives_snapshot" field.
func AfterWeeklyQuotaKnivesSnapshotLT(v float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldLT(FieldAfterWeeklyQuotaKnivesSnapshot, v))
}

// AfterWeeklyQuotaKnivesSnapshotLTE applies the LTE predicate on the "after_weekly_quota_knives_snapshot" field.
func AfterWeeklyQuotaKnivesSnapshotLTE(v float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldLTE(FieldAfterWeeklyQuotaKnivesSnapshot, v))
}

// AfterWeeklyQuotaKnivesSnapshotIsNil applies the IsNil predicate on the "after_weekly_quota_knives_snapshot" field.
func AfterWeeklyQuotaKnivesSnapshotIsNil() predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldIsNull(FieldAfterWeeklyQuotaKnivesSnapshot))
}

// AfterWeeklyQuotaKnivesSnapshotNotNil applies the NotNil predicate on the "after_weekly_quota_knives_snapshot" field.
func AfterWeeklyQuotaKnivesSnapshotNotNil() predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNotNull(FieldAfterWeeklyQuotaKnivesSnapshot))
}

// AfterMonthlyQuotaKnivesSnapshotEQ applies the EQ predicate on the "after_monthly_quota_knives_snapshot" field.
func AfterMonthlyQuotaKnivesSnapshotEQ(v float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldEQ(FieldAfterMonthlyQuotaKnivesSnapshot, v))
}

// AfterMonthlyQuotaKnivesSnapshotNEQ applies the NEQ predicate on the "after_monthly_quota_knives_snapshot" field.
func AfterMonthlyQuotaKnivesSnapshotNEQ(v float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNEQ(FieldAfterMonthlyQuotaKnivesSnapshot, v))
}

// AfterMonthlyQuotaKnivesSnapshotIn applies the In predicate on the "after_monthly_quota_knives_snapshot" field.
func AfterMonthlyQuotaKnivesSnapshotIn(vs ...float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldIn(FieldAfterMonthlyQuotaKnivesSnapshot, vs...))
}

// AfterMonthlyQuotaKnivesSnapshotNotIn applies the NotIn predicate on the "after_monthly_quota_knives_snapshot" field.
func AfterMonthlyQuotaKnivesSnapshotNotIn(vs ...float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNotIn(FieldAfterMonthlyQuotaKnivesSnapshot, vs...))
}

// AfterMonthlyQuotaKnivesSnapshotGT applies the GT predicate on the "after_monthly_quota_knives_snapshot" field.
func AfterMonthlyQuotaKnivesSnapshotGT(v float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldGT(FieldAfterMonthlyQuotaKnivesSnapshot, v))
}

// AfterMonthlyQuotaKnivesSnapshotGTE applies the GTE predicate on the "after_monthly_quota_knives_snapshot" field.
func AfterMonthlyQuotaKnivesSnapshotGTE(v float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldGTE(FieldAfterMonthlyQuotaKnivesSnapshot, v))
}

// AfterMonthlyQuotaKnivesSnapshotLT applies the LT predicate on the "after_monthly_quota_knives_snapshot" field.
func AfterMonthlyQuotaKnivesSnapshotLT(v float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldLT(FieldAfterMonthlyQuotaKnivesSnapshot, v))
}

// AfterMonthlyQuotaKnivesSnapshotLTE applies the LTE predicate on the "after_monthly_quota_knives_snapshot" field.
func AfterMonthlyQuotaKnivesSnapshotLTE(v float64) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldLTE(FieldAfterMonthlyQuotaKnivesSnapshot, v))
}

// AfterMonthlyQuotaKnivesSnapshotIsNil applies the IsNil predicate on the "after_monthly_quota_knives_snapshot" field.
func AfterMonthlyQuotaKnivesSnapshotIsNil() predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldIsNull(FieldAfterMonthlyQuotaKnivesSnapshot))
}

// AfterMonthlyQuotaKnivesSnapshotNotNil applies the NotNil predicate on the "after_monthly_quota_knives_snapshot" field.
func AfterMonthlyQuotaKnivesSnapshotNotNil() predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNotNull(FieldAfterMonthlyQuotaKnivesSnapshot))
}

// AfterSubscriptionStatusEQ applies the EQ predicate on the "after_subscription_status" field.
func AfterSubscriptionStatusEQ(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldEQ(FieldAfterSubscriptionStatus, v))
}

// AfterSubscriptionStatusNEQ applies the NEQ predicate on the "after_subscription_status" field.
func AfterSubscriptionStatusNEQ(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNEQ(FieldAfterSubscriptionStatus, v))
}

// AfterSubscriptionStatusIn applies the In predicate on the "after_subscription_status" field.
func AfterSubscriptionStatusIn(vs ...string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldIn(FieldAfterSubscriptionStatus, vs...))
}

// AfterSubscriptionStatusNotIn applies the NotIn predicate on the "after_subscription_status" field.
func AfterSubscriptionStatusNotIn(vs ...string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNotIn(FieldAfterSubscriptionStatus, vs...))
}

// AfterSubscriptionStatusGT applies the GT predicate on the "after_subscription_status" field.
func AfterSubscriptionStatusGT(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldGT(FieldAfterSubscriptionStatus, v))
}

// AfterSubscriptionStatusGTE applies the GTE predicate on the "after_subscription_status" field.
func AfterSubscriptionStatusGTE(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldGTE(FieldAfterSubscriptionStatus, v))
}

// AfterSubscriptionStatusLT applies the LT predicate on the "after_subscription_status" field.
func AfterSubscriptionStatusLT(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldLT(FieldAfterSubscriptionStatus, v))
}

// AfterSubscriptionStatusLTE applies the LTE predicate on the "after_subscription_status" field.
func AfterSubscriptionStatusLTE(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldLTE(FieldAfterSubscriptionStatus, v))
}

// AfterSubscriptionStatusContains applies the Contains predicate on the "after_subscription_status" field.
func AfterSubscriptionStatusContains(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldContains(FieldAfterSubscriptionStatus, v))
}

// AfterSubscriptionStatusHasPrefix applies the HasPrefix predicate on the "after_subscription_status" field.
func AfterSubscriptionStatusHasPrefix(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldHasPrefix(FieldAfterSubscriptionStatus, v))
}

// AfterSubscriptionStatusHasSuffix applies the HasSuffix predicate on the "after_subscription_status" field.
func AfterSubscriptionStatusHasSuffix(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldHasSuffix(FieldAfterSubscriptionStatus, v))
}

// AfterSubscriptionStatusEqualFold applies the EqualFold predicate on the "after_subscription_status" field.
func AfterSubscriptionStatusEqualFold(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldEqualFold(FieldAfterSubscriptionStatus, v))
}

// AfterSubscriptionStatusContainsFold applies the ContainsFold predicate on the "after_subscription_status" field.
func AfterSubscriptionStatusContainsFold(v string) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldContainsFold(FieldAfterSubscriptionStatus, v))
}

// EffectiveAtEQ applies the EQ predicate on the "effective_at" field.
func EffectiveAtEQ(v time.Time) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldEQ(FieldEffectiveAt, v))
}

// EffectiveAtNEQ applies the NEQ predicate on the "effective_at" field.
func EffectiveAtNEQ(v time.Time) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNEQ(FieldEffectiveAt, v))
}

// EffectiveAtIn applies the In predicate on the "effective_at" field.
func EffectiveAtIn(vs ...time.Time) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldIn(FieldEffectiveAt, vs...))
}

// EffectiveAtNotIn applies the NotIn predicate on the "effective_at" field.
func EffectiveAtNotIn(vs ...time.Time) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNotIn(FieldEffectiveAt, vs...))
}

// EffectiveAtGT applies the GT predicate on the "effective_at" field.
func EffectiveAtGT(v time.Time) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldGT(FieldEffectiveAt, v))
}

// EffectiveAtGTE applies the GTE predicate on the "effective_at" field.
func EffectiveAtGTE(v time.Time) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldGTE(FieldEffectiveAt, v))
}

// EffectiveAtLT applies the LT predicate on the "effective_at" field.
func EffectiveAtLT(v time.Time) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldLT(FieldEffectiveAt, v))
}

// EffectiveAtLTE applies the LTE predicate on the "effective_at" field.
func EffectiveAtLTE(v time.Time) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldLTE(FieldEffectiveAt, v))
}

// ClosedAtEQ applies the EQ predicate on the "closed_at" field.
func ClosedAtEQ(v time.Time) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldEQ(FieldClosedAt, v))
}

// ClosedAtNEQ applies the NEQ predicate on the "closed_at" field.
func ClosedAtNEQ(v time.Time) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNEQ(FieldClosedAt, v))
}

// ClosedAtIn applies the In predicate on the "closed_at" field.
func ClosedAtIn(vs ...time.Time) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldIn(FieldClosedAt, vs...))
}

// ClosedAtNotIn applies the NotIn predicate on the "closed_at" field.
func ClosedAtNotIn(vs ...time.Time) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNotIn(FieldClosedAt, vs...))
}

// ClosedAtGT applies the GT predicate on the "closed_at" field.
func ClosedAtGT(v time.Time) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldGT(FieldClosedAt, v))
}

// ClosedAtGTE applies the GTE predicate on the "closed_at" field.
func ClosedAtGTE(v time.Time) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldGTE(FieldClosedAt, v))
}

// ClosedAtLT applies the LT predicate on the "closed_at" field.
func ClosedAtLT(v time.Time) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldLT(FieldClosedAt, v))
}

// ClosedAtLTE applies the LTE predicate on the "closed_at" field.
func ClosedAtLTE(v time.Time) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldLTE(FieldClosedAt, v))
}

// ClosedAtIsNil applies the IsNil predicate on the "closed_at" field.
func ClosedAtIsNil() predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldIsNull(FieldClosedAt))
}

// ClosedAtNotNil applies the NotNil predicate on the "closed_at" field.
func ClosedAtNotNil() predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNotNull(FieldClosedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasOperator applies the HasEdge predicate on the "operator" edge.
func HasOperator() predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OperatorTable, OperatorColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOperatorWith applies the HasEdge predicate on the "operator" edge with a given conditions (other predicates).
func HasOperatorWith(preds ...predicate.User) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(func(s *sql.Selector) {
		step := newOperatorStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasNext applies the HasEdge predicate on the "next" edge.
func HasNext() predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, NextTable, NextColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasNextWith applies the HasEdge predicate on the "next" edge with a given conditions (other predicates).
func HasNextWith(preds ...predicate.SubscriptionSettlementOrder) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(func(s *sql.Selector) {
		step := newNextStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPrevious applies the HasEdge predicate on the "previous" edge.
func HasPrevious() predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, PreviousTable, PreviousColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPreviousWith applies the HasEdge predicate on the "previous" edge with a given conditions (other predicates).
func HasPreviousWith(preds ...predicate.SubscriptionSettlementOrder) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(func(s *sql.Selector) {
		step := newPreviousStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAfterUserSubscription applies the HasEdge predicate on the "after_user_subscription" edge.
func HasAfterUserSubscription() predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AfterUserSubscriptionTable, AfterUserSubscriptionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAfterUserSubscriptionWith applies the HasEdge predicate on the "after_user_subscription" edge with a given conditions (other predicates).
func HasAfterUserSubscriptionWith(preds ...predicate.UserSubscription) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(func(s *sql.Selector) {
		step := newAfterUserSubscriptionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAfterPlan applies the HasEdge predicate on the "after_plan" edge.
func HasAfterPlan() predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AfterPlanTable, AfterPlanColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAfterPlanWith applies the HasEdge predicate on the "after_plan" edge with a given conditions (other predicates).
func HasAfterPlanWith(preds ...predicate.SubscriptionPlan) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(func(s *sql.Selector) {
		step := newAfterPlanStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SubscriptionSettlementOrder) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SubscriptionSettlementOrder) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SubscriptionSettlementOrder) predicate.SubscriptionSettlementOrder {
	return predicate.SubscriptionSettlementOrder(sql.NotPredicates(p))
}
